### ISSUE TITLE
Wiki: missing pages

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#100]
The following pages are missing:
- [ ] Ship core
- [ ] Warp armor

The following pages are incomplete:
- [x] Force field upgrades (item port, attraction & repulsion)
- [ ] Advanced laser tutorial (add a comment regarding OpenComputers)
- [ ] World generation

The following blocks are non-functional, hence have no pages yet:
- [x] Transporter
- [x] Ship scanner

The following wiki pages have obsolete or missing pictures:
- [ ] https://github.com/LemADEC/WarpDrive/wiki/Getting-Started%3A-Part-One%2C-The-Basics
- [ ] https://github.com/LemADEC/WarpDrive/wiki/Laser-setup-%28basic%29
- [ ] https://github.com/LemADEC/WarpDrive/wiki/Laser-setup-%28advanced%29

**Comment by Sasszem** [comment]
Transporter page also missing :(

**Comment by FirstArchon** [comment]
page for ship scanner block also missing

**Comment by LemADEC** [comment]
Updated for clarity

**Comment by Sasszem** [comment]
Actually, You can figure out the transporter, but It was took me half an hour to get it work.

**Comment by LemADEC** [comment]
Laser tree farm has its own page now.

**Comment by Sasszem** [comment]
Cool

**Comment by blazelink3** [comment]
Another missing page (for the latest update so sorry if I sounds entitled or anything along those lines, I'm not trying to be) is the weapon controller, how do you network the lasers to it?

**Comment by LemADEC** [comment]
I've added a short explanation on the advanced laser tutorial to introduce the Weapon controller.

**Comment by pe-ia** [comment]
Since a lot of people wanted a wiki page for the transporter I made one

**Comment by LemADEC** [comment]
There's now an in-game manual. Wiki remains online but won't be maintained anymore.
