### ISSUE TITLE
[improvement] Determining ship size automatically

### ISSUE THREAD

**Issue by Cr0s** [LemADEC/WarpDrive#104]
It would be better that we can determine ship size automatically or with player's guidance using some marker-blocks.

There is some possible ways to play with:
1. **Breadth-first search** (with some depth limit depending on maximum ship size, of course) to calculate ship's volume blocks and all 6 dimensions (up, down, right, left, front, back)
2. **Marker blocks**, placed on 6 sides from the core depending on all six dimensions. Marker blocks can be placed not on the exactly same line as the core, but in some area around core's coordinates in specific dimension.

**Comment by LemADEC** [comment]
As a first step for players, we could just add a overlay view in game of the ship dimensions, eventually use a tool item to adjust the dimensions.

I prefer the flood fill approach. Not sure how much different it is from "breadth-first search".
To implement that, we need to refactor JumpEntity in a sequencer vs ship definition classes. This will enable other things to come like forcefields, etc.
We'll need to define 'bridge' and 'exclusion' blocks to stop the search.

**Comment by Cr0s** [comment]
Flood fill is eventually more correct than BFS, because flood fill is a special case of BFS on multi-dimensional uniform gird like Minecraft world or some 2d tiled maze.

**Comment by LemADEC** [comment]
so Flood fill it is :)

**Comment by Nyabloody** [comment]
Sorry to bump this, but any news for the auto-define ship size thing? It would be really helpful because it's actually a big pain to find the exact dimensions for some ships. And ... why the Front side is West, the Back side is East and so on? It's really weird... I don't remember having that issue while back in 1.6.4 with Cr0s original mod.

**Comment by LemADEC** [comment]
The warp controller is the front of your ship, same as in 1.6.4.

**Comment by Nyabloody** [comment]
So it depends the way I place down the warp controller in my ship?

**Comment by LemADEC** [comment]
yes, it does influence how your ship size is measured and which direction it's moving

**Comment by Nyabloody** [comment]
Ok I've made further tests and I can tell you it's wrong. No matter how I place down the ship controller, the Front side is always West. I could provide you some screenshots if you want? But I'm sure there is something wrong there.

EDIT:
I'm sorry, you're right in the end. It depends on which side of the ship core is placed the controller. But it should be mentioned on the wiki or somewhere else...

**Comment by LemADEC** [comment]
It's written in the mod description itself:
"
How to play?
Your ship is centered around a Warp core with a Warp controller. Both needs to be placed horizontally next to each others. The Warp core receives both EU and RF power. The Warp controller defines the front of your ship and connects with a ComputerCraft Advanced computer or OpenComputer equivalent.
"

Sadly, there's no wiki page for it, yet.
I'll add some tool tips to the blocks.

**Comment by LemADEC** [comment]
Already tracked in #29
