### ISSUE TITLE
Consider refactoring of asteroid generation

### ISSUE THREAD

**Issue by Cr0s** [LemADEC/WarpDrive#105]
Can someone explain to me, for what reason we decide to drop existing generation code and replace it with another, which is more complicated and even doesn't work?

https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/config/structures/Asteroid.java#L253

Instead of breaking working things in main branch, we should create a separate branch for each significant code change, prototypes, etc.

**Comment by LemADEC** [comment]
We needed something configurable, so we went into XML configuration implementation instead of porting the existing system.
The XML format needs to be tried in real-life before we can refactor it.

**Comment by LemADEC** [comment]
and yes, it's a mess and the only reason we're still in alpha

**Comment by Cr0s** [comment]
I suggesting to remove this xml-thingy into separate branch and port the original generator until (and if) Numenorean finished his generator.

**Comment by LemADEC** [comment]
I'll do a pass on it this week.

**Comment by NCrashed** [comment]
PR is merged, @Cr0s is that enough to close the issue?

**Comment by Cr0s** [comment]
:+1:
