### ISSUE TITLE
Wiki: add instructions for deploying dev environment

### ISSUE THREAD

**Issue by NCrashed** [LemADEC/WarpDrive#107]
I have some problems with the topic. What I have done:

```
./gradlew setupDecompWorkspace
./gradlew eclipse
```

And starting MC with `GradleStart` class.

But:
- IC2 and other mods (despite WarpDrive) aren't loaded
- Access Transformers aren't applied - gravity in space is broken

So, I request step-by-step instruction how to configure all for eclipse development.

**Comment by LemADEC** [comment]
There's a eclipse/mods folder in the repository, you need to copy that mods folder in your execution environment. The WarpDriveCore-dev is a fake mod to force Forge to run the integrate coremod and enable gravity and breathing hooks.

The code formating rules are to be loaded fomr Eclipse-nowrap.xml.

**Comment by NCrashed** [comment]
Copied. Codechiken wants mcp configs at startup and there aren't any within gradle environment. Actually it needs following files: `packaged.srg` or `joined.srg`, and `methods.csv`. 

Current workaround: download [mcp-9.08](http://www.modcoderpack.com/website/content/mcp-908), unpack and feed `conf` folder to file chooser.

P.S. `packaged.src` could be found at `build/tmp/recompSrc` but `methods.csv` is missing.

**Comment by LemADEC** [comment]
If I remember right, you need to setup Dev workspace, not Decomp workspace.

**Comment by NCrashed** [comment]
Just tried from scratch with `setupDevWorkspace`, the same behavior is presented. Codechiken wants the mcp files and there are none in workspace.

**Comment by TheNumenorean** [comment]
I originally set it up with setupDecompWorkspace

**Comment by TheNumenorean** [comment]
Have you tried starting it from Eclipse?

**Comment by NCrashed** [comment]
I started it only from eclipse with Startgradle class.

**Comment by LemADEC** [comment]
CodeChickenCore is needed when using non-dev mods but it's not working with the ones we need (CC and OC).
Since IC2 is already 'dev', you don't really need CodeChickenCore in the mods folder.

Did you do the setupDevWorkspace on Forge or WarpDrive?

**Comment by NCrashed** [comment]
> CodeChickenCore is needed when using non-dev mods but it's not working with the ones we need (CC and OC).
> Since IC2 is already 'dev', you don't really need CodeChickenCore in the mods folder.

Ok, it just was in `eclipse/mods` folder.

> Did you do the setupDevWorkspace on Forge or WarpDrive?

Yep, I did `./gradle setupDevWorkspace`.

**Comment by LemADEC** [comment]
Try that command on the Forge installation itself.

**Comment by LemADEC** [comment]
Read me updated, dependencies simplified, closing
