### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by CaptainMegavolt** [LemADEC/WarpDrive#108]
A few suggestions for this awesome mos:
-MetaWorlds mod-like multiblock entities for ships (so ships actually fly smoothly), and on a related note, engine blocks for non-warp travel.
-If the MetaWorlds thing is not possible, maybe add ability to turn ships?
-Cloaking/Decloaking animation (star trek ripple-in-space style?)
-Hyperspace animated skybox (sorta like hyperspace travel in star wars)
-Some kind of flat image or some such thing in space to indicate where "planets" are (planet images could maybe be added in folder in .minecraft), so you can see the earth beneath you, or whatever.
-Some randomly-generated planets included in vanilla WarpDrive
-Better gravity? (ships need gravity generators)
-More ship/spacestation weapons (missile-type things (photon torpedos?), plasma cannons (or some such thing), and other stuff)
-Tractor beams? (slowly pulls blocks in its beam towards itself)
-Phase-shift device? (like in that Star Trek Next generation episode where the romulans invent a phasehifter and accidentally shift Jordy out of phase)

**Comment by LemADEC** [comment]
- Fly-by mod is already planned, see related ticket
- turn ships will come back later on
- yes, we're missing a few animations for cloaking and warping
- skyboxes are in Cr0s priority tasks
- planets display are part of skyboxes
- worldgeneration is our top priority and the only reason we're still in alpha
- not sure to catch your point on gravity, please open a separate ticket to discuss it
- new weapons are already planned, see related tickets
- see above
- see above

**Comment by CaptainMegavolt** [comment]
Regarding the gravity thing, yes i'll put a separate issue for it, but to clarify what I meant by "better gravity mechanics". What I was thinking was: 1. Improve gravity mechanics in space so that entities floating in space drift in whatever direction their momentum was last in (see galacticraft space station mechanics), and their trajectory will go towards whatever the nearest gravity well is (determined by the concentration of blocks there, even from the side or below the object. And 2. Spaceships do not innately have enough gravity to hold stuff down, so a gravity generator is required. This requires a bit of electricity and uses input from a CC computer to change gravity within the ship (detected by way of the contiguous block structure of the ship)

**Comment by LemADEC** [comment]
ok, all those points are cleared out or tracked elsewhere, closing
