### ISSUE TITLE
Small Request

### ISSUE THREAD

**Issue by Sable501** [LemADEC/WarpDrive#109]
First off, I love this mod. In my mod list, this is one of my core mods. I have two relatively simple requests: 1. A config option to increase the air duration of the air tanks added by the mod; current air duration is roughly 30 seconds, and I'd personally like to set it to 4 or 5 minutes. Either that or the ability to use Galacticraft oxygen tanks instead. I like using a capital ship as an aircraft carrier for my MCHeli aircraft; that's right, I fly helicopters in space, physics be damned. However, running out of air is a serious concern when you're a fighter pilot in a space battle. 2. A config option to disable publicly announcing whenever someone warps. Me and my friends play over a LAN and it makes surprise attacks a little difficult.

I do realize you're busy with more pressing matters, but I'd love to see these config options added.

Sincerely,
Sable501

**Comment by LemADEC** [comment]
Warp helmet was indeed bugged out, should be fixed in next update.

Warp announcements are already only visible to player aboard the ship.
