### ISSUE TITLE
Crash when we try to land between planets or in void...

### ISSUE THREAD

**Issue by Nyabloody** [LemADEC/WarpDrive#113]
I've set some planets from Galacticraft in WarpDrive.cfg. Here is my setup: http://pastebin.com/2xY7AN1H

Everytime I try to land between Moon and Mars = crash! When I reload the game, everything is back to normal and I'm still in space dimension!

I wonder if I did something wrong but shouldn't be a warning message or something to tell that the jump failed because there are no planets to land there? I checked the mod's sources and found this: https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/EntityJump.java#L417

So in theory I should get that warning message instead of a crash, right? =P

**Comment by LemADEC** [comment]
I'll need your logs to understand what's going on.

Your configuration is invalid on X axis:
Mars X in space = 8000 to 16000
Moon X in space = 2000 to 10000
Overworld X in space = -6000 to 6000
Venus X in space = -14000 to -2000

Even with that faulty configuration, it should take the closest planet and continue without crashing. I'll need your logs to understand what's going wrong here.

**Comment by Nyabloody** [comment]
Could you show me then how you would do for adding other planets to the configuration? Because I'm totally lost. And here is my crash-report: http://pastebin.com/eh5EXRAL

An other question, how do you get out from hyperspace with a small ship? I successfully entered into hyperspace using a jumpgate but now I'm stuck... I tried to to jump under or above the limits, tried to jump to another jumpgate and tried to use the hyperspace again without any results.

**Comment by LemADEC** [comment]
I'll need your server logs too, from boot up to the crash.

Try with that configuration which gives more space between your planets: http://pastebin.com/5uxMbgYj

Your small ship needs to align with another jumpgate to exit hyperspace. This can be a bit tricky since those aren't visible in that dimension, yet.

**Comment by Nyabloody** [comment]
It's a singleplayer map, here is the full log anyway:
https://dl.dropboxusercontent.com/u/11797022/mc/logs/fml-client-latest.log

Woa... with your configuration it means that I would need to travel around 42K blocks to reach Mars? Is that correct?

I even tried to spawn a jumpgate in space dimension right at the coordinates where my ship is. It failed to exit hyperspace... So I guess there is a bug or something. What about creating a similar function like the nether portal does when it spawn himself in the nether? So the jumpgate would appear right in the hyperspace dimension when you enter it with a small ship. Just an idea btw.

**Comment by LemADEC** [comment]
Looks like we're unable to load the Mars dimension. It's a regression, will have to fix that.

Mars is supposed to be much further away than the moon, so yeah, I've set it up to 42k between both centers, or 32k borders to borders if you prefer.

Regarding Jumpgate creation, the hard part is to remember whether it's already placed or not, and recover from related server crashes.
