### ISSUE TITLE
No recipe for the enantiomorphic reactor?

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#114]
Should there be one?

**Comment by LemADEC** [comment]
![image](https://cloud.githubusercontent.com/assets/4776032/11759973/3798daf4-a088-11e5-82ac-7a73f9599138.png)
![image](https://cloud.githubusercontent.com/assets/4776032/11759975/434b2dc0-a088-11e5-9fa7-8656dd61002c.png)

Recipes are there.
Only Dynamic recipe set is supported.

**Comment by TheNumenorean** [comment]
So, interestingly, the recipe does not show up in NEI, either for the core or the laser itself. It would probably be worth trying to figure out a way to accomplish that.

**Comment by LemADEC** [comment]
It might happen if we try to use a missing item.
What mods do you have involved?

**Comment by TheNumenorean** [comment]
Why do we only support the reactor if dynamic recipes are enabled? Shouldn't we have standard IC2 recipes?

**Comment by LemADEC** [comment]
Only Dynamic Recipes are supported globally. The others are deprecated and will be removed when we move to 1.8.
Or someone make pull request with the updates for them.

**Comment by TheNumenorean** [comment]
Ill just update them myself. Personally, I do not like the dynamic recipes.
