### ISSUE TITLE
weird oxygen glitch

### ISSUE THREAD

**Issue by Cooper71234** [LemADEC/WarpDrive#119]
Hi im having this weird glitch that while im in my ship theres one oxygen block on my head and it wont dissapear and moves with me it doesnt follow me to other rooms but it follows me while im inside that specific room its really annoying.im playing the 1.7.10 beta.
heres a screenshot of the bubble
![2015-12-21_19 26 18](https://cloud.githubusercontent.com/assets/16120516/11934727/20958828-a819-11e5-83a8-ff8273c9df5c.png)
![2015-12-21_19 26 21](https://cloud.githubusercontent.com/assets/16120516/11934730/260ce6fc-a819-11e5-8ac1-4e60aee2b7ef.png)
![2015-12-21_19 26 25](https://cloud.githubusercontent.com/assets/16120516/11934734/2c73f9ae-a819-11e5-874d-e43bceeeda63.png)

**Comment by LemADEC** [comment]
This was fixed some time ago, update to latest version and try agian
