### ISSUE TITLE
Duplicate ids with MatterOverdrive?

### ISSUE THREAD

**Issue by FarmerGadda** [LemADEC/WarpDrive#120]
Hello there! Forgive me for bothering you, this is a minor issue in hindsight, but I figured I ought to at least let people know it exists. I attempted to play Single player with some alike mods and came across this little incompatibility. The Id in question is with your "Transporter." I never thought I'd see the day where I actually missed numerical ids? XD

Now, I'm not demanding or even asking that anything be changed-I just came from MatterOverdrive's github and gave them much of the same message, so perhaps they'll change something on their end? But with this mod offering space travel and theirs offering Star Trek-esque replicators and phasers... I find it plausible that I won't be the only person who attempts to use both at once? Again, sorry for bothering you, but thank you for your time!
[crash-2015-12-28_20.18.36-client.txt](https://github.com/LemADEC/WarpDrive/files/73679/crash-2015-12-28_20.18.36-client.txt)

**Comment by CaptainMegavolt** [comment]
AHA! I have been having the exact same problem.

**Comment by LemADEC** [comment]
That bug was fixed more than 4 months ago, do us a favor and update your mods before reporting an issue :)
