### ISSUE TITLE
Camera problem in 1.7

### ISSUE THREAD

**Issue by CaptainMegavolt** [LemADEC/WarpDrive#122]
Whenever I warp or jump to hyperspace in the 1.7 version, my camera blocks come along with the ship but the monitors say they are out of range, unless I warp back to the exact location where I built the ship.

**Comment by LemADEC** [comment]
There's a 15 to 20 seconds delay for the camera and monitor to resynchronise each others.

**Comment by CaptainMegavolt** [comment]
It doenst work at all, like ever. Even after a delay. I have warped, gone off and repaired my enantiomorphic reactor (which exploded) and come back to test my lasercams and cameras, and they all said out of range.

**Comment by LemADEC** [comment]
Issue is specific to SMP

**Comment by CaptainMegavolt** [comment]
Hmm. I believe I was playing LAN at the time. Thanks for the tips

**Comment by LemADEC** [comment]
Fixed in d49bb546f991a15fae42518c42255291882b61ce
