### ISSUE TITLE
Tiered Warp Cores

### ISSUE THREAD

**Issue by CaptainMegavolt** [LemADEC/WarpDrive#123]
I recently had a look at the issue regarding a 'slots' system, and had an idea: What if there were multiple tiers of warp cores, and each could support a different size and complexity of ship? So for example, a Mk. 1 warp core would be able to support, say, a ship with max dimensions of 20x20x20, a max of one laser, and so on.

On a related note, if something like this gets implemented, could the Hyperdrive be a separate device, say, some sort of big multiblock, and only works on ships with a high enough tier warp core and enough mass. Hyperdrive is controlled independently from warp drive. Also, on hyperdrive energy consumption: Entering hyperspace requires a lot of energy, and once you're in hyperspace, the hyperdrive continues using energy as long as you remain in hyperspace. Leaving hyperspace is free, and you automatically get ejected from hyperspace if your hyperdrive runs out of energy. The logic here is that hyperdrives need to raise your entire ship into a higher energy dimension, which takes a lot of kick-off energy, but keeps using energy once there to maintain a higher energy state. Also, if you leave the bounds of your ship (as defined by the warp core) while in hyperspace, you instantly die (as supposedly you are leaving the hyperdrive's energy field, and are torn apart by high-energy particles).

**Comment by LemADEC** [comment]
The current idea is to use structural blocks as tiers while keeping the same ship core block. In other words, you'll need higher tier structure and more of them to build bigger ships.

To my interpretation of the lores, an hyperdrive is a fantasy warpdrive with infinite speed, very small footprint and no side effect. If you prefer, it's a creative warpdrive engine.

Ship core will remain. Ship controller is subject to debate, we might merge both in a single block.
The warp capability will eventually move into structure blocks (a bit like nacelles), the more the faster you can move.
The player teleportation will eventually move to the transporter blocks.

Hyperspace dimension will be revamped in the coming months when we'll add more realistics star systems with planet movements.

**Comment by CaptainMegavolt** [comment]
On the subject of hyperdrives, I have always understood them to be devices that consume a very late amount of energy to get a ship into Hyperspace, where the ship would travel using its own sublight enginez, but when it left Hyperspace it would have traveled vastly further in real space than it had in Hyperspace.

My suggestion that hyperdrive be a separate block was just to have a separate device to get your ship into Hyperspace l, which functions as I described it. Once in Hyperspace you use your normal warp drive to get around, but you move a lot further relative to real space

**Comment by LemADEC** [comment]
Already covered in other issues, closing
