### ISSUE TITLE
A Few Things

### ISSUE THREAD

**Issue by Beadsmith2** [LemADEC/WarpDrive#126]
1 - Firstly, I would like to note that this mod is not compatible with the "Smart Moving" mod (for 1.7.10). Not sure if that's fixable, but I thought I'd bring it up. It also doesn't work with ArchimedesShips+, but it does work with the original, ArchimedesShips.

2 - I am 21 years old, love Sci Fi (especially Star Trek), and have been modding Minecraft for over 2 years now. I have seen a lot of good mods (and bad ones). But, I think this mod is, if not the best mod, definitely up there. (At least top 3)

3 - There is another mod, by Simeon Radivoev, called "Matter Overdrive," which I thought I'd direct your attention to. It is also a Star Trek based mod, which focuses more on the "science" side of Star Trek. Maybe you two could touch base, and merge your mods? That would be the most epic mod ever. (I am going to leave a similar comment on his page) I hope to see you guys working together in the future! His mod can be found here. --- http://simeon.co.vu/Mods/MatterOverdrive/ ---  I think you will like what he has done.

4 - Also, if you want, (I am not a coder, but I have some coding, modeling, and animation experience) I could help out with this (joint?) mod as well. I would find it a fantastic experience working with modders like you! (I've tried to make my own mods, but I always have so many ideas I don't know what to do with them, and I often get impatient with the code XD) -  I can modeling/skin work, to save you some time, and would also love to help with developing the quest system, if you decide to work with Simeon.

Anyway, this message is FAR too long. I really hope you are interested, and actually read my post :P. I know you're probably really busy XD I also know this isn't really the place to put this comment, but I don't really know where else to reach you best.

Please contact me if you are interested in my help! (A reply will do)
Thank you for your time, Cr0s!

P.S. I am also a Trekkie, Whovian, Star Wars fan, LotR fan, and much much more. Sci-fi/fantasy is my thing, and I actually intend to start a film company at some point (hopefully soon - working on a script write now!), making Scifi/fantasy films.

**Comment by LemADEC** [comment]
1. Not working is a bit vague to me. Please provide symptoms, logs or mods versions.
2. Thank you.
3. I know about Matter Overdrive, I've already had to fix incompatibilities with them. We had discussion about a merge but it wasn't conclusive. Also, WarpDrive is intended for balanced PvP, while MO is more inclined to OP single player survival.
4. Help is always more than welcome. As for modeling, the camera and laser blocks comes to mind, regarding textures, we could use particles effects and such, a decent armor(s), etc. You may reach me on the community TeamSpeak at ts.funsquaregames.com

**Comment by CaptainMegavolt** [comment]
If I might pop in on this thread, I'd like to put in my potential help for
modeling and texturing as well. I am reasonably experienced with Techne,
but due to how buggy it is, I would greatly appreciate any suggestions for
any other MInecraft modeling programs. I'm good with Mr. Crayfish's model
creator, but that only makes .JSON models for 1.8.

_--Supernova Industries Supreme Chairman Megavolt_

**Comment by TheNumenorean** [comment]
@Beadsmith2 As for you point number 3, I already tried, LemADEC is fairly opposed to this unfortunately.

Edit: Also, Cr0s  doesn't work on this anymore...

**Comment by LemADEC** [comment]
@SupernovaCo target is 1.8.

**Comment by TheNumenorean** [comment]
Target is 1.8?

**Comment by CaptainMegavolt** [comment]
Yes, i'd like to know what you mean by target is 1.8. Do you mean that you
plan to add 3D models for components in the 1.8 release?

**Comment by LemADEC** [comment]
We need to add 3 models, starting with Camera and Laser. Since there's so much changes in rendering between 1.7 and 1.8, and we need to move to 1.8 within a couple months, we better go straight with 1.8 models.

**Comment by CaptainMegavolt** [comment]
Gotcha. What sort of models were you thinking of?

_--Supernova Industries Supreme Chairman Megavolt_

**Comment by CaptainMegavolt** [comment]
I just remembered, I have been collaborating with another modder (known on the Minecraft Forums as Thebest108, i believe) on an airship mod with very good moving block grid and flight mechanics. Perhaps you could work with him on the FlyBy update.

**Comment by TheNumenorean** [comment]
I would like to protest that we "need" to go to 1.8. Most mods are still being developed for 1.7, and 1.9 is going to be coming out soon. Updating to 1.8 would be a waste of time, we should just wait for the next big update and focus on getting some of the features we have considered programmed.

(I realize this may sound absurd considering im still too busy to do much of anything, but I plan to help again in a few months).

**Comment by LemADEC** [comment]
@TheNumenorean  you're mixing Forge and Vanilla here.
Forge 1.8.9 is about to be released, it's built upon Vanilla 1.8 that was first released in Septembre 2014, that's 18 months ago.
Vanilla 1.9 isn't official yet, so Forge 1.9 would be usable 2017...

@SupernovaCo we've been messing around with a modified version of ArchimedesShips but it's a bit crude and very buggy. You have any good contacts with him/her?

**Comment by TheNumenorean** [comment]
The question is, wouldn't it be better to get the mod out of beta before doing another complete overhaul? 1.7 is the most popular platform, and will probably be for a long while.

**Comment by LemADEC** [comment]
many mods already have beta for 1.8, they're merely pending the official 1.8.9

**Comment by TheNumenorean** [comment]
My other point stands.

Is it that you want to update your modpack?

**Comment by LemADEC** [comment]
my modpack can't move to 1.8 yet, other mods aren't ready, but if we wait for everyone to be 1.8 to start updating, we'll be too late.

**Comment by LemADEC** [comment]
and yes, we can still work on the mod with stuff not impacting 1.7 vs 1.8. But adding something that's changed in 1.8 should be planned for 1.8, so we don't do it twice.

**Comment by TheNumenorean** [comment]
Too late for what?

And another update means that development for 1.7 will basically stop, and the mod isn't finished yet.

**Comment by LemADEC** [comment]
Too late versus other options for players.
Yes, development will be stalled on 1.7.

**Comment by TheNumenorean** [comment]
What other options?

**Comment by LemADEC** [comment]
Neither my server nor my modpack are alone out there.

**Comment by LemADEC** [comment]
Original questions have been answered. Open a new ticket if you feel further discussion is needed.
