### ISSUE TITLE
computer craft program not loading

### ISSUE THREAD

**Issue by brenden1010** [LemADEC/WarpDrive#127]
after putting in my ship name it dose not load

**Comment by LemADEC** [comment]
what does it say exactly?
Have you put a ship core next to your ship controller, horizontally?

**Comment by glixyl** [comment]
I just verified that the Advanced Computer from CC is loading just fine after putting in my ship name.  Latest code version 1.3.17

**Comment by LemADEC** [comment]
Not enough information to investigate further, open a new issue once you've the details
