### ISSUE TITLE
MovingWorld support for 1.8.9 port

### ISSUE THREAD

**Issue by MoonlightSystem** [LemADEC/WarpDrive#128]
the creator of movingworld and archemedesshipsplus  is making a redux of movingworld which will be in a way like metaworlds
i was wondering if you could use this for making working spaceships that actually move

**Comment by LemADEC** [comment]
Thanks for your suggestion.
We are indeed monitoring dark progresses with Moving World and AS++. As of now, the code is still a bit too unstable to use it for us. Also it doesn't completely cover our existing features, so a rewrite would be required either way.
Obviously, we'll continue monitoring his progress, things can progress fast sometimes :)
