### ISSUE TITLE
Radar wiki page vague

### ISSUE THREAD

**Issue by FirstArchon** [LemADEC/WarpDrive#129]
the radar wiki mentions the ability to increase the range of the radar but doesn't mention how to do so and it doesn't seem to be just right clicking on it with a range upgrade. 
"As you increase scan radius, scan duration will take longer, and energy requirement will increase exponentially."-wiki page on radar

it also shows a radar being output to a cc monitor but doesn't explain how.
ie wrap the monitor and then run the scan program in the monitor

**Comment by LemADEC** [comment]
You increase through the radius property in the LUA API.
With the preloaded 'ping' script, you can pass the range has an argument.
With the preloaded 'scan' script, you need to copy it and change the first line.

Range upgrades have no use in the mod, hence they have no recipe.

The screenshot was done with OpenComputers, which works a bit differently than ComputerCraft and won't require warping the monitor.

**Comment by FirstArchon** [comment]
what is the usage of the ping script? ping(5000)?

**Comment by LemADEC** [comment]
it's a standard command line program, just add parameters separated by space, like so:

```
ping 5000
```

**Comment by LemADEC** [comment]
No update, assuming solved
