### ISSUE TITLE
Move mods dependency to configuration file

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#13]
- [x] Blocks blacklist: those are forbidden inside and ignored next to the ship (currently, it's Bedrock, Artifacts invisible bedrock)
- [x] Blocks white-list: those doesn't count in ship volume (currently, any 'air' block)
- [x] Blocks expandable: those can be destroyed by the ship when arriving at destination (should it be the same as the white-list?)
- [x] Blocks late placement: those should be placed after the basic blocks to avoid crashes and baddies (IC2 reactor anyone?)
- [x] Asteroids type: this a weighted list of possible asteroid type (Overworld, Nether, End, etc.)
- [x] Asteroids filler blocks: for a given asteroid type, this is a list of possible core blocks with their corrupted(cobblestone) variant
- [x] Asteroids ore blocks: for a given asteroid type, this is a weighted list of possible ore blocks. Bedrock should be always in there by default.
- [x] Asteroids gases blocks: for a given asteroid type, this is a weighted list of possible gases/atmosphere blocks. Air means no atmosphere.
- [x] General behavior: if a mod is not loaded, its blocks are ignored and configuration file remains unchanged. If a mod is loaded and one of its block is missing, a warning should be logged in console.
- [ ] Space debris loots: this is a weighted list of possible itemStacks to find in space debris loot chests, including min/max quantity
- [x] Recipes: this a set of recipes to use instead of default. Eventually propose a sample scripts for MineTweaker?

**Comment by LemADEC** [comment]
Updated with WorldGeneration, loots and recipes

**Comment by TheNumenorean** [comment]
I have an idea for this, will post once it is fleshed out.

**Comment by LemADEC** [comment]
Fixed in baede105460c5076734a25dda5e03a06c58fb58e
