### ISSUE TITLE
[Query] : Dimensions?

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#130]
Hi There,

Lets say I have 20 dimensions I wish to connect via the space dimension.
- How are they shown in-game? I cant seem to understand the configs. Are the lists using world name or dimension id? (i.e Overworld = Dim 0, but I have a world called Earth which is Dim 4)
- Are we able to drop the amount of 'clutter' - i.e asteroids another other ships in the space dimension?
- Is there a way I can separate planets by a greater distance using the space dimension?
- Is there any way I can use the Galacticraft atmosphere system in space?

Sorry to dump you with all these questions, I'm trying to set up a Stargate Themed server and interstellar + intergalactic craftable ships is really appealing as an alternative to the gate network (we have 50+ playable worlds)

Regards,
@draksterau

**Comment by LemADEC** [comment]
The configuration uses the dimension ID as numbers.

You can remove all asteroids and moons definition to have an empty space, or just add some empty ones made of a single leaf to reduce the number of normal ones.
We'll add a proper configuration for it later on.

You can put planets space coordinates wherever you want provided:
1- it's withing the Space world border so you can actually reach it.
2- you stay within ±100k on X and z axis. After that, most mods will have weird behaviors and will eventually crash, vanilla included.

Galacticraft oxygen is unusable on servers due to its current design, we'll eventually disable it so only WD oxygen works on GC planets.

**Comment by StargateMC** [comment]
Thanks for the response! :)
Ill do the empty space scenario - that works wonders :)
I'll do some testing now with regards to planet coordinates... I am having trouble doing it in single player though! :( It doesn't appear to be viewable from space? Is that by design?
With regards to GC Oxygen, is there any reason its not usable? It works fine from what Ive been able to see?

**Comment by LemADEC** [comment]
GC oxygen is a major source of TPS lag, you don't want it on your server unless you re-implement it.

Planet won't show in space. Cr0s is working on it. I had a prototype showing them on a radar.

**Comment by StargateMC** [comment]
@LemADEC believe it or not rad fast is on it ! :)
Noted though. No problems.
Is there a way to force all blocks on a ship to be connected? Not just a radius?

**Comment by LemADEC** [comment]
rad fast ?

What do you mean force all blocks to be connected?

**Comment by StargateMC** [comment]
At the moment the ship can be 50 blocks in the air, and if I create a radius of 60, it will include blocks that are part of the ground if I warp upwards.

I meant radfast, from Galacticraft :)

**Comment by StargateMC** [comment]
@LemADEC 

What do you mean moon definition? I cant find it anywhere..... :(

**Comment by StargateMC** [comment]
Another question... please don't hate me.... if a player is connected to the ship and summoned.. does this only work within the same dimension?

Can we possibly set a radius to the ship of say 500...and only in the same dimension?

**Comment by LemADEC** [comment]
Players are teleported through dimensions, for the same cost.

A ship radius of 500 blocks is possible but it'll require to load completely the ship during the move, which is a lot of stress for the server.
I don't understand your point on the "same dimension" here?

**Comment by StargateMC** [comment]
I'm trying to ask is it possible to restrict "summoning of players" to a distance of 500 and for same dimension?

I don't want players being able to be summoned from one planet to another if the ship is on a different planet..

**Comment by LemADEC** [comment]
That should be fairly easy to add

**Comment by StargateMC** [comment]
Sorry for my bad explaining!!! XD @LemADEC
