### ISSUE TITLE
Ships griefing through overlap

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#131]
At the moment, a ship can quite literally be made up of blocks that are not connected.

This means  that a warp core can grief peoples bases by being activated and expanding its radius into their base....

I'd recommend a config that requires blocks be connected.... perhaps if you require the Warp Core be directly connected to the ships hull which must be enclosed and anything within the hull is transported even if it is floating?

**Comment by StargateMC** [comment]
![example](https://cloud.githubusercontent.com/assets/9921203/13377547/e9da8b02-de33-11e5-9026-0074f08f0587.png)

**Comment by LemADEC** [comment]
You are proposing to have a blocks connection constrains on ships.
This will not prevent griefing.
This will prevent building ships with floating blocks inside the ship.
This feature is planned in the future but doesn't address the issue at hand.

On the other end, ship cores can't overlap each others, hence you can't use your ship to grief another one.

**Comment by StargateMC** [comment]
But what if I have a base on land @LemADEC ? If the ship core expands over it, it can be sucked out of the world.

**Comment by LemADEC** [comment]
Your base is typically:
1- on a planet, hence ship size is limited to a few thousands block, so you would need to precisely pinpoint that base location.
2- in space, your base is a ship, hence protected by overlapping cores rule
3- in space, your base is hidden inside a moon, hence protected by the bedrock randomly spawning in there

**Comment by StargateMC** [comment]
@LemADEC The point is it _can_ grief... :(

My player base is umm how do I put this... open to using any means necessary to destroy their enemies.

**Comment by LemADEC** [comment]
A ship cannot cut next to a tile entity. Typically, you can't stop your ship border next to a chest or a contraption like cables, machines, etc. So, you really need to be precise to cut open a base.
If you want to prevent it, add obsidian to the anchor list and tells that base should be walled in it, most players already do that anyway.

As for griefing with a ship, it'll remain a valid strategy. The same way you can ram a ship into another through jumping.

**Comment by StargateMC** [comment]
AH!
Sorry I completely glazed over the anchor section.
So I just pick an item to act as a ship-repellent and we're good to go. :D gotcha!

**Comment by StargateMC** [comment]
@LemADEC one last question, is there any requirement for the name of the int list associated with dimensions?

**Comment by StargateMC** [comment]
@LemADEC I think I know how to solve this problem - Automatically treat anything that is "Soil" as an "Anchor" too?

**Comment by LemADEC** [comment]
Currently, the planet name is only used for logs at boot. It'll be used in starmap entries later on.
Soil are part of your ship biodome, that won't work as an anchor. Try stone instead :).

**Comment by StargateMC** [comment]
@LemADEC Genius!!
