### ISSUE TITLE
Add configuration for player teleportation

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#132]
As per #130 and roadmap:
- [x] restrict teleportation range
- [ ] adjust cost vs distance and dimension

**Comment by StargateMC** [comment]
If possible, please add a disable-cross dimension transfer regardless config option

**Comment by LemADEC** [comment]
range includes cross-dimension

**Comment by StargateMC** [comment]
Sweet :)

**Comment by LemADEC** [comment]
Transporter setup replaced the need for this, hence closing.
