### ISSUE TITLE
DraksterAU is learning WarpDrive :)

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#133]
As above.... I can successfully enter the atmosphere, but the ship gets half-destroyed in the process.
This could happen by accident... and a player would destroy a massive build in the process.

Should prevent entering the atmosphere by accident with a message like this one and not do anything:

_This ship is too big to land on a planet_

**Comment by StargateMC** [comment]
Actually this is happening all the time, regardless of ship size...... is there something I need to do?

**Comment by StargateMC** [comment]
@robotia This is happening on thermos only... any configs I need to be aware of?

**Comment by LemADEC** [comment]
Please enable all logs and post them while reproducing the issue.
Also, please add screenshots and blocks count before and after the jump so we can narrow down the issue.

**Comment by StargateMC** [comment]
@LemADEC This happens when leaving the planet too.
I haven't tried Hyperspace yet, trying that in a few mins.

I do notice that I see the worldborder (bukkit plugin) being triggered during jump, as if I've hit it .. even though I am almost at spawn and the world border is at least 2500 blocks away.

Enabling logs now.

**Comment by StargateMC** [comment]
@LemADEC I don't get any errors.

BUT... I have found this is only when I sit the computer in the front of my ship...
i.e  15 blocks in front, 45 behind computer the front half is transported. Its like the forward value is treated as the radius on that axis and not both?

**Comment by StargateMC** [comment]
@LemADEC So Ive tested this thoroughly.

If I put the computer in the bridge of my ship 15 blocks from the front of my ship, with "back" set to 45 blocks... it should get the whole ship but it doesn't.

**Comment by LemADEC** [comment]
The ship core is the center of the coordinates systems and count as 0 on all axis.
I'm unable to reproduce the issue with Thermos, KCauldron or Forge. You're probably using invalid ship dimensions.

**Comment by StargateMC** [comment]
Exact dimensions are:

FRONT: 15 blocks
BACK: 45 blocks
LEFT: 25 blocks
RIGHT: 25 blocks
UP: 20 blocks
DOWN: 20 blocks

Its as if FRONT = 15 causes BACK = 15....

These are not working?

**Comment by LemADEC** [comment]
It depends on your ship :).

**Comment by StargateMC** [comment]
Explain?! o.O what do u mean depends on ship?

**Comment by LemADEC** [comment]
The dimensions you're entering are defining the bounding box for your ship.
So depending on the ship sizes and the Ship core position inside it, the dimensions to enter will differ.

**Comment by StargateMC** [comment]
I have placed my core 15 blocks from the front of my ship. 45 blocks from the rear. It is 40 wide, so 20 for LEFT and RIGHT.... and it is  40 high.

Is this not right? :(

**Comment by LemADEC** [comment]
Assuming your ship core is centered vertically, it should work

**Comment by StargateMC** [comment]
If I reverse this, and select 45 FRONT and 15 BACK and sit the core in the REAR of the ship, it cuts off the front.

You sure this isn't a bug?

**Comment by LemADEC** [comment]
I'm pretty sure you are confusing the controller and the core.
Core is the center, controller is the front.

**Comment by StargateMC** [comment]
Oh, they don't need to be joined..... WOW.

**Comment by StargateMC** [comment]
one last thing then, how do I delete reference to a destroyed jumpgate? I cant create another with same name.

**Comment by LemADEC** [comment]
Yes, they DO need to be joined.
To delete a jumpgate, you need to shutdown the server and modify the jumpgate list in the world folder.

**Comment by StargateMC** [comment]
If they need to be joined, then how can you not have to put the controller dead centre in the middle of your ship (away from your fancy ship-bridge build)? =P
No worries will do thanks xD

**Comment by LemADEC** [comment]
there's no reason to put your ship core in the dead center of your ship.

**Comment by StargateMC** [comment]
If you don't then bits will be cut off... My whole point for this issue haha

**Comment by LemADEC** [comment]
The controller allows you to set a different size for each direction from the core, why do you absolutely want the same size on both directions of each axis?

**Comment by StargateMC** [comment]
I don't. I'm saying if you set them to different the smaller one is used for the larger one.

Ie 15 front and 45 back is being treated like 15 front 15 back by the mod.

**Comment by LemADEC** [comment]
That's incorrect.
Try with the default ship with /generate ship
Then enter the ship dimensions as Front 12, Left/Right/back/up 6, and Down 2.
Then jump.

**Comment by StargateMC** [comment]
Try that, but with a larger ship. It works with the small one for me too.

**Comment by StargateMC** [comment]
Will send through pics later

**Comment by LemADEC** [comment]
No updates for 18 days, assuming fixed
