### ISSUE TITLE
Problem with camera video channel set

### ISSUE THREAD

**Issue by cooperg2001** [LemADEC/WarpDrive#143]
It appears that the command shown on the wiki for setting video channel in cameras does not work.
The command shown is `laserCamera.videoChannel(7089)`  however i only got it to work by typing `laserCamera.videoChannel (7089)` . As you can see there is only a space that made the difference, but the command for setting monitor channel did not require the same change.

**Comment by LemADEC** [comment]
There's no reason for a space to be interpreted by the LUA interpreter. There's probably a mixup somewhere in your testing.

**Comment by cooperg2001** [comment]
Roger that. I'll redo my tests

**Comment by LemADEC** [comment]
:)
