### ISSUE TITLE
SMP Controller script crash after jump

### ISSUE THREAD

**Issue by sexyasianboy** [LemADEC/WarpDrive#146]
while the OC-script-shipcontroller is running normally in singleplayer, there may be one issue in multiplayer mode. Whenever i jump (up, down, front, back, etc.), after the jump the script is crashing and i have to reload it.

"TheCrashReport" (i called the file autorun.lua)

```
/autorun.lua:139: attempt to perform arithmetic on local 'sizeX' ( a nil value)
stack traceback:
/autorun.lua:139: in function 'ShowWarning'
/autorun.lua:843: in main chunk
(...tail calls...)
```

I dont know how to fix that, because im a noob. It isnt a big problem, but i would like to run the script permanently instead of restarting it after every jump.

**Comment by sexyasianboy** [comment]
btw its the opencomputerscript from your page, i found: 
[https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/resources/assets/warpdrive/lua.OpenComputers/warpdriveShipController/startup.lua](url)

**Comment by LemADEC** [comment]
The script is preloaded in the filesystem, check the mount name with "df".
Where's your computer screen located relative to the case? How big is your ship? Can you post a picture of it?
