### ISSUE TITLE
Unable to load TileEntityAbstractEnergy with 1.7.10-1.3.18

### ISSUE THREAD

**Issue by crunkazcanbe** [LemADEC/WarpDrive#147]
http://pastebin.com/mi6DXBMU I added the latest version to my home made mod pack ,and it crashes on start up :/

**Comment by LemADEC** [comment]
Looks like IC2 API was improperly distributed by another mod. Please post your fml-client-latest logs from the logs folder so we get more details on the issue.
You'll have to remove mods to find which one is messing around.

**Comment by LemADEC** [comment]
Any update on this one?

**Comment by LemADEC** [comment]
No update, assuming fixed
