### ISSUE TITLE
With EnderIO, Air Generator is not buildable - wrong EnderIO Reservior used in recipe.

### ISSUE THREAD

**Issue by WazWaz** [LemADEC/WarpDrive#148]
With EnderIO (1.7.10-2.2.8.381) installed, the Air Generator recipe requires an EnderIO Reservior (215:5), but this is the block that appears when you put 2x2 Reservior (215) blocks on the ground - it cannot be crafted, and therefore the Air Generator cannot be crafted.

Worked around by temporarily enabling vanilla recipes in warpdrive cfg.

**Comment by LemADEC** [comment]
Thanks for you report, this was fixed in f3bb09a8f63df411a34837bebc9f723dd58e46dc
