### ISSUE TITLE
Radar recipe with EnderIO requires 14 Ender pearls - correct?

### ISSUE THREAD

**Issue by WazWaz** [LemADEC/WarpDrive#149]
Seems excessive, as if the Vibrant Alloy Block should be a machine chassis.
(especially since Radar doesn't do much yet)

**Comment by LemADEC** [comment]
Radar can detects ships 10k blocks away, provided you give enough energy. What alternate recipe would you propose?

**Comment by WazWaz** [comment]
Ah, I understand. We've only played with a single ship so far, so I guess it wasn't obvious how useful it was in large-scale games.
