### ISSUE TITLE
Dublication of Immersive Engineering cables.

### ISSUE THREAD

**Issue by ZMikkie** [LemADEC/WarpDrive#150]
Tested with warp drive compiled after commit ab8a485f39e43c4caa98ff646fda1001ecab4ff8 and Immersive Engineering 0.7.4 in multiplayer.
![java_2016-04-04_22-21-21](https://cloud.githubusercontent.com/assets/18270661/14260723/8fbd41ac-fab5-11e5-8ede-0518bc0af25c.jpg)
Warping while having cables onboard have 2 issues.
1. Minor, cables become invisible but still work.
![java_2016-04-04_22-22-29](https://cloud.githubusercontent.com/assets/18270661/14260827/094fdebc-fab6-11e5-8418-7147a8588bd3.jpg)
2. Major. Each jump doubles the amount of cable between 2 connectors. So, first jump gives 2 caples per connection, second jump gives 4 cables and so on. And (issue no.1) they are invisible. If player relogs, they are visible again, and when thery are visible they cause massive fps drop cos of thier quantity. I've spent 4 minutes trying to break 10 connections having around 1 fps.
Result of breaking 1 HV connection after 4 jumps:
![2016-04-04_22-43-12](https://cloud.githubusercontent.com/assets/18270661/14260911/a6266ddc-fab6-11e5-85f7-1202984c2959.png)

**Comment by LemADEC** [comment]
It's a bug in IE itself, I've added a workaround for it in a83a0a59a67ce1d3d8b86b86bd54c868b3b1e30f
