### ISSUE TITLE
Client crash when rendering Jump entity

### ISSUE THREAD

**Issue by axelpx** [LemADEC/WarpDrive#151]
Whenever any player on my server warp jump - their client crash with the provided crashlog:
http://pastebin.com/E64ZgYvf

Warp Drive mod version: 
WarpDrive 1.3.18 Beta for 1.7.10

**Comment by LemADEC** [comment]
One of your mods is corrupting the renderer. You'll have to remove mods until you find which one is derping.
Start with Optifine and CustomNPC.

**Comment by LemADEC** [comment]
This is not a WarpDrive bug.
