### ISSUE TITLE
Air generator modifications

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#153]
Air generators do not expand more than two blocks away in a large open space.

There should be a config change for the 15 block limit. Personally I find 15 to be annoyingly limiting for any kind of large ship.

**Comment by LemADEC** [comment]
They are already expanding more than 8 blocks away, you're doing something wrong.

**Comment by LemADEC** [comment]
and yes they periodically fall back to a few blocks as part of their animation, but technically they still covers you since you don't suffocate instantly when out of air.

**Comment by TheNumenorean** [comment]
Ok, the configuration option does not appear to exist, that is a feature request.

I also would not post unless I had literally just tested it and it did not work. I will post a video later, and you can tell me whether I am using it wrong. It was oscillating between approximately 4 and 3 blocks radius, which is wrong.

**Comment by LemADEC** [comment]
You need to maximize the available sides to increase the coverage and build pressure on a nearby surface.
If you put it on the ground with a power source on top, you'll have less effect than putting it 2 blocks above ground with only bottom side obstructed with a power source.

For the record, you can currently fill a 15x15x5 room with only 2 air generators in the middle of 2 opposing sides, a few blocks away from walls.

**Comment by LemADEC** [comment]
15 is the limit in vanilla for block's metadata. Pushing further requires either to:
1- use a secondary block to (almost) double the range. This an heavy impact on the existing computation code. We could consider it a tier2 air generator of sort.
2- use tile entities and cause massive direct and indirect lag in the area.
3- use a cached map of the air volume and loose the existing animation effect when air leaks.

Option 3 requires a valid oxygen source (not just power like the current approach). This could be implemented once we have Fly-by and Shield implemented since those use similar code but will get more benefits from it.

**Comment by TheNumenorean** [comment]
Ok, that makes sense, and is more complicated than I had hoped. It is still a worthwhile feature if we can eventually add it, so I will create a new issue for it.

The side pressure explains it, that should be explained on the wiki though. Also maybe worth a conf option? It looks a lot more elegant to have it flush with the deck or bulkheads.

**Comment by LemADEC** [comment]
What configuration do you have in mind?

**Comment by TheNumenorean** [comment]
How hard would it be to allow a single side to exert full pressure, so that an sir generator open only on one side in the ceiling of other surface of a ship can still fill the full 15 blocks with air? Being able to embed air generators in the floor would be very nice, as it is more aesthetically pleasing. Also, having multiple sides matter doesn't make much sense from a physics point of view.

**Comment by LemADEC** [comment]
This implies loosing about 2 blocks range on the air generator, which will be even worse than current air generator slightly shift from walls/ceiling.
Also, it's realistic to distribute air in multiple points from physics point of view. It's not practical to have it away from the wall/ceiling.
If we wanna go realism, there's way more to consider like actual air recycling and circulation, temperature and humidity, etc.

**Comment by LemADEC** [comment]
I made an explicit ticket for the feature request. Closing this one for clarity of the issue tracker

**Comment by Zensoji** [comment]
I'm confused. In my creative inventory there is no Air generator (using latest beta build).
Also Galacticraft has it's own air distribution and generation system - does this conflict with that?

**Comment by LemADEC** [comment]
Both air systems work on their own. So you would need WarpDrive air in WarpDrive dimensions, and GC air in GC dimensions.
The air generator is there for me in the creative tab (1st line, 5th row).

**Comment by Zensoji** [comment]
Found it. Although it was 5th Column 8th Row.
