### ISSUE TITLE
Air generator microblock issue

### ISSUE THREAD

**Issue by CaptainMegavolt** [LemADEC/WarpDrive#158]
Air generators destroy adjacent Forge Microblocks when active:

Before:
![2016-04-21_09 54 47](https://cloud.githubusercontent.com/assets/11221935/14713600/58bd6c78-07a7-11e6-8e51-7407b3d0362e.png)
After:
![2016-04-21_09 54 48](https://cloud.githubusercontent.com/assets/11221935/14713601/58cd1dbc-07a7-11e6-9fd2-a38777cb2759.png)

**Comment by CaptainMegavolt** [comment]
The same problem occurs with Mekansim Universal Cables

**Comment by LemADEC** [comment]
so the first block is placed but the propagation won't ?

**Comment by CaptainMegavolt** [comment]
If you mean that the first block placed by the air generator removes the
microblocks, but not the propagating air blocks, then yes, that is correct.

_--Marvin_Megavolt_

**Comment by TheNumenorean** [comment]
Can confirm, ive noticed this bug too. I believe I know where the bug is

**Comment by TheNumenorean** [comment]
I think it is an issue with line 63 of AirGeneratorTileEntity. My dev environment got messed up, so I cant check, but I suspect that block.isir() doesnt work like suspected.

**Comment by TheNumenorean** [comment]
Possible fix commited, should be checked

**Comment by LemADEC** [comment]
ouch, that's gonna hurt

**Comment by LemADEC** [comment]
ok, that fix will cause more issues than solve, I'll revert it and push my local changes.

**Comment by TheNumenorean** [comment]
Fine by me. The issue as far as I can tell is just that it is looking to the offset twice.

**Comment by LemADEC** [comment]
The original issue is that microblocks don't implement the Forge isAir check properly. So you are at the right place for the fix. However, Vanilla air isn't the only air out there, including WarpDrive air itself.

**Comment by LemADEC** [comment]
Immibis Microblocks works properly for the record.
Issue is confirmed with latest ForgeMultiPart 1.7.10-1.2.0.347.

**Comment by LemADEC** [comment]
Ok, turns out the bug was on our side and causing some invalid chunkloading in some edge cases.
FMP does a more complicated air check, hence triggers the error.
I didn't test mechanism but it should certainly be better now.

@TheNumenorean you've some free time to work on the mod again?
