### ISSUE TITLE
Feature Request: GC oxygen compatibility 

### ISSUE THREAD

**Issue by ICY105** [LemADEC/WarpDrive#161]
I see a lot of 'issues' about the oxygen system not being very good. I think a great way to fix this would be to have compatibility with Galacticraft's oxygen system. It's a lot more flushed out, and overall more powerful. This would solve a lot of people's complaints about the oxygen system.

I'm not too familiar with modding, but if you can read the player's nbt data then there is an 'oxygen setup valid' tag added by GC you could hook into. Making oxygen tanks deplete would be a bit more difficult though.

**Comment by LemADEC** [comment]
The existing oxygen works actually better than GC in terms of server CPU usage, visual effect and player functionality.
What we are missing is a second tier oxygen generator and torch 'extinction'.

On the other end, GC is over expensive, over complicated, and kill the server CPU with oxygen piping, oxygen collection, oxygen bubbles and oxygen sealer. Fair enough, it gives more things to do for players playing alone.
WarpDrive is intended to play on server, no in single player.

As for supporting the oxygen breathing from GC, it's already in the roadmap, there's already a ticket for it, so I'll close that one.

Thank for you suggestion.
