### ISSUE TITLE
Rotation support for more mods

### ISSUE THREAD

**Issue by CaptainMegavolt** [LemADEC/WarpDrive#163]
Certain modded orientable blocks, such as Carpenter's Blocks and Matter Overdrive holographic signs will not rotate with a ship when it rotates as part of a jump.

**Comment by Zensoji** [comment]
Glad I read this. Using (I asssume) the same modpack (FTB Horizons: Dawnbreaker) and hadn't tested the warp system yet as I was setting up the rest of my bridge. I take it flying normally (forward/reverse/left/right) is fine though? Basically as long as I don't rotate everything should be fine?

**Comment by LemADEC** [comment]
Rotating with Carpenters won't corrupt your world per say. It's just won't align properly until you realign your ship.
If you want to have support for rotating new blocs, you'll have to provide a reference map showing all the rotation of the blocks as explained on the forum.

**Comment by Maxstripe** [comment]
mekanism also will not rotate with ship

**Comment by LemADEC** [comment]
For those interested to help add more rotation support, please provide a map as follow:

Create a map with all possible rotations for blocks of the mod in question.
The map name should be the mod name with its version.
The requirement is for each block that rotates:
- place a central stone block in a 3x3x3 area,
- place each possible rotation of the block on the related side of that stone block,
- leave 1 or 2 blocks of spacing between each areas of 3x3x3,
- organize those areas horizontally in a matrix (don't make a big straight line, don't stack them vertically),
- for activated blocks like doors, remember to make an area for the 'open' doors and another area for the 'closed' ones.

Upload that map on dropbox or something equivalent.

**Comment by LemADEC** [comment]
Carpenter's blocks are supported. Please refer to #192 for new mods
