### ISSUE TITLE
Remove reliance on 'computer' mods

### ISSUE THREAD

**Issue by SkylordJoel** [LemADEC/WarpDrive#164]
The blocks that currently use a computer for interface should have a GUI instead.
It can be useful for people designing modpacks where computers would be considered OP, for example.

**Comment by LemADEC** [comment]
Why would we consider a computer being OP?
Turtle and nanobots can be disabled easily.

**Comment by BenFRC5147** [comment]
Plus I perfer having the option to create my own jump software if I so desire ;p

**Comment by LemADEC** [comment]
No answer from original poster, not planned, closing until further information are provided
