### ISSUE TITLE
WDCore error on server startup

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#165]
This error is occuring at startup for me:

[15:08:12] [Server thread/INFO] [WarpDriveCore]: Injection failed for net/minecr
aft/world/chunk/Chunk (0 / 1), aborting...

Is this concerning? I cant figure out where it stems from.

**Comment by LemADEC** [comment]
I need the full log to understand that bug and the full list of mods involved

**Comment by LemADEC** [comment]
if possible, recompile with setting debugLog to true here: https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/core/ClassTransformer.java#L25 . This will spam the logs but will help to understand what's going on.
For the record, this error impacts the cloaking system.

**Comment by LemADEC** [comment]
Any update on this one?

**Comment by LemADEC** [comment]
Not update, not enough data to investigate, closing until we can reproduce with full logs
