### ISSUE TITLE
warpupdater scripts regression with 1.3.21 (rotation update)

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#166]
As reported here http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2510855-1-6-4-1-7-10-warpdrive-build-your-ship-freely?comment=913 , the warpupdater and related pastern are no longer working following the API changes for rotation support.

@YuRaNnNzZZ please check it up :)

**Comment by DraksterAU** [comment]
@LemADEC I got another issue relating to computers...

When I booted up a spawned ship using the /generate command, it does not come up with the menu (after selection of ship name) with dimensions etc, until I press the 1 key.
Nothing is displayed on the screen to explain this... I was just lucky enough to mash keyboard buttons til I found out the magic button! :)

**Comment by YuRaNnNzZZ** [comment]
I'll look into it.

**Comment by LemADEC** [comment]
Fixed in 752748f4ed09b87cb0b3c5388eaef624ffa43eb8
