### ISSUE TITLE
CC computer ID used by default in ship name

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#169]
When I try to name my ship, as soon as I press any button (i.e type test)... when I press the first button, the characters populate with '163t'... or '164t' for some reason.

**Comment by LemADEC** [comment]
Known minor issue.

**Comment by LemADEC** [comment]
Actually, it's intended. The bug is that OC doesn't do it.

**Comment by Maxstripe** [comment]
OC defaults to the comp adress until you change it

**Comment by StargateMC** [comment]
Annoying thing really. But all good if it's working as intended.
