### ISSUE TITLE
Beta .21: Computer on bootup will not have anything on the screen

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#170]
@LemADEC Ive got another issue relating to computers...

When I booted up a spawned ship using the /generate command, it does not come up with the menu (after selection of ship name) with dimensions etc, until I press the 1 key.
 Nothing is displayed on the screen to explain this... I was just lucky enough to mash keyboard buttons til I found out the magic button! :)
![test 2](https://cloud.githubusercontent.com/assets/9921203/15096557/c25c1858-1541-11e6-931f-1d76c7cb0c16.png)

**Comment by LemADEC** [comment]
It's the same menu presentation as the old script, nothing new here. You just have to read the actual menu.
