### ISSUE TITLE
Start scripts with an help page

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#173]
Hi There,
Several players on my server are doing some testing with our pack on singleplayer.
More than half of them are confused by the main menu (0, 1, X as options) - including myself before.

Can you please add some text to the main screen that says "Ship main menu, select from one of the options below" - or something similar, so that it is a bit more obvious to people new to WD?

Just a usability thing... not a high priority.

Regards,
DraksterAU

**Comment by LemADEC** [comment]
Already fixed
