### ISSUE TITLE
Idea: Config setting to enable space in multiple dimensions

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#175]
We are currently setting up several space based spawn builds - they're canon builds from the SG universe.

What we'd like to do Is enable the space dimension functionality in multiple dimensions, if this is possible? 
It would allow these builds to exist separate to space in the event of any issues, and the dimensions themselves are places players cannot build.

These dimensions would have the oxygen, gravity and generation of space, without the cross dimension travel support - it would be treated as a 'world' not 'space' when it comes to that.

I've already tried (and failed) to implement this, as for some reason the vacuum just doesn't work... generation, air generators and gravity do.

Would give realism to the spacecraft we have built if they required the appropriate life support systems etc and were not just a void world.

Could it be as simple as changing the SPACE dimension ID config to an integer list and switching the code to do a list contains number instead?

**Comment by LemADEC** [comment]
That's already on the roadmap for 1.9

**Comment by StargateMC** [comment]
Damn, ill keep at it then =P

**Comment by LemADEC** [comment]
As explained, already on roadmap, hence closing

**Comment by StargateMC** [comment]
No worries
