### ISSUE TITLE
Aborted warp still damages ship

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#176]
Latest code: Warping into bedrock results in damage to ship, even though it says there is insufficient space to jump

**Comment by LemADEC** [comment]
If your ship doesn't move, there's only fake explosions happening.
If those explosions damages you, there's probably a plugin or mod messing around with explosions.

**Comment by StargateMC** [comment]
Still says there is a collision and there wasn't enough space to jump at the same time. So either the ship should warp and be damaged or it shouldn't warp... Not both though?

**Comment by LemADEC** [comment]
logs?
