### ISSUE TITLE
Cloaking Radius

### ISSUE THREAD

**Issue by LuckyLuke313** [LemADEC/WarpDrive#177]

**Comment by LuckyLuke313** [comment]
Dear Modder

i have a problem with the Cloaking Core from your Mod. I use ComputerCraft and the standard program. The problem is that the radius of the Field is always limited to 5 Blocks from the inner Cloaking Coils even if i place the outer Coils like 5 blocks away from the one in the inside it doesnt work.(By the way awesome sound :D) .

Thank you for your help
LuckyLuke313

**Comment by LemADEC** [comment]
Please post a screenshot of your setup to illustrate the issue.

**Comment by LuckyLuke313** [comment]
![2016-05-19_09 59 42](https://cloud.githubusercontent.com/assets/19412672/15386561/c4e5151a-1da8-11e6-8ce9-19ab985e33f8.png)
![2016-05-19_10 00 03](https://cloud.githubusercontent.com/assets/19412672/15386562/c4e867e2-1da8-11e6-94c7-caf174bbbb69.png)
You can see it is a Valid setup i used the T1 that you can see what is cloakend and what not the coil is in the front of the Ship, but it doesnt work. I hope the screenshots help you, thanks for your help

**Comment by CaptainMegavolt** [comment]
I've had something like this happen to me before. Lemme see if I can
recreate the problem. I'll be back with screenshots and more info soon.

**Comment by LemADEC** [comment]
Fixed in edda2eb8dc1a61beeb11623b0c898f210a3cd066
Axises were mixed up in the area definition
