### ISSUE TITLE
Problem with Radar and OC

### ISSUE THREAD

**Issue by Zensoji** [LemADEC/WarpDrive#179]
I'm having a little trouble with the Radar system, insofar that from reading the limited info in the wiki, it appears that it should operate similar to the weapons controller and the warpdrive controller and load a custom GUI for the radar system. However in practice my OC computer is just booting up as if it wasn't there, however it does recognize that the radar is there when I run the components command.

**Comment by LemADEC** [comment]
Type 'dir' or 'ls' to see the 2 available commands: ping and scan.
Major changes are planned for the radar, so wiki is fairly light for it for now.

**Comment by Zensoji** [comment]
I've just looked through the whole file system and there are no scan or ping programs.

Additionally the address of the radar isn't in the /mnt/ folder

**Comment by LemADEC** [comment]
When typing df , you should see the warpdriveRadar. In the negative, you've either your radar not connected to the computer chassis or the LUA scripts are disabled in your WarpDrive configuration.

**Comment by Zensoji** [comment]
found it. thanks.
