### ISSUE TITLE
Revisit ChunkLoader

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#18]
Should decide if actually neccessary

**Comment by LemADEC** [comment]
ChunkLoader is now a pure separate block

**Comment by TheNumenorean** [comment]
Still though, do we really need it? There are better alternatives out there. And the WarpCore has to be able to do it anyway on its own.

**Comment by LemADEC** [comment]
As long as it works, no reason to remove it. If it breaks, that another story.
Also, we won't look for a recipe for it.

**Comment by TheNumenorean** [comment]
Fair enough

**Comment by TheNumenorean** [comment]
Im marking this for taking a look at for version 2

**Comment by LemADEC** [comment]
Nobody to work on that, no point to keep it open
