### ISSUE TITLE
Deck Plating

### ISSUE THREAD

**Issue by Zensoji** [LemADEC/WarpDrive#180]
Had an idea about some new blocks. As you already have hull plating covered in tiered levels, could there also be deck plating? Similar to StarMiner's gravity core block mechanic it could exert a 2 block tall gravitational pull only on the top face, and emit air out of only the top face. Underneath it should be a deck plating controller with a simple GUI to set which face has the energy feed and which has the oxygen feed from the air generator. It should keep in theme with your mods tendency to be very demanding on energy :-)

**Comment by LemADEC** [comment]
Sounds very specific and unrelated to WarpDrive as it is currently. Not quite sure what you're trying to propose here.

**Comment by LemADEC** [comment]
Can you clarify what your proposing here?

**Comment by LemADEC** [comment]
No answers for 3+ weeks, closing for now. Reopen a ticket once you've more details
