### ISSUE TITLE
Radar not Working

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#181]
Okay so I've found many different things for how to make the radar work, but none of them have worked for me. In most places it says you need a pastebin code to run the program, but I couldn't find it anywhere. In other places it says that as long as the advanced computer is directly on top of the radar that you can just run ls, or dir and the ping and scan will come up.

  None of this has worked. No pastebin I have tried has worked, the ls and dir bring up nothing, and I have looked at all the programs on the computer attached to it, as well as the config files for ComputerCraft, to no avail.

I am running ComputerCraft 1.58, and everything else in warp drive works fine (just not the radar)

Thank you for any help in advance guys!

**Comment by LemADEC** [comment]
Reset the mod configuration and try again. If it's still fails, post your full FML server logs.

**Comment by ghost** [comment]
Thanks for your help, I found the issue.
It turns out that I was just running the wrong version of computercraft. I changed it to an older version (who would have thought?) and now it works great.
Thanks guys!

**Comment by ghost** [comment]
Oh, wait, I was thinking of a different issue, how funny. The radar is all better now, too though, lol.
Thanks!!
