### ISSUE TITLE
Ship formation not possible do to cc error? 

### ISSUE THREAD

**Issue by Deckee** [LemADEC/WarpDrive#183]
A ship cant be created because of this bug.
WarpDrive-1.7.10-1.3.21.-.jar or 
WarpDrive-1.7.10-1.3.22.-.jar
ComputerCraft1.75.jar
industrialcraft-2-2.2.822-experimental.jar
I name the the ship it troughs many errors and goes to this screen. 
![2016-06-02_22 45 54](https://cloud.githubusercontent.com/assets/8199121/15768191/6d9029ea-2914-11e6-91f6-90a23729ef8b.png)
![2016-06-02_22 43 13](https://cloud.githubusercontent.com/assets/8199121/15768192/6f733fa4-2914-11e6-840b-372be1233c19.png)
![2016-06-02_22 45 57](https://cloud.githubusercontent.com/assets/8199121/15768196/73e69310-2914-11e6-8168-13ca301a045a.png)

**Comment by LemADEC** [comment]
There's no error here. You just need to use the bottom menu, as usual.

**Comment by Deckee** [comment]
it just gets stuck on the computers blue screen, read the wiki and followed step by step

**Comment by LemADEC** [comment]
Bottom text is the menu: press 0 for connections page, press 1 for Ship core page, press X for exiting

**Comment by Deckee** [comment]
I will try that

**Comment by Deckee** [comment]
that worked
