### ISSUE TITLE
Radar Help

### ISSUE THREAD

**Issue by dommiddleton4** [LemADEC/WarpDrive#185]
Hi sorry if this is a stupid issue but I'm wondering how I set up the radar?
I have the radar next to a full MFSU and also next to a ComputerCraft monitor & advanced computer, adn when I do "ping 100" it says "ping:41: attempt to call nill"
then when I try to do scan it says : "scan:69: attempt to call nill"
Here are screenshots:
![2016-06-18_17 55 36](https://cloud.githubusercontent.com/assets/20016290/16172329/363b2e06-357e-11e6-9187-6b75411f0863.png)
![2016-06-18_17 57 40](https://cloud.githubusercontent.com/assets/20016290/16172328/363b0fb6-357e-11e6-869a-95ebfafed108.png)
![2016-06-18_17 57 42](https://cloud.githubusercontent.com/assets/20016290/16172331/363e6c06-357e-11e6-9d53-f7b806f1aae6.png)
![2016-06-18_17 57 44](https://cloud.githubusercontent.com/assets/20016290/16172330/363ca9ca-357e-11e6-9c5d-57ab2a7a0230.png)

Thanks

**Comment by LemADEC** [comment]
What version of IC2 and WarpDrive are you using?
What does it say when right-clicking the radar?

**Comment by LemADEC** [comment]
Any update on this issue?

**Comment by dommiddleton4** [comment]
Sorry yes didn't see this before, forgot to check my emails my bad..
I'm using the 1.7.10 versions here:
![image](https://cloud.githubusercontent.com/assets/20016290/16396938/422b9dd0-3cb9-11e6-92d2-e92d5bbf5162.png)
And when I click on the radar it just says the amount of EU being used

**Comment by LemADEC** [comment]
That version of WarpDrive is way too old, please uses latest.
I can't see your IC2 version number here.

**Comment by dommiddleton4** [comment]
Ah I see I'll update it now 
And yeah it doesnt show for me but when I enter the archive it shows up as: Industrial-Craft-2-Mod-Experimental-1.7.10.jar So thats probably out of date too...
Sorry if this was a pointless post aha

**Comment by LemADEC** [comment]
No update, assuming fixed
