### ISSUE TITLE
Protection plugin support doesnt support cross dimension warping

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#187]
Hi @LemADEC 

The Protection plugin support is great, except for when you warp down into a planet... for some reason it may be using the Space coordinates to check (<0 Y) for block break/place ability, and not the coordinates on the destination dimension.

Not a huge deal, but it does trap players if they warp down to a world near the spawn of it and there a place they do not have interact/build rights as it is protected.

I'm assuming this might also be the case in the reverse direction... not sure.

There seems to be intermittent issues with the implementation overall. A player not long ago warped into his faction claim.

Regards,
DraksterAU

**Comment by LemADEC** [comment]
This is fixed in next update
