### ISSUE TITLE
No opencomputers method for advanced laser tutorial

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#188]
Can you make an extra page with instructions on how to use the laser with opencomputers computer?
Would be nice because i really like opencomputers

**Comment by LemADEC** [comment]
The mod uses the same method for both ComputerCraft and OpenComputers.
The only differences are the syntax sugar between ComputerCraft and OpenComputers themselves, The latest is already explained in the Laser basic tutorial.

**Comment by LemADEC** [comment]
No update since 8 days, assuming fixed
