### ISSUE TITLE
Add teleporter plate / revisite space teleporter

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#19]
Add a new block or at least a configuration defining the block that receive an entity/player during teleportation.
Revisit the algorithm to choose a plate nearby destination to move the teleported entity/player on.

**Comment by Sasszem** [comment]
Also add some cool particle effects for the transporter!

**Comment by LemADEC** [comment]
Yes, it would be great. Sadly, we've yet to find a decent texture artist to work with us...

**Comment by Sasszem** [comment]
I think, if y write a list of the needed textures, a lot of people'll help.

2015.08.24. 3:41 keltezéssel, LemADEC írta:

**Comment by LemADEC** [comment]
The list is directly visible in the jar itself :)

**Comment by Sasszem** [comment]
I've seen that you did it. But tell me: How does it work? I've tried, buit I couldn't transport myself.

**Comment by LemADEC** [comment]
I've only reviewed the code, never played with it in practice, as far as I know Darkholmenk wasn't finished with it, hence the need to revisit the algorythm.

**Comment by CaptainMegavolt** [comment]
I could make some textures for this mod. I've already started making a private texture pack for it.

**Comment by LemADEC** [comment]
We're almost done with redoing the blocks textures. Items and effects are open for taking :).
Come on the community TeamSpeak to discuss it further => ts.worldwarminecraft.net

**Comment by CaptainMegavolt** [comment]
I'll see what I can do. :)

**Comment by LemADEC** [comment]
Equation were already fixed, this ticket no longer applies
