### ISSUE TITLE
Weapon Controller

### ISSUE THREAD

**Issue by LuckyLuke313** [LemADEC/WarpDrive#190]
I know its not the right place but i dont know what to do. I coudnt figure out how to use it correctly (i tried it like 3-4 weaks). If any one could post a link to a tutorial or help me with a comment i would  realy appretiate  it thanks for your fast replies.

(i am using the 1.3.22 version of WarpDrive)

Sorry dear mod creator i completly fergot to check the forum out and to thank you so, THANKS

**Comment by LemADEC** [comment]
What did you try? what did you observe?

**Comment by LuckyLuke313** [comment]
I failed trying to connect laser batterys (particle boosters and a laser camera) with the weapon controller. I placed a computer near both and tried to figure out the name of the Controller for ComputerCraft.

**Comment by LemADEC** [comment]
You don't need to connect particle boosters to computers in 99% cases.
You only need to connect the 'Laser(s)', the 'Laser+camera(s)' and the 'Weapon controller' to the same computer.

**Comment by LuckyLuke313** [comment]
Ah okay that was my problem thank you for your help
