### ISSUE TITLE
Compatibility list for 1.12

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#191]
High priority:
- [x] BlockStates
- [x] Rendering
- [x] CoreMod
- [x] JumpBlock
- [x] Particle effects
- [x] I18n -> TextComponentTranslation 
- [ ] IC2 explosion destroy blocks before the attached tile entity, causing crashes in cloaking core

Medium priority:
- [x] Computer interfaces

Low priority:
- [ ] remove ITickable from force fields blocks
- [ ] find a replacement for markBlockForUpdate
- [x] check SMP support for /invisible
- [x] air decrease next to breathing entities

**Comment by craft90** [comment]
Have you considered support for Tesla (https://minecraft.curseforge.com/projects/tesla) and/or the new Forge power API (it's a lite version of RF as far as I understand)?

**Comment by ghost** [comment]
With which computers from which mod will be working WarpDrive and when approximately will be released 1.10.2 version?

**Comment by LemADEC** [comment]
Forge and Tesla supports aren't a priority, mostly because of the impacted CPU consumption.

I'm currently using OpenComputers in my dev space. ComputerCraft should be compatible too.

**Comment by RedstoneParkour** [comment]
How did this issue about 1.10 compatibility end up in an milestone for 1.12?

**Comment by LemADEC** [comment]
Because 1.10 support was dropped to focus on 1.12
