### ISSUE TITLE
How to fix "No Space to Jump" when in an open area and nothing around you

### ISSUE THREAD

**Issue by Da-Spud** [LemADEC/WarpDrive#193]
How to fix "No Space to Jump" when in an open area and nothing around you

**Comment by LemADEC** [comment]
Enable all logs, reproduce the issue, then post your logs

**Comment by Da-Spud** [comment]
[LOG.txt](https://github.com/LemADEC/WarpDrive/files/380581/LOG.txt)

**Comment by Da-Spud** [comment]
sorry it took so long, the internet crashed earlier

**Comment by LemADEC** [comment]
[01:33:56] [Server thread/INFO]: CheckMovementResult -2242.0, 102.0, 3913.0 -> -2243.0, 102.0, 3913.0 false 'Ship is entering a protected area'
=> you can't move your ship inside spawn or similar plugin protected area
