### ISSUE TITLE
WD or OC Issue? NetworkDispatcher exception io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by steelshot** [LemADEC/WarpDrive#196]
Recently discovered this mod with open computer, and i'm loving it, but i'm having an issue on every jump.

I set the coords to an empty area, ships seems to move fine with all blocks and so so. But once the warp is done maybe after 1-2 sec i get kicked with this error: `[00:24:47] [Netty Client IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(6) + length(1) exceeds writerIndex(6): UnpooledHeapByteBuf(ridx: 6, widx: 6, cap: 6)`

It does seem that the warp finishes successfully, and it feels like OC issue, but i'm just double checking if i'm correct.

http://paste.ee/r/yuabq search for [00:22:04] timestamp

EDIT: It seems that once a new ship is built and a computer is setup, it does not kick me out for the first jump, after that kick every time.

**Comment by LemADEC** [comment]
Are you able to reproduce it in single player with only WarpDrive and OC ?

**Comment by steelshot** [comment]
Gimme 5 mins

**Comment by steelshot** [comment]
Seems i need a power mod.... gimme few extra mins

**Comment by steelshot** [comment]
Doesn't seem to crash or anything now on single player

**Comment by steelshot** [comment]
It has seem that the issue, has **mysteriously** disappeared, I dont know how, i only did reboot the server, but i did do that loads of time during testing phase, maybe there was some invisible blocks or something picked up in ships dimensions or something....

I'll close the issue and re open it, if i manage to track something down. I'll more extensive testing later on today.
