### ISSUE TITLE
Weird Particle effect?

### ISSUE THREAD

**Issue by Venrixia** [LemADEC/WarpDrive#197]
Whenever im in a chest or any other block with a inventory, when you put your cursor over a filled Air Cannister, and press T, weird particles show up

![parti](https://cloud.githubusercontent.com/assets/20848405/17420923/e4619618-5a73-11e6-874e-d6e85d31d433.jpg)

**Comment by LemADEC** [comment]
I can only reproduce it with JABBA barrels holding air canisters.
Particles seems like the force field ones.

**Comment by LemADEC** [comment]
As discussed on Discord, this is actually a feature from JABBA barrels, hence not an issue.
