### ISSUE TITLE
transporter

### ISSUE THREAD

**Issue by DarylOliver** [LemADEC/WarpDrive#198]
I am aware there is an issue on how to configure the transporter but I was wondering currently how do you use it if you can?

**Comment by LemADEC** [comment]
Transporter isn't balanced, and has no preloaded script to make it work.
You can teleport entities between 2 spots with it. Adding beacons at source/target will reduce the cost.
There's an unstability factor depending on distances, beacons and boosting energy provided.
LUA methods are self documented.
Good luck :)
