### ISSUE TITLE
Make dependencies optional

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#20]
- [x] ComputerCraft
- [x] OpenComputers
- [x] IndustrialCraft2
- [x] ThermalExpansion

**Comment by TheNumenorean** [comment]
Dont we already have IC2 and TE?

**Comment by LemADEC** [comment]
They're required. Object is to make them 'optional'.

**Comment by TheNumenorean** [comment]
Ah, my apologies

**Comment by LemADEC** [comment]
fixed in 1.3.1
