### ISSUE TITLE
Large ships breaks OC case link with peripherics

### ISSUE THREAD

**Issue by vrnRaptor** [LemADEC/WarpDrive#203]
Program freezes on opencomputers after warp. After restarting computer, everything works again.

**Comment by LemADEC** [comment]
What version of the mod are you using? Is it in single player or multiplayer?
Are you warping in the same dimension?
We'll your full logs during the jump.

**Comment by vrnRaptor** [comment]
I have written is not entirely wrong. Computer does not freezes, picture on the monitor freezes. But I can still warp.
I use WarpDrive v1.3.26
I tested this in a single game
Freezes after any warp, no matter where.
Full log:
[latest.zip](https://github.com/LemADEC/WarpDrive/files/427269/latest.zip)

**Comment by LemADEC** [comment]
You'll have to add the following lines to the block_tags section in WarpDrive.cfg:

```
    S:"OpenComputers:case1"=PlaceLatest
    S:"OpenComputers:case2"=PlaceLatest
    S:"OpenComputers:case3"=PlaceLatest
    S:"OpenComputers:caseCreative"=PlaceLatest
```

For the record, you also have sound issues:

```
[17:21:35] [Client thread/INFO]: Couldn't play computer speaker sound because your sound card ran out of memory. Either your sound card is just really low-end, or there are just too many sounds in use already by other mods. Disabling computer speakers to avoid spamming your log file now.
```
