### ISSUE TITLE
supported mods snagging ship

### ISSUE THREAD

**Issue by SpicyForthProgrammer** [LemADEC/WarpDrive#204]
mekanisim universle cable snagged my ship, network cables(cc), big reactors, enderio capacitor banks 
all snagged my ship

**Comment by LemADEC** [comment]
Snagging happens when your ships dimensions are incorrect, typically those cables are placed right outside your ship.
It's a safety measure so you don't split your ship by mistake.

**Comment by SpicyForthProgrammer** [comment]
oh oops I anti mattered it
