### ISSUE TITLE
WarpDrive is NOT working with EnderIO/RF

### ISSUE THREAD

**Issue by evgkul** [LemADEC/WarpDrive#207]
Ship Core don't receives energy from EnderIO

**Comment by LemADEC** [comment]
It's working on the official pack since 2 years now.
You've provided no logs and no version information.

**Comment by evgkul** [comment]
Versions are latest

**Comment by evgkul** [comment]
Sorry, but on which version of EnderIO it works properly?

**Comment by evgkul** [comment]
There is nothing about EnderIO and Warpdrive in logs(debug energy logs are enabled)

**Comment by LemADEC** [comment]
'Latest' isn't a proper version number.
We need all mods version and the logs.
And possibly a screenshot of your setup.

**Comment by evgkul** [comment]
EnderCore-1.7.10-0.2.0.34_beta.jar
EnderIO-1.7.10-2.3.0.425_beta.jar
ForgeMultipart-1.7.10-1.2.0.347-universal.jar
OpenComputers-MC1.7.10-1.6.0.7-rc.1-universal.jar
WarpDrive-1.7.10-1.3.20.-.jar

**Comment by evgkul** [comment]
http://pastebin.com/j1gN7x1Y

**Comment by evgkul** [comment]
http://i.imgur.com/B8lvdCN.png

**Comment by evgkul** [comment]
[mods.zip](https://github.com/LemADEC/WarpDrive/files/453251/NewArchive.zip)

**Comment by evgkul** [comment]
Also I tryed to use ImmersiveEngineering, but it also not worked

**Comment by LemADEC** [comment]
EnderCore, EnderIO, WarpDrive, CodeChickenLib and OpenComputers are out of date in your setup.
ForgeMultipart needs to go in the mods/1.7.10 folder to work properly.
RF works with the CoFHCore mod.

**Comment by evgkul** [comment]
Thanks!

**Comment by evgkul** [comment]
And can you write somewhere about CoFHCore?

**Comment by LemADEC** [comment]
No RF mods work without CoFHCore.

**Comment by evgkul** [comment]
Strange(EnderIO and Immersive Engineering worked normally)

**Comment by LemADEC** [comment]
They both comes with an old version of CoFHCore.

**Comment by evgkul** [comment]
But normal player doesn't know about it :)

**Comment by LemADEC** [comment]
Forge doesn't provide a proper solution for this, sadly.
