### ISSUE TITLE
(Question) are berzerkers possible?

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#210]
Would it be possible to create some sort of computercraft ai controlled berzerker that would go to random coordinates in space and shoot (and pursue) any ships and players in range that were not part of a playerlist? it would be cool if you could send one to destroy some enemy ships, it would operate completely on its own. But it would probably require a huge amount of coding, would it be possible?

**Comment by LemADEC** [comment]
You can fully automate your ship movements with LUA scripts.
Players aren't directly reported by radar but you can use laser cannon to scan for them or just a bunch of turrets to deal with them ;).

**Comment by ghost** [comment]
You mean it can be fully automated?

**Comment by LemADEC** [comment]
yes
