### ISSUE TITLE
Cannot Get FF Projector To Operate

### ISSUE THREAD

**Issue by Maxstripe** [LemADEC/WarpDrive#214]
with max() method cannot change to anything larger than 1,1,1
and with enable(true) it wont generate any feild

**Comment by LemADEC** [comment]
max() accepts a floating value between 0 and 1. You can scale it up with range upgrades.
projector is enabled by default. Are you sure you've provided power and set a frequency?
what's the projector sides color?

**Comment by Maxstripe** [comment]
east and west sides are blue circles
rest are green semi circles
fully powered and has a freqency set. it wont generate shield blocks tho

**Comment by Maxstripe** [comment]
solved: Factions prevents the FF block from placing sheild bits

**Comment by LemADEC** [comment]
Nice!
