### ISSUE TITLE
AE2 quantum link chambers are hard coded anchors

### ISSUE THREAD

**Issue by Maxstripe** [LemADEC/WarpDrive#215]
AE2 quantum link chambers anchor ship when theyre on board even tho they arent set as anchors in teh config file or even in the config file

**Comment by LemADEC** [comment]
Which versions are you using?
Please post the logs too.

**Comment by Maxstripe** [comment]
.29 (server own has said this is the version were using)
cant access logs as its on a server

**Comment by LemADEC** [comment]
Anchors configuration is server side only. Check with your server staff, not me.

**Comment by Maxstripe** [comment]
i checked the config. it is not listed in the config

**Comment by LemADEC** [comment]
Server side configurations and logs.
