### ISSUE TITLE
Ship Cores Detonate On Break

### ISSUE THREAD

**Issue by Maxstripe** [LemADEC/WarpDrive#216]
Ship cores detonate upon breaking them even if the cooldown is done
this seems like a bug

**Comment by LemADEC** [comment]
What version are you using?
What are the logs?
What does it say?
What do you mean by breaking?
What cooldown are you talking about?

**Comment by Maxstripe** [comment]
.29
on a server so i cant access said logs
it says nothing
mining the core with an atomic disasember from mekanism
the jump cooldown. i waited till it was complete thinking it wouldnt blow up then but it still blows

**Comment by LemADEC** [comment]
Ship core are intended to explode if broken after first jump.

**Comment by Maxstripe** [comment]
so how are you suposed to harvest them?

**Comment by LemADEC** [comment]
They are too delicate for that.
You can only recover before you first jump or from derelic ships.
Also, with fortune 3 you can recover most components.
