### ISSUE TITLE
Ship disappeared

### ISSUE THREAD

**Issue by axelpx** [LemADEC/WarpDrive#218]
I lost my ship when trying to land on a planet dimension. I wanted to recover it from an autosave schematic but it didn't work. This is what WE says when trying to load backup schematic:

Schematic could not read or does not exist: Tag 'Schematic" does not exist or is not first.

**Comment by LemADEC** [comment]
Backup needs to be moved to the main schematic folder first.
You only give the file name, no folder or extension.

**Comment by axelpx** [comment]
I've done it. And even tried to rename it to something like 'aa'. This is the command that I use 
//schematic load aa (without extension)
and this is what I get 
"Schematic could not read or does not exist: Tag 'Schematic" does not exist or is not first."

Can post screenshots of that I'm doing everything right.

**Comment by axelpx** [comment]
![default](https://cloud.githubusercontent.com/assets/1360553/19627790/1765c886-9958-11e6-9cbc-ce56f8413575.JPG)

**Comment by LemADEC** [comment]
WorldEdit save format isn't compatible with forge as it's missing critical information.
You need to use the ShipScanner block to restore an autosaved ship. Something like:

```
<componentName>.deploy(<shipname>, <Xoffset>, <Yoffset>, <Zoffset>, <Rotationstep>)
```

**Comment by axelpx** [comment]
Lem, can you provide some information on how to use ShipScanner please. Maybe a simple template for a program or something. It would be very appreciated. Thanks in advance.

**Comment by axelpx** [comment]
Oh, one of my friends made a simple program to restore ships. 
Here it is, if some one needs it: http://pastebin.com/HyNXDjfm
