### ISSUE TITLE
Crash with Immersive Engineering

### ISSUE THREAD

**Issue by axelpx** [LemADEC/WarpDrive#220]
Here is the crashlog. It always happen in DIM-3 of the WarpDrive (Hyperspace) and always after a restart of the server (server is unable to start until the dimension DIM-3 is wiped).

http://pastebin.com/t99HZht9

Mods version:
WarpDrive: WarpDrive1.7.10-1.3.30.
Immersive Engineering: ImmersiveEngineering-0.7.7.jar

Server core: Thermos:1.7.10-1614.57

**Comment by LemADEC** [comment]
We have those 3 versions on the official server and no such issues.
Sounds more like a Mekanism bug regarding chunkloading.

**Comment by LemADEC** [comment]
Any update on this?

**Comment by LemADEC** [comment]
No update, assuming fixed
