### ISSUE TITLE
Transporter Does Not Have Activation Method

### ISSUE THREAD

**Issue by Maxstripe** [LemADEC/WarpDrive#221]
the transporter block is missing an activation method to transport things with

**Comment by LemADEC** [comment]
You need to "energize".

**Comment by Maxstripe** [comment]
Do I just call the energize function or is there any parameters that need to be entered? Also the crafting recipe doesn't show

**Comment by LemADEC** [comment]
As the change logs says:
"Scanner, Transporter, Beacon and Decorative blocks are 'work in progress', recipes are disabled for a reason, use at your own risk."

**Comment by LemADEC** [comment]
Existing Transporter API is described in the forum, here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2510855-1-6-4-1-7-10-warpdrive-custom-ships-laser-cannons?comment=772
