### ISSUE TITLE
New lua libraries (hooks too) and globals

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#222]
Selecting (including GetPos() GetOrigin() etc):
spacegen.GetAll/GetPos("structurename", "structurename", "structurename", etc) (allows user to select structures generated in space/with commands

ship.GetPos("shipname") (select ship by name)
ships.GetAll() (speaks for itselfs)
local/ship.GetPos/GetOrigin("number of warp") (get users ship pos and origin)

Targeting/warping:
GetPos("shipname", "warpcontroller/warpcore/energy origin")
GetOrigin("shipname", "warpNumber( 1 is first etc))
ships.GetAll() (use for k,v in next ships.GetAll() to select all nearby ships)
local (local ship)
ship("shipname", "positionselection(alternative)")
warpTo("position grabbed by function)/ table" )
shootLaserTo("(same as above)" )
reactorIsStability("stability percentage value") then
reactorIsActive() == true/false (is the reactor on or off?)
miningLaserIsActive() == true/false (is it on or off?)
ship/local.IsWarping() do (execute if ship is warping)
forcefield.GetStatus() (returns energy value range strenght etc)

Hooks:
hook.Add("onShipWarp", "string", "function called()" )--is the ship starting to warp?
hook.Add("onLaserShoot", "string", "function()" )--did the laser shoot?
hook.Add("onWarpFinished", "string", "function()" )--did the ship warp succesfully?
hook.Add("onMiningLaserActive", "string", "function()" )--also onMiningLaserOff
hook.Add("onWarpEnergyLack", "string", "function()" )--if user tries to warp but fails because not enough energy
hook.Add("onWarpImpact", "string", "function()")--if ship impacts object and computer running script not broken

"function()" is the name of the function that is called when event occurs
"warpNumber" must be a value like 2.
It means that it grabs the position after move(warp 1) was made. Every value is the position of its lower value. For a failsafe make it have a range between 0 and 255 that if you try to grab the origin of the ship higher then 255 (like you input warpNumber as 257 and it tries to grab the ships pos when it had finished its 256th warp it will output out of origin range)

"Table" is the name of the table stored with position data. Make it have a check that if the pos is not in front of the laser in a 180 degrees radius and/or the values are incorrect/non existant it returns with a print: "incorrect data" (if incorrect position like no z value) or just nil if non existant in table
Make it delete table data if another getpos/getorigin is runned and inserted into that table
Make most of the on(event) also work for ships/ship/local

I hope this makes scriptings for warpdrive easier

Question: how do i scan and target entities/players?

**Comment by LemADEC** [comment]
Most of those are creative commands that should never be accessible to normal players.
There's no such things as hooks in LUA with CC/OC. There's only events, that are already most of your proposals.

This seems like you want to define an API before actually trying to use the existing one...

**Comment by ghost** [comment]
Oh i never knew there werent hooks. I never needed them actually in cc

**Comment by ghost** [comment]
Sorry
