### ISSUE TITLE
OpenComputers Integration

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#223]
On your curseforge's page write about integration with OC, but all yours expamles writed on ComputerCraft base. Can you write a guide with OC?

**Comment by LemADEC** [comment]
Examples are provided for both. Preloaded scripts are also available for both. So I don't really see your point here...

**Comment by ghost** [comment]
I think he means that the opencomputers coding is a slight bit harder

**Comment by LemADEC** [comment]
Closing due to lack of answers from original poster
