### ISSUE TITLE
capacitor bank brings crashes

### ISSUE THREAD

**Issue by Soyaro666** [LemADEC/WarpDrive#228]
Well, as the title said.
To give some more detail: I've been playing in creative with a massively modded pack I've been working on for a while. I built some superior capacitor banks, started loading them, tried some wrenches on them, then broke them and got this crash log. https://openeye.openmods.info/crashes/90ea61dd3cec599eccd8e1ef8755ce95
crash was reproduceable (at least in this pack) and OpenEye doesn't identify any mods beside warpdrive involved in the crash, so I'm asking you for help ;-)

for now I'm going to disable capacitor crafting recipes 'til I know how to avoid this crash...

**Comment by LemADEC** [comment]
Looks like you've managed to get corrupted block.
Try with latest version for a start: https://minecraft.curseforge.com/projects/warpdrive/files/2333031
Please post the full crash log too.

You need to use tuning forks to configure the Subspace capacitors sides.

**Comment by Soyaro666** [comment]
ah. I didn't want to use beta mods 'cause usually stable mods should be, you know, stable... I'll give it a try and write back in a few hours I guess.
btw, is there a way to switch EU to RF?

edit: the previous crashlogs raw data: http://pastebin.com/1kWTrjCY

**Comment by Soyaro666** [comment]
allright. it's not that I need to use tuning forks for an effect. I have to use them because wrenches do corrupt the block. 
raw crashlog: http://pastebin.com/WaKrdP3C

when using a wrench the capacitors name may change (waila names a superior capacitor as basic capacitor, for example). tested wrenches from forestry, magneticraft, minefactory reloaded, thermal expansion, matter overdrive, RFTools and sonic screwdriver from tardismod. the wrench and the side I rightclicked onto had influence on what happens with the capacitor. it's hard to explain... however, I guess it's a compatibility problem between warpdrive and at least some of those wrenches/wrench apis...
