### ISSUE TITLE
some feature requests about custom oxygen distribution

### ISSUE THREAD

**Issue by Soyaro666** [LemADEC/WarpDrive#229]
Hey.
Custom helmets please. Yes, I'm aware I could simply install IC2 and use their oxygen tanks with any helmet I put into config. Problem is I don't like IC2, it would screw my current mod collection in multiple ways. But I have multiple mod armor sets that would/should have the ability to provide oxygen (modular power suit, Antman suit or higher tier ironman armor for example).
I'd like to see trees as oxygen providers. My Idea in that case would be a config option like "block a, if adjacent to block b, becomes an oxygen distributor of strength c". if the strength part isn't possible there could be a minimum count of block a per block b. Balancing would be the size (a flying forest would be huge so it would cost a lot more energy to jump with that, on the other hand you wouldn't need to worry about your life supports energy consumption).
A portable life support system of some sort would be nice. I have something like a chestplate in mind that does distribute oxygen to a helmet. In this case I'm thinking about the ironman suit again. I would want to have a config list where I simply have to add chestplates for them to become oxygen distributors. Maybe there would be a special item needed in inventory for balancing reasons (life support generator/battery that needs to be replaced/recharged less often than oxygen tanks?) this would end with following constellation: generator or battery in inventory, a chestplate that does drain such energy sources to distribute oxygen and a helmet/mask that could distribute oxygen from oxygen tanks/tubes/whatever but prefers to drain previously named chestplate. I'm talking about high tier tech that should be more expensive compared to simply fill your inventory with oxygen containers...

well, enough ideas for one post I guess. And if there were similar requests I'm sorry, I did search for oxygen related topics but didn't find anything beside GC compatibility requests...

**Comment by LemADEC** [comment]
Oxygen is already in rework on 1.10, notably to use WarpDrive air canister with custom helmets.

Trees don't produce oxygen, they only (slowly) recycle it. I don't really like GC approach to that as it's fairly unrealistic and lag inducing for servers. I think Air should be created from ice or water sources, while the trees would be an cheaper but slower approach to recycle used air. In other words, the more trees you've in your ship, the faster air quality increases, the more entities you've, the faster it decreases.

I don't quite get what you mean with your chestplate proposal, can you elaborate on that?

**Comment by Soyaro666** [comment]
short version: you have to wear a helmet that can provide oxygen from containers, but if you're wearing a chestplate that supports it, you're consuming energy from your inventory instead of oxygen tanks.
In addition, based on your idea of ice and/or water, snow balls/blocks, ice blocks or water containers could be consumed too. Here we'd be talking about a portable oxygen generator...

**Comment by CaptainMegavolt** [comment]
So, you're proposing a chest plate that would generate oxygen from ice and
electricity on the fly? A good idea, in my opinion. ;D

**Comment by LemADEC** [comment]
31785f7f971172bb288d1314753401ad48d059bc
e27b08f08b89388014d5247f09ba16befcb389a8

Since 1.10 is stalled due a Forge bug, I've added armor bonuses to 1.7.10.
