### ISSUE TITLE
AVP mod support

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#230]
As reported by @Tapmemer on #163 :
The maker of avp mod, ri5ux might want some mod integration too. He made it so two suits from the mod make you able to breath in warpdrive dimensions

**Comment by LemADEC** [comment]
AVP uses a deprecated API IBreathingHelmet that was removed a few months ago. This functionality is currently handled directly in IAirCanister and WarpDrive configuration.

**Comment by ghost** [comment]
Ill contact ri5ux and give him this

**Comment by LemADEC** [comment]
This is not a WarpDrive issue, assuming ifxed in AvP.
