### ISSUE TITLE
Mekanism v9 Universal cables aren't detected

### ISSUE THREAD

**Issue by craft90** [LemADEC/WarpDrive#232]
I tried to connect power to the ShipCore via an Ultimate cable from Mekanism. However it refused to connect to the block and the ShipCore did not charge up. Connecting the Energy cube directly to the Ship Core did work though.

**Comment by LemADEC** [comment]
What version of WarpDrive and Mekanism are you using?
Did you actually enable IC2 and RF support in Mekanism?
Did you add CoFHCore or IC2API to enable RF or IC2 in WarpDrive?

**Comment by craft90** [comment]
It's the latest version of Mekanism and WarpDrive for 1.7.10
I wasn't aware you had to? Universal cables usually works with RF without config changes. (These are fresh configs n.b.)
I used COFHlib at first. When Universal Cables didn't work I added Thermal Dynamics (which meant thst I also replaced COFHlib with COFHcore.) Redstoneflux ducts connected properly. I don't use IC2. In my second try I simply put the Creative Energycube right next to the core and it worked without issue (and faster than redstone ducts).

**Comment by craft90** [comment]
Also, is there a config for changing power display units? As I only use RF, EU doesn't say me anything.

**Comment by LemADEC** [comment]
'Lastest' is not a version number. We need the exact version numbers.
Energy unit display is part of the 1.10 update.

**Comment by craft90** [comment]
Fair enough.
WarpDrive 1.7.10 - 1.3.30
Mekanism 1.7.10 - 9.1.0.281
MekanismGenerators 1.7.10 - 9.1.0.281
MekanismTools 1.7.10 - 9.1.0.281
Computercraft 1.7.10 - 1.75
