### ISSUE TITLE
Default LUA scripts use hardcoded max jump distance

### ISSUE THREAD

**Issue by khionu** [LemADEC/WarpDrive#236]
I am trying to rescale distances/costs/etc for my pack, and I set the configuration to 1024 blocks for maximum jump distance, but I'm still limited to 149, which is more than the default value.

I think this might be part of a bigger problem, however. I think the configuration needs an overhaul. There seems to be a lot of values that you would expect to be covered given the ones that are, such as Hyperspace Jump distances.

**Comment by LemADEC** [comment]
Maximum jump distance is hard-coded in the LUA scripts. You need customized those if you want to access something bigger than 127 blocks.

We're missing the mod version number for your issue.
We're missing details on 'configuration overhaul'.

**Comment by khionu** [comment]
By "configuration overhaul", I meant a revision of what values in the mod could be set into the configuration. There were several things I was searching for, before I stopped working on my pack.

I'm using Latest Release for 1.7.10

**Comment by LemADEC** [comment]
'Latest' is NOT a version number.
If you remain vague, I can't help you with your configuration issues.

**Comment by khionu** [comment]
1.3.29, which is listed as the latest release on CurseForge.

Forgive me if I haven't seen your forums, they aren't linked in this repo or on the CurseForge. From my research, and the research of a few others I was talking to about my modpack, this mod has been in extremely slow development, at best.

Just as you don't want your time wasted, nor do I. That was my concern, though it does seem my conclusion was drawn without all the facts. I would suggest linking your forum in more places, if that's the optimal place to find information.

**Comment by LemADEC** [comment]
Latest is 1.3.30: https://minecraft.curseforge.com/projects/warpdrive/files 
CurseForge doesn't want it to be upgraded to release for some reasons.

**Comment by LemADEC** [comment]
I guess we'll never know what was the configuration issue :(
