### ISSUE TITLE
Warp Chestplate, Leggings, and Boots not available

### ISSUE THREAD

**Issue by khionu** [LemADEC/WarpDrive#238]
NEI doesn't show them, though it seems they are supposed to exist? https://github.com/LemADEC/WarpDrive/blob/31785f7f971172bb288d1314753401ad48d059bc/src/main/java/cr0s/warpdrive/item/ItemWarpArmor.java

**Comment by Echo343** [comment]
They exist in NEI; however, they are missing their item textures last I knew.  In NEI look for the purple and black checkerboard pattern.

**Comment by khionu** [comment]
I did multiple searches, went through all the possible recipes that use Iron, etc. After I made this issue, I even checked my Minetweaker dump, wasn't there.

Note, I hadn't yet implemented anything with Minetweaker, I was in the process of doing a playthrough to list everything I wanted to adjust.

**Comment by LemADEC** [comment]
The WarpArmor full set is only available in dev space, related Item textures are on hold.
