### ISSUE TITLE
Could you allow me to compile part of the codes and run some tests?

### ISSUE THREAD

**Issue by Sunspot0411** [LemADEC/WarpDrive#239]
Hi LemADEC, would you allow me to use part of 1.10.2 source code to test some of features? I want to test if the laser cannon and explosion works fine for Valkyrien Warfare mod. If you allow me to do so, then could you tell me which parts of the code are necessary? The computer I'm currently using is not fast. If you it is not ok then could you give me a rough estimate for 1.10.2 beta release time? I have been waiting for the 1.10 version for a long time. Thanks

**Comment by LemADEC** [comment]
Computer interfaces, Radar, ship jumping and laser interactions haven't been integrated yet, they most probably non-functional.
Force field is projecting but let entities goes through.
Rendering issues remain in Enantiomorphic reactor core, IC2 Reactor laser and Subspace capacitors. Those needs to be fixed before we can release an alpha, probably in March or something.

**Comment by CaptainMegavolt** [comment]
If I may ask, are there any plans to use the Valkyrian Warfare sub-world
engine integrated into WarpDrive?

*--Marvin_Megavolt*

**Comment by Sunspot0411** [comment]
So there is still a lot of work to do, I'll wait then. But I suggest you consider compatibilities with VW mod when you upgrade. For example a working warp drive and a laser cannon on a VW ship.

**Comment by LemADEC** [comment]
Pretty sure I've already answered to that on the official forum.
