### ISSUE TITLE
Support other mods space dimensions

### ISSUE THREAD

**Issue by Soyaro666** [LemADEC/WarpDrive#240]
Hey there, I'm currently working on [my pack](https://minecraft.curseforge.com/projects/dimensional-nightmare)s next version. While warpdrive is in it I just added advanced Rocketry and had a dim id conflict - nothing I couldn't handle but I had an idea in that moment.
Both mods are adding space. There are others doing the same. Why does every mod need an own space if they could be configurable to use an existing dim ID as Space?

I'm requesting one feature. I guess "RegisterWarpdriveSpace=true/false" would work, while default is true. If false you could simply skip dim registration and on jump into space you could check if the dim that's set as space_dimension_id does exist. If it does, jump there, no matter where that dim comes from, if it doesn't the jump simply fails without any movement.

If you don't change anything warpdrive would act exactly like we're used to. but for mod pack authors it would add a lot of possibilities.

**Comment by LemADEC** [comment]
Honestly, I've never been patient enough to grind Advanced rocketry to reach its space dimension. So I'm a bit confused on why one space would be better than the other?

**Comment by Soyaro666** [comment]
It's not about one being better than the other. It's really only what I wrote: Why should you have 2 (or even more?) different dimensions that are, in theory, identical?
Another idea I had about that would be your world generator as an adition of given dims world generation but that would be a mess of code I guess...

Btw, I want to request the same feature over there so you can in fact choose the spacedim you prefer by disabling the one(s) you don't like. I just started here because I'll benefit from features you add. I'll keep using Warpdrive while I have no idea if i'll ever actually play with Advanced Rocketry ;-)

**Comment by LemADEC** [comment]
World generation is attached to the dimension, switching it would be messy.
SkyRendering can be forced in a specific dimension, but that would be weird.
Oxygen/air breathing between the same mods (GC, WG and AR have their own).

Ultimately, there'll be multiple space dimensions in WarpDrive, one per solar system.

**Comment by Soyaro666** [comment]
I thought about TiC which can generate it's Slime Islands in any dimension. Wouldn't a similar mechanic work for your asteroid fields and shuttles, where the set space dim would be the whitelist for them?

**Comment by LemADEC** [comment]
yes, it would be possible in theory, just never done it and not sure how much work it would require

**Comment by LemADEC** [comment]
Fixed in 369bbc746f8af2e0a1fe4bc291dde9f9e84c7862
