### ISSUE TITLE
Recipes are inconsistently implemented

### ISSUE THREAD

**Issue by Brycey92** [LemADEC/WarpDrive#242]
When recipes are at the default of hard ic2 mode, only some of the blocks and items have recipes. In dynamic recipe mode, it seems other blocks and items have recipes, but a few of the ones with recipes in ic2 hard mode do not have recipes in dynamic mode.

**Comment by LemADEC** [comment]
Only dynamic recipes are supported. Blocks without recipes in dynamic are untested/use at your own risk.

**Comment by LemADEC** [comment]
Scanner is intended for spawns and admins.
Chunkloader is largely untested and badly coded.
Teleporter is missing a preloaded LUA script and a balance pass.

**Comment by Brycey92** [comment]
Oh, but then if dynamic recipes are the only ones that are supported, why is ic2 hard recipe mode the default?

**Comment by LemADEC** [comment]
Dynamic recipes are enabled by default since a year ago, around 1.3.20 d179261d0ab2062f77f20bda8a39fe1e8ba7a08a

You may have reused an older configuration. In which case, I strongly advise to backup and delete your configuration then restart your pack to generate the default as you're probably missing a few fixes found in the configuration.

**Comment by Brycey92** [comment]
I took your advice and regenerated the logs, and man, there are a lot of changes I missed! One of the changes, though, disables the jump logs when the comment right above it says they should always be enabled. Is there a reason for this?

**Comment by LemADEC** [comment]
Jump logs are enabled by default.
Jump block logs are disabled by default.
https://github.com/LemADEC/WarpDrive/blob/05c2b47e1da7507d373f639dbb213ebae59df17d/src/main/java/cr0s/warpdrive/config/WarpDriveConfig.java#L382
