### ISSUE TITLE
Force field blocks are visible in NEI

### ISSUE THREAD

**Issue by Brycey92** [LemADEC/WarpDrive#243]
Despite being completely transparent and uncraftable, all the force field blocks appear in NEI. While I can hide this with a separate mod, I do still have to write the configs to hide it, and others may not want the force field blocks cluttering their NEI.

**Comment by LemADEC** [comment]
This is a bug in NEI itself. The mod doesn't report the block nor its variation to vanilla creative menu.
NEI is doing its own listing of block variations force them to be shown.
There's not much we can do on our side to fix this NEI issue.
