### ISSUE TITLE
Server crash on block place/break

### ISSUE THREAD

**Issue by Brycey92** [LemADEC/WarpDrive#244]
With the latest commit (2b473ae3da692e6fe652e8d68b16c803c32489cb) there is a server crash when I place or break a block:
https://gist.github.com/Brycey92/38b82391d846b631083213fcf8c61d72

It appears setStarMapRegistryItems is null when a loop tries to iterate through it in [StarMapRegistry:onBlockUpdated](https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/data/StarMapRegistry.java#L93)

**Comment by LemADEC** [comment]
This is already fixed in my dev space, just haven't commit the change yet

**Comment by Brycey92** [comment]
Cool, thanks!
