### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by Muirrum** [LemADEC/WarpDrive#246]
Good afternoon @LemADEC , I am the current head of development over at Matter Overdrive. Recently, one of our users came to me asking if we could somehow integrate WarpDrive into MO, and I wanted to get your thoughts on this.

**Comment by LemADEC** [comment]
What make you think MO is a godly mod that should eat mine with no further considerations?

**Comment by Muirrum** [comment]
I have no intention of "eating" your mod. The user in question stated that if there were some API function to add MO blocks to the list of allowed warp blocks, that that would be the integration.

**Comment by LemADEC** [comment]
That's a different integration we're talking here :D .
I've never tried jumping with MO blocks or entities, not sure what's the extend of issues.
If it's just about rotations, there's an API here: https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/api/IBlockTransformer.java
Check here for sample implementations and make a pull request: https://github.com/LemADEC/WarpDrive/tree/MC1.7/src/main/java/cr0s/warpdrive/compat

It's easier to start with a reference map as explained here: #192

**Comment by LemADEC** [comment]
Yeah, I remember now, MO never worked in my dev setup, so I couldn't build the compat classes for it.

**Comment by Muirrum** [comment]
Well, from what I can remember about WarpDrive configuration, there's a .config file that contains every block a person can jump with, is that still the case?

**Comment by LemADEC** [comment]
Everything is supported by default, you can blacklist movement or prioritize multiblock components through configuration. If integration is request, I would assume something doesn't work, which is probably multiblock or rotation related.

**Comment by ETStareak** [comment]
Ah，you don't have Chinese lang right?

**Comment by LemADEC** [comment]
Feel free to translate to Chinese and make a pull request :).

**Comment by LemADEC** [comment]
Any update on the specific issue with Matter Overdrive?

**Comment by LemADEC** [comment]
@Dev-Osmium I could boot with the Matter Overdrive mod but the lag is insane, that is too unstable to move further. Open a new issues once you've a stable version or some details I can work on.
