### ISSUE TITLE
[Wiki] Warp armor?

### ISSUE THREAD

**Issue by Adkkid** [LemADEC/WarpDrive#248]
I'm not seeing anything about the Warp armor set in any of the wiki entries. I see that in the air section it explains the air-breathing helmets, but by skimming the others, I saw no other entries about the armor set.

**Comment by LemADEC** [comment]
This part wasn't released and shouldn't be available in any private nor public pack.
Wiki will be updated when we get there.

**Comment by Adkkid** [comment]
I see a recipe for it on our server. We're running a compiled version based off 1.3.30, using the Dynamic Recipes setting. Nothing in this compiled version should have modified the recipes, either.

**Comment by LemADEC** [comment]
You're not allowed to compile and distribute the mod.
Delete it and use the official binaries from CurseForge.

**Comment by Adkkid** [comment]
All right. It's not my server, but I'll let the owner know.

**Comment by LemADEC** [comment]
Added to wiki roadmap #100
