### ISSUE TITLE
[1.7.10] Reactor control programs occasionally crash

### ISSUE THREAD

**Issue by Brycey92** [LemADEC/WarpDrive#250]
Sometimes, when a ComputerCraft computer has been controlling a reactor for a while, the program will crash and a shell prompt appears in the middle of the reactor control program's GUI. This, of course, causes the reactor to explode.

**Comment by LemADEC** [comment]
What version of the mod are you using?
What is the error reported on the computer?

**Comment by Brycey92** [comment]
I'm using 1.3.30, and there is no error reported, it just dumps me back into the shell.

**Comment by LemADEC** [comment]
We need a screenshot of the shell when it happens.
Also, try to enable the LUA and ENERGY logs while reproducing the issue.

**Comment by LemADEC** [comment]
This is a ComputerCraft bug.
A workaround has been added in 99221df636fc8dcf786b6f553ab548ef46eda91d
