### ISSUE TITLE
Cant figure out translation upgrade for forcefields. 

### ISSUE THREAD

**Issue by claytonwilson** [LemADEC/WarpDrive#252]
This may not be the correct place for this question however it is the most maintained area I could find.

This is likely not a bug but my inability to figure out a feature (Cant find any detailed documentation on it).  The "issue" I am having is the translation upgrade for the forcefield projectors not "working".  The upgrade successfully applies to the projector(screenshot #1).  The forcefield generates and stays projected(screenshot #2) and the projector has the ability to change the rotation and beamfrequency (rotation upgrade) (screenshot #3) of the forcefield properly through its Lua attribute .rotation from what I have gathered there should be an attribute for .translation (?) also.  That or I cannot use the one that is there and if this is the case I would greatly appreciate a few exact examples as I cannot figure it out.  Thank you in advance any help is greatly appreciated.
Edit: Present in versions 1.3.30 and 1.3.29
![2017-04-14_21 57 13](https://cloud.githubusercontent.com/assets/11720793/25059908/004a3cd4-215e-11e7-9ed8-570cb78f82b1.png)
![2017-04-14_21 56 43](https://cloud.githubusercontent.com/assets/11720793/25059913/0c0e7e54-215e-11e7-9770-78edb735e84b.png)
![2017-04-14_21 55 06](https://cloud.githubusercontent.com/assets/11720793/25059916/263e0038-215e-11e7-93e9-9ace90ec9941.png)

P.S. Amazing mod imo the best out there.

**Comment by LemADEC** [comment]
This is the repository for the official WarpDrive mod, so you're in the right place :).

The min, max and translation methods are missing on CC API for the forcefield projector, as of 1.3.30. It was fixed through ce8d5e3319a6a9f6c5dc53003d32b818284abf18 but not released yet.
You can use OpenComputers instead for now.
New official version should be out in a couple weeks. I might do an alpha this week, we'll see.

**Comment by claytonwilson** [comment]
That would explain the difficulty :).  

Okay Ill likely just stick with ComputerCraft until the alpha is released. 
Ill be on the lookout for the alpha/release.
Thanks for the help :).

**Comment by LemADEC** [comment]
Fixed back in May, will be up on curseforge soon.
