### ISSUE TITLE
Open Computers Interface doesn't load properly in Singleplayer (v1.7.10) 

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#255]
Hi @LemADEC 

Sorry to bother you with this one but I've set up a creative computer in open computers in single-player and attached it a WD ship controller... but I'm not getting past the Ship core detected... screen.

It says I should press 1 to access the ship core etc, but nothing is appearing in the bottom of the screen like it used to.

If I'm doing something wrong and it's user error, sorry!

See screenshots:
![image](https://cloud.githubusercontent.com/assets/9921203/25777782/bab160a0-332b-11e7-8d9d-d6bf86005fa5.png)

![image](https://cloud.githubusercontent.com/assets/9921203/25777789/e6e5af64-332b-11e7-824d-14c222d01762.png)

I'm using OpenComputers 1.6.2.12 with the latest build available on GitHub in the 1.7 Branch for Warp Drive.

You got me excited when you said skyboxes render! I had to try it out.

**Comment by LemADEC** [comment]
ship core is the center, ship controller is the front.

**Comment by LemADEC** [comment]
you can still do /generate ship, then add your OC computer to the controller.

**Comment by StargateMC** [comment]
Thanks @LemADEC :)
