### ISSUE TITLE
Server Crash bug in Latest code

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#257]
Hi @LemADEC 

In the latest code available on the 1.7 branch the mod will not load on a server, as it is attempting to modify a field in the constructor for BlockDecorative.java that is client only.

I've got around it in my fork / testing by using the below, but you can probably do better? I'm not sure.
if (FMLCommonHandler.instance().getSide().equals(Side.CLIENT)) icons = new IIcon[EnumDecorativeType.length];

https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/block/passive/BlockDecorative.java#L33

**Comment by LemADEC** [comment]
yes, the public repository is SSP/client side only until my modpack is released.
