### ISSUE TITLE
Unable to jump into hyperspace or out again 

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#259]
Hi Lemadec,

I've been doing some testing with your latest code and ran into an issue where I can't jump into our out of Hyperspace. 
Both OC and CC say Destination jumpgate '' is unknown. Check jumpgate name.
Happens in SP and on my dev server.

Hoping you can help ? If it's just WIP no worries.

Regards,
Bysokar

**Comment by LemADEC** [comment]
That should work just fine

**Comment by StargateMC** [comment]
@lemadec You commented out the 3rd entry in the controller modes. It causes issues :)

**Comment by StargateMC** [comment]
The modes get offset by 1 sometimes as a result

**Comment by LemADEC** [comment]
Sounds like a bug in the common setMode() method here: https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/block/movement/TileEntityShipController.java#L120

**Comment by StargateMC** [comment]
No worries sorry didn't know if this was a little temp thing you did til your server is released... So I reported then closed because things appear to work after uncommenting teleport mode

**Comment by StargateMC** [comment]
Ps - do you have any info on what your server will be like? What mc version etc?

**Comment by LemADEC** [comment]
Currently, it's dependent on 3 mods that are only found on 1.7.10.

**Comment by StargateMC** [comment]
Sweet as - What are they ?
Also, what are your thoughts on MMOCore? Would you consider using it if you ran a hybrid server ?

**Comment by Bysokar** [comment]
Ran*

**Comment by LemADEC** [comment]
PM me on Discord to discuss further. Let's keep issue trackers for issues themselves :)
discordapp.com/invite/0ZanfS3S9yu3Wf2M

**Comment by StargateMC** [comment]
I'll figure this out and offer a PR

**Comment by StargateMC** [comment]
just a note  for later- coordinates between space/hyperspace are still 1:1, so it's impossible to jump between space/hyperspace to the correct location unless they are the same size and centre point.

**Comment by LemADEC** [comment]
Position scaling isn't supported. That doesn't mean Space and Hyperspace should have the same border size.

**Comment by StargateMC** [comment]
@LemADEC What I mean is that if CenterX/Z for space is at 150,000 and 150,000 (with a 20k border) and in the space dimension I am at 1,000 and 1,000 if I go up to hyperspace, I will be at 1,000/1,000 .. not within the border. It also happens in reverse when dropping out.. but the out of border message appears.

Sorry for the confusion

**Comment by LemADEC** [comment]
So the transfer shift happens only with planets, not with space/hyperspace. Have you tried both ship and /space commands?

**Comment by StargateMC** [comment]
You cant hit /space when going to and  from hyperspace?

**Comment by LemADEC** [comment]
/space allows you to go in/out of any dimensions

**Comment by StargateMC** [comment]
Edit: The space command is the same, I was testing from my Dim that has the same center as hyperspace (0,0)

**Comment by ghost** [comment]
does his ship even have mass needed to leave when trying to leave?

**Comment by StargateMC** [comment]
Yes. The bug is in the global positioning system for star systems that do not have the same dimensions and position of the hyperspace dimension. Lems well across it dw :)

**Comment by LemADEC** [comment]
Ship mass has no relation with the position issue we're discussing here. If you have another issue in mind please open a different ticket.

**Comment by LemADEC** [comment]
Virtual hyperspace has been introduced early July while fixing global positioning and transitions.
Ship movements costs have full customization support, through configuration file and a forge event.
Since the core issue is fixed, please open new tickets for whatever is left.
