### ISSUE TITLE
Request - control whether or not a ship can land on a planet

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#262]
Hi Lemadec

Any chance youll allow whether or not a ship can land on a planet to be seperate to the dimension hasAtmoaphere flag in celestialObjects?

Primary reason I ask is I'm keen on having some nethers have no atmosphere, but obviously a ship cant land there.

Regards
Bysokar

**Comment by LemADEC** [comment]
Your capacity to land on a planet has no relation with the hasAtmosphere flag.
It's purely defined by whether a dimensionId was provided or not.

**Comment by StargateMC** [comment]
You can't define the atmosphere flag and have it apply to a dimension without having both though?

**Comment by LemADEC** [comment]
then just place the Nether under the overworld like in the default configuration?

**Comment by StargateMC** [comment]
My server uses mod/plugin generated nether dimensions, and many of them. Nether portals are also disabled - stargate travel is required.

This functionality would work for any underground themed world generators though.

Dont want players travelling between worlds by dropping through into the void on another world haha

**Comment by LemADEC** [comment]
if you want worlds that are not attached to current galaxy, you can just create another hyperspace/space dimensions as parent for those worlds.

**Comment by StargateMC** [comment]
Then they won't show up where I want them haha.
I agree thats a good workaround tho

**Comment by LemADEC** [comment]
"Worlds out of this world"

**Comment by StargateMC** [comment]
huh lol

**Comment by StargateMC** [comment]
Just to nut this one out, the goal for this request is/was:

- Config option that has 'warpdriveShipsEnabled' or something similar, which is done per dimension in celestialObjects.
- Message if you try to warp to that planet from space, or jump while on the dimension, which states something like 'The atmosphere on this planet interferes with the ship's warp core... jump aborted'
- (Maybe?) Prevent placement of a Warpdrive ship core on said dimensions, to prevent players wasting resources?

This would allow an underground dimension type (eg: Nether, EpicCaves etc) to be used with WarpDrive for its celestial object rendering and atmosphere control capabilities (And *cough* for MMOCore to pull accurate position info).

Think: http://www.stargate-sg1-solutions.com/wiki/Praclarush_Taonas

Regards,
Bysokar

**Comment by LemADEC** [comment]
you can already use plugins or forge events to prevent placing ship core or moving ship in a specific area or dimension.

**Comment by StargateMC** [comment]
Good point. I'll make a plugin for it.
