### ISSUE TITLE
Hyperspace color config

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#263]
Hi Lemadec
Would you be able to add a config option for modifying the hyperspace dimensions color?

Primary reason I ask is hyperspace is blue in stargate canon.

Regards
Bysokar

**Comment by CaptainMegavolt** [comment]
I agree (although I rather like the red Star Control/Babylon 5 hyperspace),
I would like to see this feature

**Comment by LemADEC** [comment]
Well, the hyperspace coloring doesn't work anyway right now, so let's start by fixing that first :)

**Comment by LemADEC** [comment]
Fixed in dev

**Comment by StargateMC** [comment]
Thanks :)
