### ISSUE TITLE
OC Radar program /scan.lua

### ISSUE THREAD

**Issue by Mace-Windu1** [LemADEC/WarpDrive#264]
I am in single player on a server modpack. It uses the 1.7 branch code as of the 21st of May. I have the default radar program installed. When I try to use /scan.lua it comes up with the error shown below. /ping.lua still works fine. I have tried numerous times and reinstalled the program a few times. I am using a tier 2 server, with tier 3 CPU, graphics card, and HDD, tier 3.5 memory x3, and EEPROM (lua bios). The server is connected to a terminal server and they are connected on the right side of the server rack to a WD Radar.

![wd radar error](https://cloud.githubusercontent.com/assets/21285684/26336929/43491b06-3f2a-11e7-83d7-c424b20bd266.jpg)

**Comment by LemADEC** [comment]
There's an unnecessary "not" in the GPU check for a few LUA scripts. It's fixed in dev.
