### ISSUE TITLE
Players cant warp between hyperspace and space and vice versa

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#267]
Hi Lemadec

Just popping this one here so the issue is tracked.

When a player jumps into hyperspace with the latest code, then end up at the same XYZ coordinates that they were in and not the relative coordinates to the space dimension they were coming from.

The same happens in the opposite direction, when coming out of hyperspace.

**Comment by LemADEC** [comment]
That's #259, the ship transition aren't fixed yet. Same goes with the /space command.
