### ISSUE TITLE
Laser-setup-(advanced) to be splitted with Weapon controller

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#268]
@LemADEC i added some info from the video about advanced laser boosting and *somehow* fucked something up that makes the image just be a image and not the video. i added the info because the video could be unclear for some people (it took me watching more then 2 times til i knew it). can this be fixed (i dont know github tags)

**Comment by LemADEC** [comment]
I've fixed the link, you had removed a " at the end and a [ at the beginning. It's an inception of picture with an hyperlink.

What you've added should be a new separate page for the weapon controller.
Some of the informations are confusing for me:
advanced computer from CC (just computer from OC)
=> you need more than a computer for OC. Refer to the Computer tutorial instead, no need to repeat ourselves here.
(- tuning fork if you run into camera not detected by weapon controller bug)
=> you need to setup the video channels by LUA or by a tuning fork. If there's a bug, open a ticket to get it fixed, no need to make picture of it in the wiki :)
- modem (don't need modem for OC)
=> you only need the "Wired Model" which is quite different from the "Wireless Modem". OC does require wiring too. As above, just redirect to the Computer tutorial page.

**Comment by LemADEC** [comment]
https://github.com/LemADEC/WarpDrive/wiki/Laser-setup-(advanced)

**Comment by ghost** [comment]
i ment if you use computercraft:
you minimally need an advanced computer
and with opencomputers:
just any computer

and with opencomputers you can just connect the "cable" to the devices instead of placing a wired modem and wiring it up or wireless modem and sending singals to it

**Comment by LemADEC** [comment]
ComputerCraft requires an Advanced computers and some wiring.
OpenComputers requires an Tier 2 API,  a Tier 2 screen, an HDD, a keyboard and some cabling.
Either way, the WarpDrive wiki isn't the place to explain how to play with ComputerCraft or OpenComputers, so I want keep those to the minimum.

**Comment by LemADEC** [comment]
Wiki has been largely updated, open a new ticket if issues remain
