### ISSUE TITLE
Need help adding planets.

### ISSUE THREAD

**Issue by BrotheBear** [LemADEC/WarpDrive#269]
Trying to add planets to my config file, but it's constantly erroring when I try to launch the game. 

This is what I'm trying. I originally had overworld size at 20k 20k, and nether at 10k 10k, but then figured that if the nether is starting at 20k it might overlap, so I dropped them down.

But even after trying several different variations I can't get this working. Could you please help?

```
planets {
    # dimensionId, dimensionCenterX, dimensionCenterZ, radiusX, radiusZ, spaceCenterX, spaceCenterZ
    I:overworld <
                0
                0
                0
                19990
                19990
                0
                0
         >
        I:nether < 
                -1 
                0 
                0 
                9990 
                9990 
                20000 
                -40000 
	>
}
```

 Also, would it be possible to have the dimensions all on one line like: 

```
planets {
    # dimensionId, dimensionCenterX, dimensionCenterZ, radiusX, radiusZ, spaceCenterX, spaceCenterZ
    I:Overworld < 0 0 0 20000 20000 0 0 >
    I:Nether < -1 0 0 10000 10000 20000 -40000 >
    I:The End < 1 0 0 5000 5000 -85000 -85000 >
    I:Deep Dark < -150 0 0 5000 5000 45000 -15000 >
    I:Last Millennium < -112 0 0 5000 5000 85000 -85000 >

```

**Comment by LemADEC** [comment]
The configuration format for planet is completely changed for next version and relies on XML files with way more options to configure.

You say having an error but I see no logs or error message in your post, so I'm a bit confused on what you've observed.

Your overworld goes from x -19990 to x +19990.
Your nether goes from x +10010 to x +29990.
Just change the nether center coordinates.

The wiki includes a google doc to help you visualize this configuration.

**Comment by BrotheBear** [comment]
![image](https://user-images.githubusercontent.com/3680588/27265328-777bc664-548b-11e7-9af2-6219498b4b83.png)


... Am I just being a derp and doing this wrong then?

Regarding errors, this is happening. 

![image](https://user-images.githubusercontent.com/3680588/27265327-6b55fe0e-548b-11e7-99ec-4890ea395269.png)


Edit: This is what I'm working with at the moment.

![image](https://user-images.githubusercontent.com/3680588/27265324-515c07be-548b-11e7-9de8-70d3d7cc316c.png)

**Comment by LemADEC** [comment]
oups, forgot to check the Z coordinates too :).

Looks like you've a faulty format in your configuration file.
What does the FML log says? => <modpack folder>/logs/fml-client-latest.log
Can you post those errored files on gist or pastebin?

**Comment by BrotheBear** [comment]
Forgive me, where is the FML log?

**Comment by BrotheBear** [comment]
https://pastebin.com/drjRVG7n

**Comment by LemADEC** [comment]
With a spreadsheet program, you can add new lines with Alt-Enter in formulas.

**Comment by LemADEC** [comment]
```
[23:47:07] [Client thread/ERROR]: An exception occurred while loading config file WarpDrive.cfg. This file will be renamed to WarpDrive.cfg_20170618_234707.errored and a new config file will be generated.
[23:47:07] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.RuntimeException: Malformed list property "/config/WarpDrive/WarpDrive.cfg:538"
```
=> check line 538

**Comment by BrotheBear** [comment]
Does spacing matter much then with the xml? 

![image](https://user-images.githubusercontent.com/3680588/27265437-bb64ce78-548d-11e7-8a2f-459241f04b16.png)

So will this work now?

**Comment by LemADEC** [comment]
I've no idea what's in your line 538, so I can't tell.
I'm pretty sure you need to double quotes names with spaces.

**Comment by BrotheBear** [comment]
Right. It literally WAS just a problem with spacing in the config file. Thanks for all your help it's really appreciated. Especially that excel tip! 

Edit: The spaces in the name don't seem to matter. Just travelled to the last millennium from the overworld! :)

**Comment by LemADEC** [comment]
welcome, have fun with the mod
