### ISSUE TITLE
Hi,emmm,with my help and ladengbt,the chinese language of this mod is finished

### ISSUE THREAD

**Issue by StandAndFight** [LemADEC/WarpDrive#272]
[zh_CN.zip](https://github.com/LemADEC/WarpDrive/files/1167663/zh_CN.zip)

**Comment by LemADEC** [comment]
Excellent, thank you!

**Comment by LemADEC** [comment]
I'll merge it and send it back so you can check the new added stuffs.

**Comment by LemADEC** [comment]
Here's the merged file, please check the newly added lines in English.
[lang.zip](https://github.com/LemADEC/WarpDrive/files/1201775/lang.zip)

**Comment by ETStareak** [comment]
Well,I just checked his translate and found that it is translated by baidu translate.It's not a correct translation.I'm translating your newest en_US.lang and will finish it soon.Please don't use    this zh_CN.
I'm the translater of GC4,my translation won't bad.

**Comment by LemADEC** [comment]
Thanks, keep it up!

**Comment by LemADEC** [comment]
Merge done with current state. Make a new pull request as you move further!
