### ISSUE TITLE
World Cant be created

### ISSUE THREAD

**Issue by jhammerberg** [LemADEC/WarpDrive#278]
Hi, Im trying to get the new warpdrive 1.3.34 Beta to work (The official one from curseforge) but when I try to create a new world my game crashes and says there was a out of bounds error...

https://cdn.discordapp.com/attachments/102776848185847808/347389551184052234/crash-2017-08-16_10.41.19-client.txt

PS: anyone whos having this problem I downloaded fastcraft and things seem to be working.

**Comment by LemADEC** [comment]
I can't reproduce the issue and you crashreport link is no longer valid.
Please provide a new crash report.

**Comment by LemADEC** [comment]
No updated for 1 month, assuming fixed
