### ISSUE TITLE
open computers, enantiomorphic reactor, and latest warp drive

### ISSUE THREAD

**Issue by KyeDuo** [LemADEC/WarpDrive#279]
I get the following error when I try to use the enantiomorphic reactor and open computers
[pic](https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/20799489_1509150232480042_4223876311631750440_n.jpg?oh=a72592802eb2544c02406f7fa823906b&oe=59EF730B)
I have tried on a new world with a fresh setup and get the same thing.

**Comment by LemADEC** [comment]
As of 1.3.31 and later, you need to install OC scripts as they won't autoboot anymore, as request by OC support.
