### ISSUE TITLE
autojumping, maybe

### ISSUE THREAD

**Issue by KyeDuo** [LemADEC/WarpDrive#282]
I have found that if you reboot and OC computer during the cooldown phase, something will cause the ship to jump again once it can.
I haven't tried restarting the program via the replace screen trick yet, but the above will cause it to jump every time
I am using the latest OC, Forge, and WD
the ship is 10x9x5, using just white basic hull blocks, white glass hull blocks, white basic omnipanels, energy air field blocks, two basic air generators, superior subspace cap, IC2 HV cable for power distribution
T3 computer with Diamond CPU, 3.0 RAM, Diamond HD, T3 Graphics card, T3 Screen, keyboard
I also have quite a few other mods, I can get a list if you need it.

**Comment by LemADEC** [comment]
The ship core cool down always takes priority.
Once the core is cooled off, the next jump engages if the controller is enabled with a jump command.

Auto-summon will force enable the controller at boot.
Boot sequence will force the current mode to 'IDLE', which is not a jumping command.
So it might be related to the 'auto-summon' option, through I'm not sure how or why yet.

**Comment by KyeDuo** [comment]
I will check that setting to see if that causes a different behavior.

**Comment by KyeDuo** [comment]
ok, observations:
summon does indeed cause the OC to autojump the ship if you reset the comp while in core CD, while having it off does not. The computer does have to finish rebooting before the core is out of CD.
however, if you leave the ship before the computer finishes rebooting, the ship will not start the jump until you get back on and access the controls section of the program.
Btw, is the summon portion working? I was just outside my ship on planet testing this out with the summon active and it didn't warp me inside the ship after it jumped. Is it supposed to or am I misunderstanding what that is supposed to do?

**Comment by LemADEC** [comment]
tk for the update

Autosummon only goes up to 256 blocks or so, in same dimension. I suspect there's a bug where it'll only summon after cool down has expired, hence the feeling that it's not working.

**Comment by KyeDuo** [comment]
My ship was only jumping 25 blocks on planet. I suspect that it won't summon because the comp doesn't get properly loaded after jumping so it never has a chance to summon.

**Comment by LemADEC** [comment]
with OC, I don't expect summon to work

**Comment by KyeDuo** [comment]
interesting behavior of OC, if you remove the screen the program stops working and the computer goes to the command line. I half think OC doesn't like it when you remove a screen with a program that updates the screen constantly.
tried to use a server as the controller and it wouldn't even recognize the warp core as attached, even with network cables. I probably can't use the server to control the ship.

**Comment by LemADEC** [comment]
OC server rack works just fine by me. You may have a network misconfiguration?
![image](https://user-images.githubusercontent.com/4776032/30218865-9066ab20-94ba-11e7-9422-3a9dc616b85b.png)
![image](https://user-images.githubusercontent.com/4776032/30218906-b3bd6df2-94ba-11e7-8b25-3c44ba45bdfc.png)

**Comment by KyeDuo** [comment]
I'll have to try that setup...I had my server like my comp, straight against the controller. didn't think to go through the screen. It could also be some crazy mod interference, I do have _quite_ a few mods.
edit: ok....now the server is working fine, and now I can get the remote terminal to work....gotta love heavily modded MC. :P

**Comment by LemADEC** [comment]
Any update on this?

**Comment by LemADEC** [comment]
No update for 4+ weeks.
Crew teleportation will be removed once Transporter room is stable.
OC specific issues are already reported in #265.
