### ISSUE TITLE
Cannot resolve position of celestial object from another mod

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#283]
Hi Lemadec,

Your new celestial objects are fantastic, but another mod cannot (without reflection) at least read from the position of a celestialObject.

Can you please release a version to curse with parent posX/Z exposed, either via a readonly method or directly?

Kind Regards,
Bysokar

**Comment by LemADEC** [comment]
You want to read the parent position, not just the universal coordinate?
What's the use case for that?

**Comment by StargateMC** [comment]
Universe coordinate?

And knowing where a planet is in a space dim and where space dims are in a hyperspace allows me to calculate positions accurately.... otherwise I have no idea if im orbiting a celestial or not... the only method available atm provides the nearest one.

Just trying to translate my mod to work with your official build is all.

Bysokar

**Comment by LemADEC** [comment]
CelestialObjectManager has a method to give you if you're orbiting a planet. I'll have to check later on what's the exact name for it.

**Comment by LemADEC** [comment]
CelestialObjectManager.getClosestChild() gives you the closest child celestial object. It can be null if there's no child at all.

ICelestialObject.getAreaInParent() gives the coordinates of the given celestial object inside it's parent. You are in orbit if you're within that X and Z area. Y is forced to 0-8, so you might want to ignore it.
You can deduce the center from it if needed.

I'll probably add a CelestialObjectManager.getOrbitingChild() to simplify that.

**Comment by StargateMC** [comment]
I'm going to create a server side only mod with the coordinates exposed or use reflection then, the numbers are available and I don't see additional calculations should be required.. using aabbs etc.

**Comment by LemADEC** [comment]
StarMapRegistry.getUniversalCoordinates() gives you the universal/global coordinates of the object, given it's current coordinates inside a Celestial Object.

AABB are not cached currently because they're only used very intermittently (when ship is landing/taking off notably).

If you still a fix, we'll need a proper use case to address your issue.

**Comment by LemADEC** [comment]
Any update on this? What's the actual use case?

**Comment by LemADEC** [comment]
No update for 2 months, assuming fixed
