### ISSUE TITLE
Mainframe block

### ISSUE THREAD

**Issue by JohnNemECis** [LemADEC/WarpDrive#286]
At this moment a ship controller and a ship core is the only thing capable of being in the same network. It would be cool if all things could be connected to one and the same network. than you could add permissions, rights and restrictions to players. 
It would also add that there wont be a mess of a million computers around, one for each system. 
next to that, it would let you easy manage around in the ship, and let a captain sit in his easy chair while looking at one monitor.
next to this, it would make it a lesser pain to name every system, as for you know, reactor is reactor, lasers are weapons, and navigation is navigation

**Comment by LemADEC** [comment]
You can already connect all blocks in the same computer network and control them with your own LUA scripts.
The provided scripts are already prebuilt to that effect, and it takes minimum effort to merge them.

In practice, such single computer approach is raising performance issues on OpenComputers and makes the reactor fairly unstable.

**Comment by LemADEC** [comment]
No response for response, assuming it's already addressed.
