### ISSUE TITLE
A Little help?

### ISSUE THREAD

**Issue by Maolink** [LemADEC/WarpDrive#288]
So i built a pretty big version of the Starship Enterprise (9442 blocks in total). I programmed the ComputerCraft computer just fine, but whenever I try to jump(my ship, that is), a message pops up in chat saying that my ship stretches across too many chunks, and that the max is set to 25. I want to know if theres a way to extend the max chunks, and if so, how to do this. Thanks!

**Comment by LemADEC** [comment]
What version are you using?
Have you read the full message? what does it say exactly?

**Comment by Maolink** [comment]
i am using warp drive version 1.7.1 and the full message says: "Ship is extending over too many chunks in source world. Max is currently set to 25 in forgeChunkLoading.cfg." Thanks for your help!

**Comment by LemADEC** [comment]
there's no such version as 1.7.1, check exactly the full version number.

As the message says, you need to modify the forgeChunkLoading.cfg file

**Comment by Maolink** [comment]
I know what the message says, i need to know how to access that file

**Comment by LemADEC** [comment]
it's in the "config" folder, next to the "mods" folder
