### ISSUE TITLE
broken Enamorphic reactors

### ISSUE THREAD

**Issue by JohnNemECis** [LemADEC/WarpDrive#289]
There are two points im going to point out. this will also be in the way I see priority in it.
       1. (Latest Beta) The Enamorphic reactors are bungeejumping at stability. When I have a reactor now, it can drop down to maximally 50% and then it will start reaching 100% without any need of lasers, and it doesnt create enough energy. This will be a problem when your Enamorphic reactor is the ships main energy supply.
       2. (Any version) There is a big problem with the maximum output of the reactor. When you set it to unlimited, the maximal, or at least at my pc, is 4300 rf/t and it doesnt matter what conduit. I use Cryogenic energy pipes, and the issue persists. Can you please check why this is, and if it is not ment to be that way, can you please fix it?

**Comment by LemADEC** [comment]
The equation hasn't changed for more than a year. I've only fixed the invalid output rate.
Stability goes back to 100% when the core is starving, typically when you're pulling too much power from it.

The maximum is limited by your output connection. I typically use it with more than 40k RF/t output rate.

**Comment by JohnNemECis** [comment]
That was the problem. The reactor output was fixed and the energy was gone. Thanks for the help. I thought it was a bug.
