### ISSUE TITLE
Planets not getting created in space dimension?

### ISSUE THREAD

**Issue by soccermitchy** [LemADEC/WarpDrive#290]
Hey, when I try this configuration to get planets to show, none of the planets actually show up in the space dimension, even after deleting the files for the dimension in the `world` folder (`world/DIM-2`). How would I fix this? Here's the configuration that I'm using:
```
planets {
    # dimensionId, dimensionCenterX, dimensionCenterZ, radiusX, radiusZ, spaceCenterX, spaceCenterZ
    I:moon <
        -28
        0
        0
        4000
        4000
        7000
        1000
     >

    # dimensionId, dimensionCenterX, dimensionCenterZ, radiusX, radiusZ, spaceCenterX, spaceCenterZ
    I:overworld <
        0
        0
        0
        100000
        100000
        0
        0
     >
}
```

**Comment by LemADEC** [comment]
Update to latest version, the configuration no longer works that way

**Comment by soccermitchy** [comment]
As far as I know, I'm on the latest version for 1.7.10 (`1.7.10-1.3.29.-`, and yes that does include the `.-` at the end according to forge's mod list, apparently)... any way to fix it on this version? Can't really upgrade the pack to a newer minecraft version since we are playing with some mods that never got ported to anything newer.

**Comment by LemADEC** [comment]
Your 2 versions behind: https://minecraft.curseforge.com/projects/warpdrive/files

**Comment by soccermitchy** [comment]
Ah, ok. Thanks, I just grabbed the latest one marked 'Release', I'll upgrade later today when I get a chance and try it.
