### ISSUE TITLE
Camera View Point Error

### ISSUE THREAD

**Issue by mzldh** [LemADEC/WarpDrive#291]
![2017-09-13_17 52 31](https://user-images.githubusercontent.com/19243430/30407349-9f56488e-98ac-11e7-87ab-fed4d632e8a4.png)
![2017-09-13_17 49 19](https://user-images.githubusercontent.com/19243430/30407350-9f5748c4-98ac-11e7-94ba-9b794fd8e805.png)
![2017-09-13_17 49 33](https://user-images.githubusercontent.com/19243430/30407351-9f57e9f0-98ac-11e7-95fc-1d6745d16e02.png)
![2017-09-13_17 52 25](https://user-images.githubusercontent.com/19243430/30407352-9f5886a8-98ac-11e7-9467-497558f28280.png)

As the image shows, the there is a serious bug on the views provided by the camera, which basically makes the whole laser cannon system unuseable....
hope to have it fixed soon!

**Comment by mzldh** [comment]
mod version is 1.3.34

**Comment by LemADEC** [comment]
This is known intermittent glitch in vanilla rendering. Reopen the monitor to fix it.

**Comment by mzldh** [comment]
Oh no, it didn't help with opening the monitor, even rebooting the pc didn't help.
on the camera the glitch was intermittent, only happens at tiems but on the laser camra it becomes that once you fire the laser and could never get back normal.

other mods with remote canmeras such as security craft never had that issue.

**Comment by LemADEC** [comment]
Rebooting your game or the PC will not help.

**Comment by mzldh** [comment]
yes it didn't help, but reopening the monitor also didn't help... I turned off the monitor's power multiple times didn't help at all

**Comment by LemADEC** [comment]
Try forcing a block update in the chunk where the camera is located?

**Comment by mzldh** [comment]
No, didn't work. for the camera it isn't an issue, you can fix it by block update or reopening monitor, but for the laser camera it doesn't, and gets like that when ever you shoot a laser out

**Comment by mzldh** [comment]
Also another thing to mention, I belive this bug is not caused by other mods considering it is still happening after I took away all the other mods except for WarpDrive, ComputerCraft and IndustrialCraft. I even took away mods like FastCraft and OptiFine.
Please dp try out WarpDrive-1.7.10-1.3.34. and see for it if you have time, Thank you!

**Comment by LemADEC** [comment]
It's a vanilla/forge bug. For some obscure reason, it's rendering the block with the wrong renderer.

**Comment by mzldh** [comment]
would having a diffrent forge version help? i'm currently using the latest version of 1.7.10 V10.13.4.1614

**Comment by LemADEC** [comment]
by "obscure reason", I mean we don't know what's causing it to appear and we don't know where to look for the source of that issue.
If you can find a forge version or mod that change that faulty behavior, we could look for a proper fix.

**Comment by LemADEC** [comment]
Actually, I was confused by it working when it shouldn't, my bad
