### ISSUE TITLE
Ship disappearing in LAN

### ISSUE THREAD

**Issue by Mrphelsky** [LemADEC/WarpDrive#297]
I am having some trouble when playing with friends. Whenever I exit the world and get back on, my ship disappears and i am stuck in outer space and die. If i get off the world and get back on right away, my ship is there, but my friend's are not. If i do not get off and back on right away then my friend's ships are there but mine is not.
This is very frustrating on a multiplayer survival world, is there some way to prevent it from happening? Thanks for your time in reading this.

**Comment by LemADEC** [comment]
What version of the mod are you using?
What other mods are in the modpack?
How do you find your ship back? Where did it go?

**Comment by Mrphelsky** [comment]
I am using version 1.3.34 of WarpDrive. I am also using Matter Overdrive, Mekanism, Solar Flux, Thermal Dynamics/Expansion/Foundation, Extra Food, CoFHCore, and Optifine and Fastcraft.
As to where the ship is going, I was hoping you could tell me.
When I first boot up Minecraft from the launcher and log into my world, the ship is just gone. I am at the coordinates, and I can even use the command to find the ship and teleport to those exact coordinates, but it's just gone. 
Then I log off of the world and get right back on without exiting Minecraft, and my ship is back.
The bug is reversed for the players joining my world.
So whenever my ship is gone, their's aren't, and when their ships are gone, mine is not.

**Comment by LemADEC** [comment]
Send your server files with logs, mods, config and saves

**Comment by Mrphelsky** [comment]
I would but unfortunately I left the state today and won't be back until
Saturday or possibly later. When I get back i will send them. Also, I do
not use a server, i am on a single player world that I "open to LAN" from
offline using a wired Ethernet connection conecting my computer to the
other two,

**Comment by LemADEC** [comment]
Any update on this?
Can you send your world save too?

**Comment by Mrphelsky** [comment]
​
 Space.zip
<https://drive.google.com/file/d/0B7PwlZ-4tZ6_Y2tYNGpzV0RRX0k/view?usp=drive_web>
​Alright finally back from my trip, here is the world save. I am afraid I
do not know what you mean by server files because this is just a single
player world opened to LAN on a wired, offline ethernet connection.

**Comment by LemADEC** [comment]
Please send the whole modpack folder then

**Comment by Mrphelsky** [comment]
​
 mods.zip
<https://drive.google.com/file/d/0B7PwlZ-4tZ6_dVJlR2wwMlROZkE/view?usp=drive_web>
​Heres the mods.

**Comment by LemADEC** [comment]
I really mean the whole modpack, not just the mods folder.

**Comment by Mrphelsky** [comment]
I probably sound stupid but... What is a mod pack if not the mods I use
with the world? This is everything I use when I play on the world.

**Comment by freznelfennec** [comment]
The entire game directory.  If you are using the vanilla launcher, the entire .minecraft folder.

**Comment by freznelfennec** [comment]
This way he can go over any logs, and look at other info specific to your mod loadout.  The mods folder  itself is useless without the configs and forge version anyways.

**Comment by Mrphelsky** [comment]
Ok, sorry for the delay but internet at my house is sketchy at best and
this is pretty large.
 minecraft.zip
<https://drive.google.com/file/d/0B7PwlZ-4tZ6_R090ZHRRMEhDT2s/view?usp=drive_web>
​

**Comment by LemADEC** [comment]
Have you started that world with WarpDrive 1.3.34 or did you use an older version initially?
Do you still have the logs, I can only find latest.log in there?

**Comment by LemADEC** [comment]
Looks like a SSP bug in Forge, I'll add a workaround for next update

**Comment by Mrphelsky** [comment]
Thank you! Great mod, by the way.
