### ISSUE TITLE
Air generator revamp

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#30]
Air generators are still lag machines for client, making them pretty much useless in SMP.
Option 1: use a progressive floodfill, probably with an indirect storage.
Option 2: tweak the existing so it doesn't requires constant updates

**Comment by CaptainMegavolt** [comment]
It would make more sense if air generators, instead of having a fixed radius, would just slowly flood fill an area of any size with air, like pressurizing an area. The larger the area pressurized, the more energy the air generator uses per tick. If you have multiple air generators throughout the area, the workload will be distributed among them.

**Comment by TheNumenorean** [comment]
The problem with that approach is that it requires calculating the volume of an area, which would be really laggy, and probably storing that data somehow, resulting in even more overhead. It also has the danger of attempting to fill up all of space with air, and detecting block changes would still be really laggy.

**Comment by CaptainMegavolt** [comment]
Calculating volume was not the intent, it was more of a system where each air block would detect for open space adjacent to it and attempt to fill that space with more air blocks. The power usage would be calculated by how many contiguous air blocks were connected to an air generator, and the power load distribution would be accomplished by a similar means in which each air generator would look to see if there was another air generator contributing to its air bubble.

**Comment by LemADEC** [comment]
Galacticraft tried the fill approach for several years now and it's still works 'when it wants' while lagging the server. It's CPU usage scales exponentially with the number of air generators covering an area.

The current implementation in WarpDrive will progressively increase presure in an area, progressively loose in case of 'leaks'. It's CPU usage only scale linearly with the number of unstable blocks (leaking and growing area), hence allowing players to spam an area with air generators without killing the server.
Eventually, we'll revisite our current implementation, but right now it already works and scales better than Galacticraft, so I don't feel the urge to change it further.

**Comment by CaptainMegavolt** [comment]
Ohhh... okay then. It seems that what you are currently doing is almost exactly what I wanted. I just figured that it could be able to fill a larger area.

**Comment by TheNumenorean** [comment]
"where each air block would detect for open space adjacent to it and attempt to fill that space with more air blocks" = exponential lag.

**Comment by CaptainMegavolt** [comment]
Ok...
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

_--Supernova Industries Supreme Chairman Megavolt_

**Comment by LemADEC** [comment]
This was actually fixed in https://github.com/LemADEC/WarpDrive/commit/42843ff1682971f0808ff09468e925b92a8505b3
