### ISSUE TITLE
Ship builder drops content of IC2 reactor

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#300]
As of  1.3.34, IC2 reactor chamber content gets dropped by ship builder. Jump is fine, including rotation.

**Comment by LemADEC** [comment]
Fixed in dev

**Comment by nonenothing** [comment]
>Jump is fine

Wrong.
In last version long jump (unload/not generated chunk maybe) drop everything.
Another warpmod with same bug, haha.

**Comment by LemADEC** [comment]
That issue is fixed and was tested on the official server through more than 5k jumps.
If you have an issue, open a new tickets with details including mod version, logs and setup.
