### ISSUE TITLE
Server thread/ERROR Warpdrive Server world Overworld block updating... while chunk isn't loaded!

### ISSUE THREAD

**Issue by FourGigaquads** [LemADEC/WarpDrive#301]
Hello. I recently put together a server and the fml-server-latest.log is being spammed with the following error message with different times and coordinates.

> [22:43:01] [Server thread/ERROR] [WarpDrive/]: Server world Overworld block updating at (1122 69 873), while chunk isn't loaded!

I do have some problems with the server crashing currently, but I'm still working out the bugs. Seeing this in the log though, I'm concerned this may be unexpected behavior. Do these errors indicate an issue that needs to be fixed or are they pretty innocuous?

[fml-server-latest.zip](https://github.com/LemADEC/WarpDrive/files/1497667/fml-server-latest.zip)

Thank you!

**Comment by LemADEC** [comment]
In the next version it'll dump all threads so you can find the mod causing faulty block updates during world generation. It'll also allow to disable the log altogether, see 7c2dab4aed0849636dbd5ba8b152e5d9caf03244

There's also a workaround for forge event sequencing that's included in next version.
Either way, doing a pre-generation of the world is strongly advised and will save you lots of pain.
