### ISSUE TITLE
DraconicEvolution support

### ISSUE THREAD

**Issue by limmers2015** [LemADEC/WarpDrive#302]
I am trying to power a ship with a DraconicEvolution tier 4 EnergyCore. I have a working and verified power conversion setup from RF to EU. Every time I move the ship, I have to break and replace the core, losing almost 10 billion RF. Is there something that you can do to fix this, or something that you can tell me to do? Thanks

P.S.     I can't and won't update to a higher minecraft version. And I'm playing a custom mix of forge mods. If the info on them is needed to solve this, I can find that too.

Thank you again.

**Comment by limmers2015** [comment]
Sorry about the incorrect placement. I'm new to github, and I don't really know my way around.

Here's the list of mods I'm using:
![mods list](https://user-images.githubusercontent.com/34211966/33527786-bb3cf964-d824-11e7-9cc2-a24d4a223233.png)

And that's great but odd news about the supported energytypes. I tried with this exact file 6 months, 11 days ago, and it wouldn't have anything to do with RF. I had to get Industrialcraft to make it work. Thanks for the great news! The setup for conversion I have is kinda clunky.

It's:
Energycore to Energypylon
Energypylon through galacticraft heavy aluminum wire
Said wire to the input on a Superior capacitor
Superior capacitor to Sealable Glass fiber cable.
Cable to rest of ship

Glad to see that I can scrap that mess!

Thanks for taking the time to help me with this. Warpdrive really is a great mod, despite a few internal flaws and compatibility issues.

**Comment by LemADEC** [comment]
RF support requires the CoFHCore mod.
You should update WarpDrive to latest 1.3.34.
What internal flaws and compatibility issues are you referring to?

**Comment by limmers2015** [comment]
I see about the CoFHCore. I'll try. I will also look for the 1.3.34 mod version. Any problems just swapping it out for the one I have?

And as far as flaws and compatibility issues... Well:

Armor Stands and other freestanding blocks with specifically assigned sides don't turn with the ship, causing a few problems when using Galacticraft advanced solar panels and other things like that.

It is somewhat incompatible with Draconicevolution. (Energycores for starters)

I don't know which of these have been fixed, but I will update this list when I find out what is different in 1.3.34.

Thank you again for your help.

**Comment by limmers2015** [comment]
UPDATE:
I've tried the newer version of Warpdrive. Nice interface changes but still the same problems with both the aforementioned freestanding blocks and the Draconicevolution Energycore. 
Any suggestions? I can change the config, but I don't know what to do to make it work. May I suggest that if you do know, you simply paste in a config text duplicate here and modify before posting? Then I can just copy it and paste into my config. Just a thought. If the Energycores just won't work then I can use something else... I just means restarting my ship form scratch to incorporate it. I am going to stick with the updated Warpdrive though. Some of the interface changes are just what the mod needed. Genuis!

**Comment by limmers2015** [comment]
Do you want me to enable advanced jump debugging and jump with core onboard, then send you result? Maybe it'll help to see what's wrong.

**Comment by LemADEC** [comment]
DraconicEvolution compatibility module doesn't exist yet, you're the first one to request it. You can help by building a reference ship with all the blocks from that mod.

GalacticCraft compatibility should already work, please list the blocks that cause issues.

Which armor stands are you referring to?

**Comment by limmers2015** [comment]
In this case, the ones from TravellersGear.

**Comment by limmers2015** [comment]
The Galacticraft Solar Panels are: GalacicraftCore:tile.solar (I.D. 0511)

**Comment by limmers2015** [comment]
And by "a reference ship with all the blocks from that mod", do you mean that I literally build something with functioning variants of every Draconicevolution machine and block on it and then do... what with it?

I will gladly do my best to help in the construction of a compatibility module. I am just unsure of what to do. I also warn you that I have a lot of other things going on in my life, so a complete testing ship may take awhile. I will do my best though.

On another note, will I need to get a copy of the "reference ship" world to you? And if so, how do you propose doing that? I have some ideas, but I'll wait to see what you say before proposing them, in case they are completely irrelevant.

**Comment by limmers2015** [comment]
Maybe I can use e-mail if the file isn't too big. I've got worlds anywhere from 8.4 megabytes (within e-mail limits) to 150 megabytes (well outside of the 30mb limit).

**Comment by limmers2015** [comment]
On another note, now that this is turning into a compatibility module production discussion, should it be moved to projects? And maybe a name change to "Draconic-Evolution Compatibility Module Production" or something like that? Just a thought.

**Comment by LemADEC** [comment]
The ship needs to be a large stone platform with all multi-blocks formed, and good variations.
For example, with stairs, you want to have 4 rings: inner bottom, inner top, outer bottom, outer top variations. With doors, you want to have the 4 position open and closed, so 8 in total.

You can just upload the result on Dropbox or something alike.
Depending how the mod is coded, it can be fairly quick to implement the compatibility.

**Comment by limmers2015** [comment]
Is it a problem if the platform is made of superior hull instead? I can change it, but it'll be a LOT of work.

**Comment by LemADEC** [comment]
it's fine

2017-12-05 2:14 GMT+01:00 limmers2015 <notifications@github.com>:

**Comment by limmers2015** [comment]
Do you need each tier of energy storage multiblock?
If not then it is basically done.

**Comment by LemADEC** [comment]
make the smallest and the biggest one, just in case

**Comment by limmers2015** [comment]
Ok then. I'll check the world over one last time, but I think it's done.

**Comment by limmers2015** [comment]
Here's a [link](http://www.mediafire.com/file/7sxo8enl1ou8jne/Draconic_Evolution_Compatibility_Minecraft_ALL_FILES.zip) to it. Just unzip and dump folder contents into an empty Minecraft directory. It's a full boot-able copy, so all of the mods are in there, as well as the world itself. Sorry if that isn't the most efficient way to do it, but it's by far the easiest on my end. If there's anything that needs changing, or the file doesn't work, just tell me here, and I'll fix it ASAP.

Thanks again for working with me on this.
