### ISSUE TITLE
LibVulpes incompatible with Galacticraft and WarpDrive

### ISSUE THREAD

**Issue by jack0700** [LemADEC/WarpDrive#303]
I was playing around in space and realized that the anti-gravity was not working properly there. I was wondering if there was a possible fix for this. Sorry about bothering you. If this helps I was using these mods in addition to warp drive: 

4space 
Additional Pipes 
Advanced Rocketry 
bdlib 
Biblio Craft 
Big Reactors 
Binnies Mods 
Build Craft 
Build Craft Additions 
Build Craft Compatibility 
Carpenters Blocks 
Chicken Chunks 
Chisel 
Code Chicken Core 
CoFH Core 
Computer Craft 
Damage Indicators 
Decocraft 
Dense Ores 
Enchiridion 2 
Ender Storage 
Ender Tech 
Engineers Toolbox 
Eureka 
Factorization 
Fast Craft 
Forestry 
Galaticraft Core 
Galaticraft Planets 
Gendustry 
Advanced Generators 
Gravel to Flint 
In Game Wiki 
INventory Tweaks 
Iron Chests 
JABBA 
Journey Map Unlimited 
LibVulpes 
Mariculture 
mcjty lib 
MicDoodle Core 
Minechem 
Mine Factory Reloaded 
Nei Addons 
Nether Ores 
No More Recipe Conflict 
Not Enough Items
Open Blocks 
Open Computers 
Open Mods Lib 
Pneumatic Craft 
Pressure Pipes 
Rail Craft 
Redstone Arsenal 
rftools 
Simply Jetpacks 
squidless 
Steves Carts Steves Factory Manager 
Steves Workshop 
Storage Drawers 
Thermal Dynamics 
Thermal Expansion 
Thermal Foundation 
Translocator 
Waila 
Waila Harvestability 
WarpDrive 
Witchery

**Comment by LemADEC** [comment]
Which space dimension are you referring too?
What version of the mod are you using?

**Comment by jack0700** [comment]
The warp drive space dimension, and I am using version 1.7.10-1.3.29.

**Comment by LemADEC** [comment]
Latest is 1.7.10-1.3.34...

**Comment by jack0700** [comment]
I have updated now and gravity is still not working, any suggestions on how to fix it? Again sorry about bothering you.

**Comment by LemADEC** [comment]
send your logs and modpack

**Comment by LemADEC** [comment]
Is it intermittent from one game to another?

**Comment by jack0700** [comment]
No, the gravity not working is consistent across all worlds. Also the logs can be found [here.](https://www.dropbox.com/home?preview=Resources.zip)

**Comment by LemADEC** [comment]
This link is only valid for your drop box account, please check

**Comment by jack0700** [comment]
Sorry about that, I was in a rush and didn't check to see if I had properly created a link.  Hopefully it should work [now.](https://www.dropbox.com/s/czgksi4v6wqcpin/Resources.zip?dl=0)

**Comment by LemADEC** [comment]
ok, that one worked.
Your Bibliocraft mod wasn't downloaded properly, you want to reinstall it.
Your WarpDrive configurations are outdated, you can regenerate them by deleting the related configuration folder.
LibVulpes / AdvancedRocketery is interfering with both Galacticraft and WarpDrive. That mod is 'unstable' on 1.7.10, so we have no interest in patching it for now.
Regarding Galacticraft and WarpDrive compatibility, it'll mostly work, thought you may get some side effects.
