### ISSUE TITLE
Game crashing on startup

### ISSUE THREAD

**Issue by noicknoick** [LemADEC/WarpDrive#304]
Here is the crashlog:
[crash-2017-12-05_18.29.35-client.txt](https://github.com/LemADEC/WarpDrive/files/1530075/crash-2017-12-05_18.29.35-client.txt)

My first response was removing IC2 classic, and now it boots. But idk why that was crashing it, seeing as though there are other options for power generation and the like.

**Comment by LemADEC** [comment]
Your version is obsolete. Updated to 1.3.34, as found on CurseForge.

**Comment by noicknoick** [comment]
Shit, sorry. I thought I dl'd the most recent version.

Thanks, and sorry for wasting your time.
