### ISSUE TITLE
Warpdrive isn`t work with MCAuthenticator

### ISSUE THREAD

**Issue by Noire86** [LemADEC/WarpDrive#305]
Yep, that`s the issue.

Wardprive ships are unable to jump, while MCAuthenticator is installed. When jumping, this message appears: 

JumpSequencer/1177801404 '346fb388-5379-4ce1-b709-43ed39366cb7:0a-7046-4d63-a0ae-1c0e9ed57846' @ 'DIM223' (4834 79 4681) #5 Killing jump sequencer... (Ship is entering a protected area at (4833 83 4678)
Not enough space after adjustment, jump aborted!)

NO MATTER if I`m trying to jump in other world, region or area. This happens in every world I have.

Removing MCAuthenticator solved the issue, but this is unacceptable way. It looks like MCAuthenticator offers Warpship to authenticate, because, if the player logs in, he can`t move or do something before he acquires 2FA code. So I think, MCA recognizes Warpdrive fakeplayer as a real one. But these are just my thoughts.

Thank you in advance!

**Comment by LemADEC** [comment]
The message says "Ship is entering a protected area at (4833 83 4678)", which means a plugin is rejecting the block change in the given location.
Looks like MCAuthenticator refuses to consider the FakePlayer from WarpDrive.
That plugin needs to add whitelist on all FakePlayers or provide a whitelist option.
Other plugins like LoginSecurity and WorldGuard are supporting this just fine, so it's clearly an issue on the plugin end, not the mod itself.
