### ISSUE TITLE
WarpDrive Planet ADDING

### ISSUE THREAD

**Issue by Piouspoppy41355** [LemADEC/WarpDrive#307]
So im trying to help a owner who i play with on a mod pack with warpdrive inside add planets we are both coming up stumped and are very much lost if anyone could help explain on how to do this would be awesome (sorry if i posted this in the wrong spot don't use GitHub to often)

**Comment by LemADEC** [comment]
What version are you using?
Have you checked the celestialObjects-default.xml file?

**Comment by Piouspoppy41355** [comment]
NVM we managed to figure it out once we updated to the latest version TY for your help :D
