### ISSUE TITLE
Hydrogen and Ion Thrusters.

### ISSUE THREAD

**Issue by razorethan** [LemADEC/WarpDrive#308]
On my private server, I have found that while playing with friends the mobility with warp drive is quite difficult. I think we need to add another way of moving ships. For example, the warp core could be added to go large distances in seconds, while thrusters like hydrogen thrusters or ion thrusters could be implemented to let ships travel slower, without cooldowns and the need for blocks to teleport to make the ship move. Another example would be the blocks could actually move and perhaps even ships could roll and go upside down with this new movement system. This makes it so block copying and being placed somewhere else could be something that the warp core could only do. Ion thrusters would be for slow acceleration, but with less of a cost, but hydrogen thrusters could consume hydrogen and speed up faster allowing the ship to move fluently without any block teleporting. This can be done as seeing that Galacticraft space stations have thrusters that spin the blocks in place when the player isn't on them and it isn't considered an entity. This system could be expanded on and applied to warp drive. Another example would be Archimedes ships even though you can't stand on them and have to assemble the ship into an entity I feel like this could be fixed and expanded on so it doesn't turn into an entity and allows you to stand on it. Also, you wouldn't need to "assemble" the ship. Hydrogen could be directed to the hydrogen thrusters using pipes and RF would be needed to charge positive ions for the ion thrusters. Again this would change warp drive forever and may even get it some more popularity and reviews on youtube. Finally, the system could all be connected to the advanced computer or open computer using computer craft's networking system or open computers and the computer would show acceleration and power for them and also have a check system to detect new thrusters applied. Atmospheric thrusters would also be needed to leave the planet without warp drive and stay in the atmosphere. They also will require hydrogen. This is a request/addition to the mod. Feel free to edit any of the ideas here and start out small. You can even get rid of some things, but I really think this could improve Minecraft and space travel as a whole.

**Comment by LemADEC** [comment]
Thanks for your suggestions.

FlyBy is already part of the roadmap, check existing issues.

Archimedes ships and assimilated mods are limited to 2k blocks. WarpDrive supports more than 10 times that. You can't merge both techniques without rewriting the whole game engine, which nobody have time to do and maintain.

GalacticCraft doesn't rotate blocks, it just spins the background image. It's a nice trick but doesn't compare to actual free rotation of ships. The whole point of WarpDrive is to have multiple ships flying and fighting next to each other.
