### ISSUE TITLE
IC2 reactor drop content after jump

### ISSUE THREAD

**Issue by nonenothing** [LemADEC/WarpDrive#309]
After long (400 for instance) jump multichamber reactors drop contents of chambers - not every time but frequently.

Installed mods:
AcademyCraft-1.0.6.jar
BiblioCraft[v1.11.7][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CodeChickenLib-1.7.10-1.1.3.138-universal.jar
ComputerCraft1.75.jar
ExtraPlanets-1.9.4.jar
Galacticraft-Planets-1.7-3.0.12.502.jar
GalacticraftCore-1.7-3.0.12.502.jar
GraviSuite-1.7.10-2.0.3.jar
industrialcraft-2-2.2.827-experimental.jar
LambdaLib-1.2.3.jar
MicdoodleCore-1.7-3.0.12.502.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
WarpDrive-1.7.10-1.3.35.-.jar

Some logs:
https://pastebin.ca/3961420

**Comment by LemADEC** [comment]
I can't reproduce it.

Try with only ComputerCraft, IC2 and WarpDrive.
Also share some picture/description of your setup.

**Comment by nonenothing** [comment]
Here is mods, config and world:
https://files.fm/u/6hm3rx8f
Try ship where you are - one of 2 reactors drop at some of 400-blocks jumps

**Comment by nonenothing** [comment]
Issue still on.
Now long jump in space is ok - but long in hyper still drop.
Chambers don't connect in time, obviously.
Also maybe problem with greg multiblocks - will check it.

**Comment by LemADEC** [comment]
Thanks for the heads up.
Focus is on 1.12.2 currently and IC2 blocks don't jump at all. So until I can get IC2 working again, I can't really look into this issue.

**Comment by LemADEC** [comment]
IC2 has been fixed. Can you try to reproduce that issue and share you schematics?

**Comment by LemADEC** [comment]
No update for 7 months, assuming issue isn't reproduced on 1.12.2
