### ISSUE TITLE
Suggestion- AR Compatibability

### ISSUE THREAD

**Issue by CTH999** [LemADEC/WarpDrive#311]
It would be nice if, once you update this mod, it could be even more compatible with [AR](https://github.com/zmaster587/AdvancedRocketry/issues) (I.E. Air Generator Compatibility, Planet Compact, and more) This would work well with[1.10.2/1.11.2/1.12.2 Compatability](https://github.com/LemADEC/WarpDrive/milestone/8)

However, this is just a suggestion.

**Comment by LemADEC** [comment]
AdvancedRockectry has repeatedly broken compatibility with us, there's no point to do it solo.

**Comment by CTH999** [comment]
Ok, making an "issue" on their page. you logic seems logical!

And, [Here](https://github.com/zmaster587/AdvancedRocketry/issues/1160) It is!
