### ISSUE TITLE
Dictionary support for Parzi's Star Wars

### ISSUE THREAD

**Issue by Dead-Meming** [LemADEC/WarpDrive#313]
I run a forge 1.7.10 server on BisectHosting for a few of my friends and I with a modpack consisting of:
Starminer
Custom NPCs
CoFHCore
ThermalFoundation
ThermalExpansion
WarpDrive
industrialcraft
ComputerCraft
Light Bridges and Doors
Flans Mod
Parzi's Star Wars
journeymap
Optifine
Wailia
CodeChicken
NotEnoughItems
movingworld
Archimedes Ships
BuildCraft
SecurityCraft
Carpenter'sBlocks
But on to the real problem here, as we were sending our ships into space we encountered a problem, the StarFighters from Parzi's minecraft mod kept on suffocating! I soon dived into the server's config files trying to find some way to make space breathable and I did in the celestialObjects-default.xml. I proceeded to change space's and hyperspace's isBreathables into 'isBreathable="true"' but when we tested on the server once again I stumbled into the same problem! I now decided to converse with my friend Clark about what could be causing the problem. He soon theorized that it could be Galacticraft overwriting WarpDrive over breathing. Once again after removing Galacticraft (And corrupting the world in the process) the problem still sustained! At this point I've tried many things such as switching isBreathable between true and false again and again, and searching many configs. 

Anyway if you guys could help me I would be very grateful as everyone in the server has vision of space dogfights.

Also just another little bug we found is when you mount an Archimedes ship with an advanced computer on it it crashes the server 

Many Thanks,
Chris

**Comment by LemADEC** [comment]
You can't make space breathable, that would be nonsense.
You just need to declare the entities as non-living, see the dictionary configuration.
You can enable logs to get the names or use NEI to dump entity names.

**Comment by LemADEC** [comment]
Archimedes ship and the related Moving world will corrupt your world.
You can avoid a few crashes (not all of them) by using only simple blocks with no tile entities.

**Comment by Dead-Meming** [comment]
If you don't mind me asking, how exactly do you do that?
I'm sorry I'm still learning

**Comment by Dead-Meming** [comment]
Also would there be a way in which I could make the pilot armors for Parzi's Star Wars be able to use air canisters in space like the warp armor

**Comment by LemADEC** [comment]
There's a dictionary.yml configuration file, read through it.

**Comment by LemADEC** [comment]
No update for 4+ weeks, assuming fixed
