### ISSUE TITLE
um bug not sure or am i seeing things

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#315]
so i am playing minecraft and your website says that the force shields should connect into one shield with a single space in the middle however i see this happening 
![2018-03-11_15 19 01_1](https://user-images.githubusercontent.com/37277242/37259237-ef8702be-2540-11e8-9176-0aa7e6e6d591.png)
and other thing about that is that i have to deactivate the shields to fire any laser shot or i end up hurting my ship i was thinking if you fire the cannon you should connect a wire modem from computer craft to the canon itself where it should open the shield to allow the laser to hit its target and if there is no shield don't connect the wire modem to the force field projector to just fire like normal when there is not force field is that possible if so let me know it will save a lot of time and effort for me that should fixz the bug if this is a bug

**Comment by LemADEC** [comment]
what's your force field parameters?
where does the website says there's a single block of spacing in between?

Laser beam should pass through force field blocks provided they have the same beam frequency.

**Comment by LemADEC** [comment]
No answer for 3+ weeks, assuming closed
