### ISSUE TITLE
No bodys spawn in space on server

### ISSUE THREAD

**Issue by MarzipanAT** [LemADEC/WarpDrive#319]
I have a server and tried to play warp drive mod, but there where no objects in space and when you type /generate comes a error e.g.:

"Invalid asteroid 'null'; try one of the followings:
Error: group 'asteroid' isn't defined. Try one of:"

**Comment by LemADEC** [comment]
There's bug in reading the fillers files, remove the config/WarpDrive/filler-netherores.xml and type /wreload or reboot your server.

**Comment by MarzipanAT** [comment]
Sorry I've removed the file and rebooted the server, but I can only generate ships and jumpgates. Other objects still don't work.

**Comment by LemADEC** [comment]
post your server logs on gist or pastebin then

**Comment by LemADEC** [comment]
Any update on this?

**Comment by MarzipanAT** [comment]
Sorry, I couldn't aces my nitrado server via FTP, but somehow I maneged it now. I wrote in the chat what I'm doing. https://pastebin.com/aFfDFsJz

**Comment by LemADEC** [comment]
We need the detailed logs during boot, you've only posted the chat logs.
Also, make sure that "enable_world_generation_logs" is set to true in the WarpDrive configuration.

**Comment by LemADEC** [comment]
Any chances we can get those logs?

**Comment by LemADEC** [comment]
Logs please!

**Comment by LemADEC** [comment]
@MarzipanAT can you get us some logs please?

**Comment by LemADEC** [comment]
Fixed in dev
