### ISSUE TITLE
Wiki is missing air tanks and armor pages

### ISSUE THREAD

**Issue by Volcano10** [LemADEC/WarpDrive#327]
Some where around 50 blocks are missing and about 20-30 items are missing
some of the missing blocks: computers, ALL advanced items and blocks are missing, and much more.
some of the missing items: ALL armor, turning forks, most air tanks and ship tokens are missing and much more.
missing pages: i'm guessing at least 2 WHOLE pages!!!

**Comment by LemADEC** [comment]
The mod doesn't even have 50 different base blocks. Please be more specific if you want your point to get across.

Computers come from other mods which already have their own wikis. We do have a generic page to get you started. The latest actually link to those wikis. Consequently, I don't quite understand your point here.

Tiered blocks are considered variations of the same blocks, as such the wiki already cover those variations and their differences.

"and much more" is too generic for us to do anything about it.

Breathing section is missing a link to the air tanks page and the armor page isn't written yet.
Tuning fork and Tuning drivers already have a dedicated page named Tuning tools.
Building section is missing, along with the related Ship tokens. This part of the wiki will come with the shipyard update.

**Comment by LemADEC** [comment]
Already covered for what could make sense, make another ticket with *details*
