### ISSUE TITLE
Auto-Laser setup gone

### ISSUE THREAD

**Issue by JohnNemECis** [LemADEC/WarpDrive#328]
I've been gone for a while now, but when i returned, i was eager to download the new version. But i am really missing the old system to setup my lasers. how can i get it back? can it be added back? can i mess with the files to get it back? and how can i do it?

**Comment by LemADEC** [comment]
Which auto-laser setup are you referring to?

**Comment by JohnNemECis** [comment]
I’m referring to the one that existed in <V1.39b. In those time, when you connected a laser, you had an interface (computer craft) where all lasers were called out instantly how they were connected, and you could build laser batteries easily with corresponding Target Laser.

**Comment by LemADEC** [comment]
That feature is still present and related to the Weapon Controller. Connecting just a laser won't enable it.

**Comment by JohnNemECis** [comment]
Oh Thanks completely forgot… I haven’t played in like… a year? Sorry for the bother
