### ISSUE TITLE
Naming pass

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#33]
Classes name doesn't match in-game and some in-game names could be misleading. This issue tracks those change proposal for discussion before we do a pass and update the code:
- BlockReactor and TileEntityReactor -> BlockWarpCore and TileEntityWarpCore
- BlockProtocol and TileEntityProtocol -> BlockNetworkProtocol or BlockWarpInterface or ?
- BlockParticleBooster and TileEntityParticleBooster -> BlockLaserAmplifier or ?
- BlockLaser and TileEntityLaser -> BlockLaserHead ?

**Comment by TheNumenorean** [comment]
First sounds good. Second, WarpController? LaserAmplifier makes sense. Maybe Laser emitter?

**Comment by LemADEC** [comment]
Ok for WarpCore and WarpController.
LaserMedium or GainMedium is the proper english term for the core of the laser amplification. The first one is probably a better choice.
By LaserHead, I wanted to highlight the direction orientation of the beam. LaserDirector serves that but lacks the 'output' feels. LaserEmitter feels like it's all included. Need to think about that one.

**Comment by TheNumenorean** [comment]
Proper English perhaps, but itt would probably make more sense to people if it is labeled as an amplifier, since that is what it does.

**Comment by LemADEC** [comment]
LaserMedium is the actual real world name. I prefer to keep the 'booster' or 'amplifier' term for lasers used to increase another laser. Whatever the name we choose, it'll need some lore to explain what it does, so we could start with that.

**Comment by LemADEC** [comment]
Since the Core is supposed to be an antimatter reactor of sort, and the block is ambiguous to most player, how about we rename as follow?
Reactor/WarpCore -> ShipCore
Protocol/Controller -> ShipController

That way it's clear what it does and we can later on add blocks to externalize some features of the existing core.

**Comment by TheNumenorean** [comment]
Makes sense to me. Do you want to make the modifications, or should I?

**Comment by LemADEC** [comment]
I'll do it along with the Block/TE structure once you're done with config
