### ISSUE TITLE
Transporter Planet Bug

### ISSUE THREAD

**Issue by jhammerberg** [LemADEC/WarpDrive#332]
When trying to beam down to a planet, I set my transporter to a negative Y coordinate and (-50) and attempted to beam down, When doing this I some how got beamed to 0, 0 (The sun) I have an attached video. PS: This was on a server but I have the same problem in single player.
https://youtu.be/E4jJPm7DkD0

**Comment by LemADEC** [comment]
world was no longer updated when transporting across dimension.

**Comment by jhammerberg** [comment]
So? like make a new world and it will work? if so that didn't fix it.

**Comment by LemADEC** [comment]
The server was updated with the fix.
For single player, you'll have to wait for the next version on CurseForge.
