### ISSUE TITLE
Jump event (API)

### ISSUE THREAD

**Issue by Sirse** [LemADEC/WarpDrive#341]
I want to restrict warping into protected regions (if the players on ship don't have permissions in the region), but I can't get crew/captain GameProfile without reflection.
There is a way to get ShipCore TileEntity, but needed methods are private (ShipController reference also private). Can you implement additional public method into TileEntityShipCore?
Code snippet: [WarpDriveEventHandler](https://gitlab.zonasumraka.ru/Sirse/UMRegions/blob/master/src/main/java/org/ultramine/mods/privreg/integration/WarpDriveEventHandler.java)

**Comment by LemADEC** [comment]
The PreJump & PostJump events are only prototype, they're never called.
What property would you need in those?

**Comment by Sirse** [comment]
Get a list of players on the ship, get info about ship owner (player, who placed shipcontroller/shipcore ?) are enough for my purposes

**Comment by LemADEC** [comment]
I think you only need the IShipCore and IShipController instances, everything available through LUA is already available in those. From there you can find the players aboard the ship if needed.
