### ISSUE TITLE
Neither EnderIO Energy Conduits or Mekanism Universal Cables can connect to any WD block that uses power

### ISSUE THREAD

**Issue by khionu** [LemADEC/WarpDrive#344]
https://i.imgur.com/TJpakJM.jpg

Version: 1.4.2 on MC1.7.10
Mod list: ComputerCraft, EnderIO, WarpDrive, WorldEdit, WorldEditCUI.

**Comment by khionu** [comment]
Scratch that, not even Mekanism works https://i.imgur.com/AW1Tpgs.jpg.

I was able to get it working with WarpDrive 1.4.1

**Comment by khionu** [comment]
Not even the Subspace Capacitors

**Comment by khionu** [comment]
Ok, rolling back to 1.4.1 did not fix the issue, despite it working in a much larger pack, which contained all the same mods, save ComputerCraft, plus more.

This is the modpack + world (30 MB, MultiMC instance) where I'm having the issue.
https://cdn.discordapp.com/attachments/415273890756034570/465900406887940117/WarpDrive_test.zip

**Comment by LemADEC** [comment]
As the mod main page and change logs says, you need to have a proper energy API installed, namely CoFHcore for RF or IC2 for EU.
