### ISSUE TITLE
Fake air blocks are visible in air tight rooms

### ISSUE THREAD

**Issue by khionu** [LemADEC/WarpDrive#345]
https://i.imgur.com/Y3uC22k.jpg

I looked at the code and found it perfectly sound. I probably would have taken a similar approach. That said, it doesn't seem to be kosher with spaces with less than two lines of symmetry.

A few notes on the behavior:
 - Placing a block in a space that should have air, then breaking it, does trigger the space to be filled. However, it only stays filled for a few seconds.
 - It's the same blocks no matter where I put the air generators, as long as there's enough for the cabin.

**Comment by LemADEC** [comment]
What version are you using?
What does "kosher" mean?

Removing a block will cause an hole in the area that needs to be filled up. If you are in creative or use an IC2 wrench, the block breaking event might not fire and the system won't detect that the block is gone. In which case, the hole will never 'fill' itself with air until you place another block and break it more gently.
I've never seen a 'blinking' hole situation.

**Comment by khionu** [comment]
It's not a blinking hole, and me placing/breaking block in it's place is me attempting to fix it, it starts immediately. When I do so, the air fills the space, then leaves it shortly after, but does not repeat.

This is version 1.4.1, and I've seen this in 1.3.x versions.

"Kosher" meaning "is not holistic", being common slang for "does not go well with".

**Comment by LemADEC** [comment]
are you placing/breaking the block in survival or creative?
Can you make a video while using version 1.4.2?

**Comment by khionu** [comment]
I've tried in both. And I can't right now, but within the next day I can.

**Comment by khionu** [comment]
Just a quick update, I decided to go full out and create a few designs to see if I can narrow this behavior down to more specific reproduction details. This will likely take me a couple more weeks or longer to get all this setup, but I will make sure that what I have to provide is high quality.

**Comment by khionu** [comment]
Not a conclusion, but I was able to get the issue to show by adding a singular Ender IO Powered Light. Removing it and giving the air 5 seconds was enough for it to return to normal. It's the same grid pattern in my earlier screenshots. To be sure, the niche in the screenshots is not a factor, I tested after filling it in.

https://i.imgur.com/wpfatwC.jpg https://i.imgur.com/IE5UCt6.jpg https://i.imgur.com/1wPgoec.jpg

**Comment by khionu** [comment]
Removed them from the structure in my original screenshots, and the problem all but went away. I think it's safe to say that it's something to do with how they are rendered.

**Comment by LemADEC** [comment]
on today's screenshot, how many lights did you place then break in that area? I still see one on the roof too.

What do you mean by "the niche in the screenshots is not a factor" ?

**Comment by khionu** [comment]
The 1x3x1 space. I've been going on the theory that the mod was having issues with spaces that were not rectangular prisms, but that's not clearly not the case.

I took screenshots with and without the light, there was only ever one light.

**Comment by LemADEC** [comment]
What's your mods list?
Can you enable air logging at entity? it'll tell you the air stats around you.

**Comment by khionu** [comment]
`enable_breathing_logs` in the config? I can't find what else you mean.

[Mod List](https://github.com/LemADEC/WarpDrive/files/2216659/mods.txt)

**Comment by khionu** [comment]
If you can give me any and all config changes you'd want me to make, I can have the server owner make them tomorrow.

**Comment by LemADEC** [comment]
You've a lot of mods in there.
AdvancedRocketry has known incompatibilities with WarpDrive, I'm surprised you could even boot the server with it.
WarpDrive 1.4.1 is outdated.
ZombieAwareness creates invisible blocks and entities. Try `/wentity 20` to see if some are in the area.

The configuration to change is enable_air_at_entity_debug. As the comment says, it'll spam creative players chat to dump air information around them.
You can use `/wreload` to change the configuration without restarting the server.

Those EnderIO lights are creating invisible blocks in checker pattern, that's what you're seeing.
Are you able to reproduce without those EnderIO lights?

**Comment by khionu** [comment]
I've never had issues running a server with both AdvRkt and WarpDrive at the same time, though I've never tested the combination outside of 1.7.10.

There is only one other spot where I'm seeing the issue, and that's in a line above EnderIO Conduit Facades. This space will stay away when I break a block and replace the space, but comes back much later, usually after relogging.

It would be hard to cover every niche case for blocks that take up where Air would be wanted. I don't know how to best address this issue, without removing the Air block in favor of a non-block solution, but I do know that would create a domino effect of design problems. That said, this kind of issue will continue to exist, and I would appreciate you looking into a way to address it.

**Comment by LemADEC** [comment]
I'm a bit lost with your EnderIO conduit facade use case here. Can you elaborate with screenshots?

Removing the air blocks would remove the visual effect and the whole interest of the current design.
As it is, you don't need flood light in WarpDrive anyway.
The real question is how far does the visual glitch extend, to see how we could cover it on 1.12.

**Comment by LemADEC** [comment]
Reproduced on 1.12.2, fixed in dev
