### ISSUE TITLE
[1.12.2][thaumcraft] Warping cause infusion pillars to drop blocks

### ISSUE THREAD

**Issue by Nibor62** [LemADEC/WarpDrive#346]
Warping with infusion pillars on the ship drops two block of the material from what the pillar is made of (usually arcane stone), but the pillar is not destroy.
This allow infinite block generation.

_Build : WarpDrive-1.12.2-1.5.0.-2018-07-07a.jar_

**Comment by LemADEC** [comment]
Fixed in dev
