### ISSUE TITLE
Blocks update not triggered at ship border during jump

### ISSUE THREAD

**Issue by Nibor62** [LemADEC/WarpDrive#347]
A redstone torch attached to a ship block but being not part of the ship will not be dropped onto the ground after the ship have warp but instead it will float in the air, attached to nothing !

Build : WarpDrive-1.12.2-1.5.0.-2018-07-07a.jar

**Comment by LemADEC** [comment]
it's known limitation when ships are moved: block updates aren't triggered to save CPU, since you're not supposed to have overlapping block on the ship borders

**Comment by LemADEC** [comment]
Upon review, doing the change will cause more issues than anything, so we won't fix it.
