### ISSUE TITLE
Laser autoaiming

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#35]
Laser are currently almost useless against entity, notably players.
To fix that, we could add some auto-aiming or 'grab' distance so we can actually use them to that effect.

**Comment by TheNumenorean** [comment]
We could change the laser to be a projectile. This doesn't mean it would not look like a laser, I already have code that makes a projectile look laser like. Then we can have it damage players if it hits them, and still damage blocks on contact

**Comment by LemADEC** [comment]
The Laser execution code already scan blocks on the path and entities nearby. It just need to be adjusted for the auto-aiming, notably increasing tolerance with distance.

**Comment by TheNumenorean** [comment]
But why do we need auto aiming? Why not just have a large explosion at the point of contact?

**Comment by LemADEC** [comment]
Point of contact suppose you've almost perfectly aligned your target on the entity. This is practically impossible due to network latency and camera movement speed.
To me, Autoaim doesn't mean full assistance, it just adjust the angulation by a few degrees.

**Comment by Sasszem** [comment]
Instead of changing the laser beam to a projectile, why don't add photon/quantum torpedoes?

**Comment by LemADEC** [comment]
Kinetic weapons are already proposed in the Extended weapons ticket, please refer to it.

Laser cannon is unable to hit turrets from Helimod, so this issue is now actually a bug.

**Comment by TheNumenorean** [comment]
The point of making it a projectile is a purely code one. Though it would probably fix the helimod issue, it would not look as good.

**Comment by LemADEC** [comment]
We're already raytracing the beam trajectory one block after the other, there's no direct line or computation, we're literally simulating it moving through space.

**Comment by TheNumenorean** [comment]
Im responding for posterity to Sasszem, that making it a projectile was a code tactic not a mechanic changer.

**Comment by LemADEC** [comment]
Entity detection was messed up, should be fixed in f25d9577f43dd1bc495aeeb1dc8ced4c2e47dcc5
