### ISSUE TITLE
celestialObjects configuration for GalacticCraft

### ISSUE THREAD

**Issue by QuestionMan001** [LemADEC/WarpDrive#350]
Hello,
I have been playing your mod for quite a while on minecraft 1.7.10. and i've decided to add galacticraft planets and other dimensions into that file celestialObjects-default.xml, in new version downloaded from curseforge(1.4.2 or so) and it always crashes. 
My edited file attached. I'm lost, please do you have any advice on this?
[mc-error warpdrive mod.txt](https://github.com/LemADEC/WarpDrive/files/2219057/mc-error.warpdrive.mod.txt)

[celestialObjects-default.zip](https://github.com/LemADEC/WarpDrive/files/2219047/celestialObjects-default.zip)

**Comment by LemADEC** [comment]
The crash tells you to check your logs:
```
java.lang.RuntimeException: Invalid celestial objects definition: update your configuration to fix this validation error, search your logs for 'CelestiaObjects validation error' to get more details.
```

From the look of it, your planets are too big (12500 x 12500) if you keep them only 10000 blocks away from each others. 

Check the wiki template to help you define coordinates and sizes: https://docs.google.com/spreadsheets/d/11JG4dTQOPe95q5DGIgLOdS9PK6qNxMMJEamXtDwdFfQ

For the record, a 12500 x 12500 overworld takes ~6 GB of diskspace, imagine if all your planets are that big...

**Comment by QuestionMan001** [comment]
Thank you, i will look into it and try smaller planets.

**Comment by QuestionMan001** [comment]
By the way, how to add more solar systems to it, the tip in there is a bit small for me. It should work if i toss the planets around multiple solar systems.

**Comment by LemADEC** [comment]
you can change the star system size to fit more planets. You can also add another one, the same way you added planets.

**Comment by QuestionMan001** [comment]
Thank you again. I have reduced planet size to 2.5k and still the error pop-ups. I may double or triple the gaps between them or something like that, or toss them to other systems.

**Comment by LemADEC** [comment]
Check the logs, it'll tell you which planets are overlapping

**Comment by QuestionMan001** [comment]
I may be dumb but here is latest log, which says problem at line 208 which i don't see. Opened with notepad++
[fml-client-latest.zip](https://github.com/LemADEC/WarpDrive/files/2220866/fml-client-latest.zip)
also sending updated celestialobjects
[celestialObjects-default.zip](https://github.com/LemADEC/WarpDrive/files/2220868/celestialObjects-default.zip)
celestialObjects contains dimension id's from galacticraft and galaxyspace mostly. Still i feel like i lack the needed abilities to complete it

**Comment by QuestionMan001** [comment]
Please, i am trying all day to solve it, i have built a cruiser and want to travel with it around those dimensions
I have tried to create hyperspace with single solar system for every 8 planets, but still errors go out of game.
My ship i've built. It's the grey big one. Sorry it's zipped.
[spaceship.zip](https://github.com/LemADEC/WarpDrive/files/2221069/spaceship.zip)

**Comment by LemADEC** [comment]
```
[22:12:38] [Client thread/WARN] [WarpDrive/WarpDrive]: XML fatal error at line 208: The element type "worldGeneration" must be terminated by the matching end-tag "</worldGeneration>".
[22:12:38] [Client thread/ERROR] [WarpDrive/WarpDrive]: Error loading file celestialObjects-default.xml: The element type "worldGeneration" must be terminated by the matching end-tag "</worldGeneration>".
```

Your file is malformed, tags aren't balanced properly.
For example, line 542, you open a celestialObject with id="sun", but close it line 573. It should be closed line 548.
In notepad++, it'll highlight you the balanced tags:
![image](https://user-images.githubusercontent.com/4776032/43104717-9dc2c638-8ed2-11e8-9ce8-35359dfa9993.png)

In XML, the root tag can only be used once. Here the root tag is worldGeneration.
In practice, you've closed the root tag line 221, then close it again line 273, then reopen it line 275. That's invalid.

To help you detect such mistakes, you can add the 'XML Tools' plugin in Notepad++ through the plugin manager.
As long as you keep the WarpDrive.xsd file next to you celestialObject-*.xml file, it'll validate its syntax for you.

A good tutorial to get started on XML is available here: https://www.w3schools.com/xml/default.asp
I recommend you read up to the XML Attributes.

**Comment by QuestionMan001** [comment]
Thank you, it may be key to adding the dimensions as planets. I'll say if i was successful.

**Comment by QuestionMan001** [comment]
I think i know where your finger is pointed at, to say those must be right. I'll test that xml tools plugin and see what happens if i remove those bad segments

**Comment by QuestionMan001** [comment]
Boom. Minecraft launched! Thank you for all your help, with it, i finally launched it without crashing!
Your help was appreciated.

**Comment by LemADEC** [comment]
you're welcome, feel free to share you configuration so others can use it with GC :)

**Comment by QuestionMan001** [comment]
Sure, no problem, can do. Here it is
[celestialObjects-default.zip](https://github.com/LemADEC/WarpDrive/files/2221578/celestialObjects-default.zip)
I have added readme file for people like me who don't understand at first.
