### ISSUE TITLE
I'm a beginner, so could someone help me with adding planets?

### ISSUE THREAD

**Issue by Ocelot53** [LemADEC/WarpDrive#352]
So what am I supposed to do to add planets I've tried every other thing related to this but I still can't figure it out; could someone help me?

**Comment by LemADEC** [comment]
What did you try? what did you understood?

**Comment by Ocelot53** [comment]
I know that you are supposed to the warpdrive file and then config; I’m pretty sure I open the celestialObjects- default xlm file but I don’t know what program to open with.

**Comment by LemADEC** [comment]
Try Notepad++ with the XML plugin
Also, read this tutorial at least until the Attributes (included): https://www.w3schools.com/xml/

**Comment by Ocelot53** [comment]
Ok, cool; I read through up to that point and I've opened celestialObjects- default in Notepad++, what now?

**Comment by LemADEC** [comment]
Read it, it's full of comments explaining what is what

**Comment by LemADEC** [comment]
No update, assuming fixed
