### ISSUE TITLE
Transporter beacon not charging

### ISSUE THREAD

**Issue by RedstoneParkour** [LemADEC/WarpDrive#357]
Transporter beacons wont go into the charging slot for EnderIO, OC, Thermal Dymanics and IC2.
I am using the 1.4.2 version of WarpDrive.

**Comment by LemADEC** [comment]
https://github.com/LemADEC/WarpDrive/wiki/Transporter-Beacon#placement
Energy needs to be provided for its operation. **This can be done only from the bottom.**
