### ISSUE TITLE
NuclearCraft Ores

### ISSUE THREAD

**Issue by Sable501** [LemADEC/WarpDrive#358]
NuclearCraft Ores do not spawn in space, IC2 Uranium spawns in space, and NuclearCraft Ores spawn in Overworld, but I can't figure out why they won't spawn in space.

**Comment by LemADEC** [comment]
Feel free to add them to the FillerSet configuration of your liking, in the config/WarpDrive/filler-default.xml file.

**Comment by LemADEC** [comment]
NuclearCraft ores will be in 1.12.2 default configuration (currently it's dev only).
