### ISSUE TITLE
Ship Transportation

### ISSUE THREAD

**Issue by nitroman1999** [LemADEC/WarpDrive#359]
I think we need an option to disable Ship Core with a computer so we can transport a bunch of small ships on a big ship, because, as you probably know, you cannot overlap Ship Cores. This option will allow to avoid overlap without breaking Ship Core or Controller. Also, disabling a Ship Core would not hide it on the radar.
 I hope it will be added in future updates. Sorry for mistakes, I'm not really good at English.

**Comment by LemADEC** [comment]
The message reported when ship cores are intersecting is "Warp field intersects with other ship's field. Disable the other core to jump."
You can already disable a ship core through LUA or by terminating the default scripts (see https://github.com/LemADEC/WarpDrive/wiki/Programmable-blocks ).
A disabled ship core remains visible on the radar.
