### ISSUE TITLE
WarpDrive mod laser error

### ISSUE THREAD

**Issue by zinky0813** [LemADEC/WarpDrive#361]
<img width="1263" alt="screen shot 2018-12-07 at 6 40 48 pm" src="https://user-images.githubusercontent.com/45701938/49678035-fbe13180-fa4f-11e8-8716-5f932581fada.png">
This happend whenever I try to use a value command like this.
HIGH PRIORITY

**Comment by LemADEC** [comment]
What version are you using?
Where is the laserCamera placed compared to your computer?

**Comment by zinky0813** [comment]
1.6.4. I have the camera on top of the computer.

**Comment by LemADEC** [comment]
Latest is 1.4.2, try again.
Post a screenshot of your setup.

**Comment by zinky0813** [comment]
I will

**Comment by LemADEC** [comment]
Any update on this?

**Comment by LemADEC** [comment]
If you are on Minecraft 1.6.4, the API has changed since then. You can check the differences, here: https://github.com/LemADEC/WarpDrive/wiki/LUA-change-logs#changed-in-138
The laser bream frequency used to be just "freq" back on Minecraft 1.6.4.
