### ISSUE TITLE
a way to disable world border completely and be stopped at 29,999,984 blocks when galacticraft is installed to save headaches for configuration problems 

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#362]
i would be nice to have it set to default because someone else has the same problem

the original complaint

https://www.minecraftforum.net/forums/support/java-edition-support/2867273-cannot-access-my-base-because-of-a-fake-world

and mine 
![2018-11-11_16 47 52_1](https://user-images.githubusercontent.com/37277242/49705315-b5681000-fbd2-11e8-96ef-c133bfb8b9a2.png)

**Comment by ghost** [comment]
here are the mods
jk there about 300 mods so ya don't want to spend all the time looking and copying an pasting all the mods and i cant copy and paste all of them in a single folder because it is to big 


 jk i was joking
here they are

it is in google drive though
have fun XD

 https://drive.google.com/open?id=1_ERrljC2nF1-AEU9VoyMqlCaoJqumrbH

**Comment by ghost** [comment]
sorry though

**Comment by ghost** [comment]
and my dad just fell down the stairs
what a day

**Comment by LemADEC** [comment]
Space flight implies to have world border on planets.
Vanilla world generation stops around 200k on x or z axis, sometime even sooner for mods.
As such, you can't even reach 1M x 1M large world.

I don't understand your compatibility issue with Galacticraft, please be more specific.

**Comment by ghost** [comment]
i have a world border at 5,000 block that is invisible that send me back and sets me on fire and i don't know 
know why because i render a world  30,000,000 blocks in vennala minecraft and the picture show what i am seeing and the link says it is from warp drive however i guessing that's not the case because the max world size 30 million x and z however i am not running that many mods compared to what i actually run this is the basic slim down version of the pack that i am running for myself and i traval 5,000 in 16 min's
am i the only one not seeing this because i just did that 2 days ago

**Comment by ghost** [comment]
the link in google drive has all of the mods idk can you give me an idea how it would be causing this

**Comment by ghost** [comment]
i am in java version

**Comment by ghost** [comment]
however i don't have a bad computer at all it is actually really good

**Comment by ghost** [comment]
?

**Comment by ghost** [comment]
and it says something about galacticraft so i am wondering that might have something to do with it

**Comment by ghost** [comment]
and are you sure that you cant reach 1m x1m x and z because i will be more than happy to prove you wrong

**Comment by ghost** [comment]
and here it is both in creative and in survival
![2018-12-12_16 37 07](https://user-images.githubusercontent.com/37277242/49907719-4980e400-fe2c-11e8-92ca-d62f60650a2b.png)
![2018-12-12_16 33 45](https://user-images.githubusercontent.com/37277242/49907720-4b4aa780-fe2c-11e8-9d66-880b70e71558.png)

**Comment by LemADEC** [comment]
There's no terrain on your screenshots, that's because the game stopped even trying to generate the world. If you were in survival, you would die from movement glitches way before that.
You can learn more about the limits in the recent Minecon earth video from AntVenom, here: https://www.youtube.com/watch?v=v6-IAntqg5w&index=18&t=0s&list=PLZHdY_46KnYujVBcL0zdatfSkJeOB_bLt

Internally, mods also have bugs that cause weird things beyond 100k.

**Comment by ghost** [comment]
you lying the screen shot were taken in game so even if you say there isn't
any terrain regen your wrong because i am sanding in water in the photo in
a default world and i have been playing minecraft during 1.5.2 and how am i
not killing myself when the photo was taken in survival even if you say
there is if i would die and do to the lie you mod has been taken not of and
has been removed from my modpacks for your silly little lie as of right now
me working with your mod has been terminated i will no longer be
downloading your mod or promoting your mod
thank you have a nice day

**Comment by LemADEC** [comment]
The video is pretty good demonstration of the issues related to world generation. You should consider watching it.

**Comment by Mosely** [comment]
You know, I just don't understand why some people happen to be so belligerent.  Well, I, for one, still support the work of this mod and I applaud the efforts of those who, in 
their spare time, continue to maintain its rich set of features and functionality.

**Comment by LemADEC** [comment]
Not update on your Galacticraft issue after 6+ weeks. Feel free to open a new issue once you've specific details on that.
