### ISSUE TITLE
Publishing ship controller settings needed for "/generate ship" ships

### ISSUE THREAD

**Issue by kb-1000** [LemADEC/WarpDrive#364]
I try to use a pregenerated ship for jumps but for that I need the size settings.

**Comment by LemADEC** [comment]
Sneak right-clik the ship core with an empty to see the current dimension as a bounding box.
Start with 6 on each axis, then adjust from there.

**Comment by LemADEC** [comment]
Automatic detection of ship dimensions will come with docking, as part of the roadmap.

**Comment by kb-1000** [comment]
Will this come to 1.7.10 too?

**Comment by LemADEC** [comment]
No backport is planned

**Comment by kb-1000** [comment]
:worried:

**Comment by kb-1000** [comment]
On which branch do you develop? The newest I could see was from July 2018

**Comment by LemADEC** [comment]
I'm on the 1.12.2 branch, but it's only local on my computer for now. Would you like to help?

**Comment by kb-1000** [comment]
I don't think I would be very helpful, until now I've only done simple translation work (German), adding an ingot and its smelting recipe to a mod, adding ore dictionary to the ingots and ores of that mod and renaming some blocks and items in MC modding.

**Comment by LemADEC** [comment]
Well, the german translation could use an update if you're up for it

[lang.zip](https://github.com/LemADEC/WarpDrive/files/2831600/lang.zip)

**Comment by kb-1000** [comment]
I need the mod too that I can 1. test the translation and 2. better look what a certain thing is

**Comment by LemADEC** [comment]
What's your discord handle so I can share you the current closed alpha then?

**Comment by kb-1000** [comment]
`kaeptmblaubaer1000#3709`
