### ISSUE TITLE
Need some help and explanation with adding planets

### ISSUE THREAD

**Issue by TitaneerYeager** [LemADEC/WarpDrive#366]
Okay, so I downloaded the latest advent of ascension & glacticraft, and warp drive. In order to add the planets to space, do I need to enter the render variables? What will happen if I just enter the dimensions as planets with out inputting any render values? Do I need to add the dimensions, or if I go to the dimensions in creative will they automatically get updated into the space dimension? I ask this because I cannot find the dimension ids for the advent of ascension dimensions(Edit:I found them, but my question still stands whether I can just go to the dimensions or manually add each one.), and I saw someone seemed to have suggested this.
Thank you for your time.

**Comment by LemADEC** [comment]
Render elements are what defines how to display the planets in space. Without them, you won't see where the planets are.
Planets (and their dimension ids) shall be positioned manually in a space. If you don't declare them, you can't go there with your ship.

**Comment by TitaneerYeager** [comment]
Ok, so in the rendering area, I take it the red, blue, and green equal a solid color not three separate colors with each color filling in a part of the planet render? Also, what color code system does the rendering use? Are the period u and v required? I read what they do, but I still don't entirely understand what they do. I think period u rotates the render level along the x(?) axis in the amount of seconds entered? And v does the same for the y axis? If I do correctly understand the period u & v, If you are looking straight down at the render, does -40 mean the render does a leftward rotating motion in 40 seconds? I think it goes that way based off a grid chart with the -x & -y being the top left corner of the grid chart. Is this correct?
Thank you again for your time & help.

**Comment by LemADEC** [comment]
The documentation says:
"
  render defines several layers from surface to high atmosphere representing the planet.
  red, green, blue: **color mixing** from 0.00 (black) to 1.00 (white)
  alpha: transparency factor from 0.00 (invisible) to 1.00 (opaque)
  texture: optional texture to use, can come from resource pack, vanilla or the mod itself
  periodU, periodV: **optional** texture rotation period over the planet, measured in seconds, defaults to 0 (disabled)
		Texture coordinates are defined along U and V axis (you can see them as X and Y axis in the context of the texture pixels).
		A periodU of 40 means the texture will do progressively shift along U axis, doing a full rotation in 40 seconds.
		A periodU of -80 means the texture will shift twice slower in the opposite direction. 
  additive: optional blending function, defaults to false (multiplicative)
		Blending is the mathematical operation to mix existing pixel (previous layer or sky background) with the new one.
  
  In most cases, you want the first layer to be alpha="1.00", or the players will see the sky through the planet.
"

1/ red, green, blue are a single color mixing of the texture. It's used to "taint" the texture when rendering it.
2/ periodU and periodV are optional. (U V) is the standard texture coordinates with U being horizontal, V being vertical in the texture coordinates (not in-game, not in the model).
The actual speed is in full rotation per second, if my memory serves right.

**Comment by TitaneerYeager** [comment]
Ok, thank you alot.

**Comment by TitaneerYeager** [comment]
Thank you.
