### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TitaneerYeager** [LemADEC/WarpDrive#367]
I added dimensions in the celestialObjects-default.xml . But when I launched the game, this happened.
[crash.txt](https://github.com/LemADEC/WarpDrive/files/2776005/crash.txt)
Here is the .xml file with the added dimensions.
[celestialObjects-default.xml.zip](https://github.com/LemADEC/WarpDrive/files/2776006/celestialObjects-default.xml.zip)
You will need to unzip the .xml file.
I know it is this file because before I added the dimensions to the .xml file, it worked fine.
Thank you for the help.

**Comment by LemADEC** [comment]
Invalid celestial objects definition: update your configuration to fix this validation error, search your logs for 'CelestiaObjects validation error' to get more details.
=> search that term in your logs

**Comment by TitaneerYeager** [comment]
Without looking at the logs, I found a typo in the xml file. I fixed the typo but I still get the same crash report, so I am looking in the logs now. I take it you are talking about the logs folder inside the .minecraft folder?
EDIT:
The logs provided a typo. I was not putting </parent> to close the parent elements.
Thank you again.
