### ISSUE TITLE
Players Stuck in Hardcore even after leaving space.

### ISSUE THREAD

**Issue by redwhat1234** [LemADEC/WarpDrive#369]
I'm running a server using warp drive, and recently have started having an issue where even when not in space, or hyperspace the players are in Hardcore mode, even after editing NBT Data files, and making sure the server properties reflect hardcore == false.

**Comment by LemADEC** [comment]
The mod doesn't change anything related to gamemode.
What is exactly happening?

**Comment by redwhat1234** [comment]
Well, for some reason both solarSystem and Hyperspace are stuck in hardcore
mode, even after changing the dat files for them, they return to Hardcore
upon init, I didn't find anything relating to gamemode in the source code,
but if there is anything, could you point me to it? I was kinda just
reporting this to let you know that this is a bug, and see if you knew what
might be doing it so I could fix it and build the source.

**Comment by LemADEC** [comment]
As already explained, **the mod doesn't change anything related to gamemode**.
What version are you using?
What other mods are present?
Since when does the issue happen?
Why do you think it's WarpDrive doing it?
What about the game mode in The End and The Nether?
Details are important. Details needs to be provided. Lots of details are wanted here.

**Comment by redwhat1234** [comment]
As Soon as I'm present I'll send you a complete mod list, including all
their version annotations, and The Nether, End, and every other Dimension
is Hardcore == False, only solarSystem and Hyperspace are hardcore, which
is what leads me to believe that Warp drive may be the cause, I am however
unsure as to why looking through the dimension generators you have for them.

**Comment by LemADEC** [comment]
No update for 2 months, assuming invalid/closed
