### ISSUE TITLE
Gravity Hull Plating

### ISSUE THREAD

**Issue by jhammerberg** [LemADEC/WarpDrive#371]
In Star Trek, the excuse for having gravity in space is "gravity hull plating", they never go into much detail on it, but I think something similar would be a nice addition to Warp Drive. I purpose to add a block that functions like normal hull, except players and entities 5 or less blocks above it's surface would experience normal Earth gravity (unlike currently where its only about 1/3 that). You could also make it if you wanted to pull players less the further they are from the block, say at 3 blocks away you would only have 1/2 the gravity. If you want it could also need to be powered.

**Comment by freznelfennec** [comment]
A more practical approach might be a central 'gravity generator' block, which would be able to create multiple regions of artificial gravity (and possibly anti-gravity?) throughout the ship/station.  This way you don't end up with a ton of TileEntities.  The range for this block could then be the same as the ship core, or some fraction of it requiring large ships to have a few of them.

**Comment by LemADEC** [comment]
Please refer to existing issue #110 for Gravity overhaul discussions.
