### ISSUE TITLE
Transporter Beacon won't charge in IE Charging Station

### ISSUE THREAD

**Issue by rckymtnrfc** [LemADEC/WarpDrive#374]
I was testing out your mod and watched your tutorial videos.  Very interested in playing with it but I don't use a lot of tech mods, just Immersive Engineering.  Your machines all appeared to take energy from the IE capacitors but I was unable to place the Transporter Beacon into the IE Charging Station.  Do you think it could be made compatible?  Unfortunately I've found no other ways to charge the beacon without adding in a mod like TE.

Thanks for considering it!

**Comment by LemADEC** [comment]
Transporter beacon can only be charged from bottom when place as a block.
Using a Subspace capacitor from WarpDrive, or its ImmersiveEngineering equivalent will work.

Remember to specify the mod version.

**Comment by rckymtnrfc** [comment]
Sorry, they do charge as you stated.  I didn't realize they were charging because The One Probe is showing 0 RF when I look at the transporter beacon.

Thanks for your help!

**Comment by LemADEC** [comment]
The One Probe only measure power connecting from the top face, if I remember right, so it can be confusing at times.
Right clicking a placed beacon should give you its status.
