### ISSUE TITLE
Security Station - OpenComputers issues

### ISSUE THREAD

**Issue by JohnDog3112** [LemADEC/WarpDrive#375]
Before I start, here are the mods I'm running:
CodeChickenLib-1.12.2-3.2.2.353-universal
CoFHCore-1.12.2-4.6.2.25-universal
CoFHWorld-1.12.2-1.3.0.6-universal
OpenComputers-MC1.12.2-1.7.4.153
RedstoneFlux-1.12-2.1.0.6-universal
ThermalCultivation-1.12.2-0.3.2.11-universal
ThermalDynamics-1.12.2-2.5.4.18-universal
ThermalExpansion-1.12.2-5.5.3.41-universal
ThermalFoundation-1.12.2-2.6.2.26-universal
ThermalInnovation-1.12.2-0.3.2.11-universal
WarpDrive-1.12.2-1.5.0.-
Forge-1.12.2-14.23.5.2837

Now, the issue that I'm having is that whenever I connect the warpdrive Security Station, the computer won't startup up and is unable to get a component list. Whenever I do this it returns java.lang.NullPointerException

Just to show it works with just the ship core:
![image](https://user-images.githubusercontent.com/16504051/57740448-97b93e00-767d-11e9-8ee6-93a160549487.png)
![image](https://user-images.githubusercontent.com/16504051/57740553-0ac2b480-767e-11e9-8682-259ad867b470.png)

With the Security Station:
![image](https://user-images.githubusercontent.com/16504051/57740612-4fe6e680-767e-11e9-8ec2-d45dc023975b.png)
![image](https://user-images.githubusercontent.com/16504051/57740615-54130400-767e-11e9-872e-0c0519e0afd2.png)

Hooking it up after starting the computer:
![image](https://user-images.githubusercontent.com/16504051/57740638-6ee57880-767e-11e9-8ea9-5d71bde46700.png)

Logs:
[latest.log](https://github.com/LemADEC/WarpDrive/files/3180412/latest.log)

Hopefully that's enough information if it's not, just tell me.

**Comment by LemADEC** [comment]
Security station is a placeholder for design in-progress. It has no recipe and no Lua API yet, hence won't work.
