### ISSUE TITLE
Snow on hull slabs cause hard crash

### ISSUE THREAD

**Issue by khionu** [LemADEC/WarpDrive#379]
# Steps to reproduce
1) Build platform high enough for inclement weather to be snow
2) Put down some Basic White Hull Slabs (horizontal) on top of the platform.
3) Start rain, and wait for crash

[The entire (short) log file](https://paste.ee/p/kiG1T)

# Note
After crashing, if you manage to clear the weather before it crashes again, you can see that one or more of the slabs will have been replaced by snow.

# Environment
OS: Linux and Windows 10
Java: 8 (multiple builds and versions, OpenJDK and Oracle)
Forge: 14.23.5.2838
Mods: WarpDrive 1.5.4

For your testing convenience, a MultiMC Instance: 
[WarpDrive Snow Test.zip](https://github.com/LemADEC/WarpDrive/files/3319360/WarpDrive.Snow.Test.zip). This already has a world that has crashed due to the issue, as well as the original crashlog.

**Comment by LemADEC** [comment]
Fixed in next update
