### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by PrettyHeatToast** [LemADEC/WarpDrive#38]
Upon starting the game with computercraft, industrialcraft and the warpdrive mod installed the game crashes upon loading. http://pastebin.com/LwpNcWwN

**Comment by TheNumenorean** [comment]
You downloaded the 1.6.4 version of WarpDrive and are trying to run it on a 1.7.10 server. Please go to the curse download page and make sure you download the Alpha release labeled for 1.7.10
http://minecraft.curseforge.com/mc-mods/233565-warpdrive/files/2251310
Make sure to also remove the old version.
