### ISSUE TITLE
Client crash when Better questing tries to render an invalid itemstack

### ISSUE THREAD

**Issue by mcmso** [LemADEC/WarpDrive#381]
[crash-2019-07-06_13.59.09-client.txt](https://github.com/LemADEC/WarpDrive/files/3364490/crash-2019-07-06_13.59.09-client.txt)

**Comment by LemADEC** [comment]
That's a bug in BetterQuesting trying to render an invalid ItemStack.
I'll add a safety check in next version.
For now you can disable `add_ore_dictionary_name` in the configuration file.

**Comment by mcmso** [comment]
Many thanks for your prompt response
