### ISSUE TITLE
Unable to do Ships

### ISSUE THREAD

**Issue by Xenos93** [LemADEC/WarpDrive#383]
Whenever i try to do a spacecraft , and go in the computer (ComputerCraft, cos easier) the computer tell me "warpdrivecommons : 791 : invalidkey to 'next'." when i try to go in menus other than "Home(0)". The Computer reboot itself and make me comeback to the "Home(0)" menu ...

game version 1.12.2 forge 14.23.5.2838
mod version 1.5.0

**Comment by LemADEC** [comment]
1.5.0 is way outdated, try with latest.
ComputerCraft is no longer maintained and won't work properly. Use CC:Tweaked instead.

**Comment by Xenos93** [comment]
ok thank you :)
