### ISSUE TITLE
Player teleportation via beacon not working

### ISSUE THREAD

**Issue by lordsn0** [LemADEC/WarpDrive#384]
Able find a player by name in the transporter core but i am unable to power the transporter beacon to complete the teleportation. I can not charge the beacon by placing it on a power source as it dose not drop an item upon breaking it dose not seem to drop in to any power output slot in an capacitor blocks

**Comment by LemADEC** [comment]
Beacon can only powered be charged as a block, only from the bottom, as stated in the wiki here: https://github.com/LemADEC/WarpDrive/wiki/Transporter-Beacon#placement

Breaking a beacon will return its item form.

Please specify the mod version, what other mods are in the environment, what energy source was tried, etc.

**Comment by lordsn0** [comment]
WarpDrive 1.5.5 Alpha for 1.12.2, i have tried sub-space capacitors and mekanism energy cubes. I have been able to power the beacon via a subspace capacitor but the item dose still not drop when broken in survival, the only way to acquire them is by grabbing the block type through creative.

**Comment by LemADEC** [comment]
![image](https://user-images.githubusercontent.com/4776032/61279612-bee3d700-a7b6-11e9-8494-f6b4094c36ec.png)
works fine by me

**Comment by lordsn0** [comment]
Yep im dumb as a post, been trying to break it with my hand
