### ISSUE TITLE
Missing programs

### ISSUE THREAD

**Issue by lordsn0** [LemADEC/WarpDrive#385]
Programs for cloaking, tree farm, radar and mining laser do not load when a computer craft computer is placed next to the correct block. scripts also do not appear when the "ls" command is used

**Comment by LemADEC** [comment]
Please specify what version of the mods are involved.

**Comment by lordsn0** [comment]
WarpDrive 1.5.5 Alpha for 1.12.2. Is there a method to manually load the scripts?

**Comment by LemADEC** [comment]
What version of ComputerCraft?
Please post your debug logs on gist/pastebin.

**Comment by lordsn0** [comment]
Sorry, i am using cc-tweaked-1.12.2-1.83.1 as i couldn't get past the boot screen with the latest version of official computercraft
debug log here:
[latest.log](https://github.com/LemADEC/WarpDrive/files/3396077/latest.log)

**Comment by LemADEC** [comment]
Try with less mods, seems some are having bad interactions.
Also, update your Java.

**Comment by lordsn0** [comment]
Apparently there was an odd interaction, scripts now seem to load, dont know if its an issue or just a product of being in alpha but the clocking core can only be enabled and disabled on tier one is there any way to get tier 2 cloaking in the current version?

**Comment by LemADEC** [comment]
Cloaking core can be upgraded with a Diamond crystal.
