### ISSUE TITLE
Force field bug?

### ISSUE THREAD

**Issue by yeetmcskeet11** [LemADEC/WarpDrive#386]
Not sure if i am doing something wrong but when i set up a force field projector it collapses after 1-5 seconds. It has power, it makes a noise and has been tuned but when any shape is applied to it the force field blocks begin to build but disappear after a short time along with the sound stopping. occasionally i get a message about needing more power but even if i use 
the Zero point module infinite power source the collapse still happening. There is no computercraft program that i can load ether.
![2019-07-17_21 07 14](https://user-images.githubusercontent.com/53002374/61371282-bd5e0000-a8d7-11e9-89cd-39ddbd62a902.png)

**Comment by LemADEC** [comment]
what's your mods list and version?

**Comment by LemADEC** [comment]
Fixed in dev

**Comment by yeetmcskeet11** [comment]
WarpDrive-1.12.2-1.5.5.jar
foamfix-0.10.3-1.12.2
OptiFine_1.12.2_HD_U_E3
cc-tweaked-1.12.2-1.83.1

Fixed in dev? Not sure what that means sorry.

**Comment by LemADEC** [comment]
It means it's fixed in my development space and will be part of the next update on CurseForge.
