### ISSUE TITLE
Issue with computercraft

### ISSUE THREAD

**Issue by yeetmcskeet11** [LemADEC/WarpDrive#387]
I am getting a error when trying to add lasers and i am missing the mining program when trying to use the mining laser

Error:![2019-07-22_12 48 58](https://user-images.githubusercontent.com/53002374/61603054-6e212200-ac7f-11e9-9031-9be210c2c09d.png)
Missing program: ![2019-07-22_12 52 01](https://user-images.githubusercontent.com/53002374/61603073-86913c80-ac7f-11e9-8345-e8ec88e20ddf.png)

mod list:
cc-tweaked-1.12.2-1.83.1
WarpDrive-1.12.2-1.5.5

Unrelated but the cloaking core seems to use power even when off, is this a feature or a bug?

**Comment by LemADEC** [comment]
Most blocks won't connect until you upgrade them with a Computer interface.

**Comment by LemADEC** [comment]
The cloaking core has a huge internal energy storage, it'll drain energy until that storage is full.
