### ISSUE TITLE
Laser tree farm stuck at 3x3 size

### ISSUE THREAD

**Issue by solar138** [LemADEC/WarpDrive#388]
**Describe the bug**
The laser tree farm seems to be stuck at a 3x3 scanning and mining radius. I've read the wiki, which is incomplete, but it still doesn't work.

**To Reproduce**
1. Place down laser tree farm.
2. Add a superior laser medium underneath it.
3. Place a chest next to it.
4. Power the superior laser medium.
5. Attach a computer to the tree farm.
6. Weird blue rings appear and it only mines trees in a 3x3 radius.

**Expected behavior**
I added one superior laser medium underneath it so I expect it to work with an 11x11 size. Even when I add more, it still is 3x3.

**Screenshots**

Setup: 
![2019-07-27_13 33 42](https://user-images.githubusercontent.com/46548002/61999328-5082fc80-b073-11e9-80a4-eeac29c2b062.png)

**Versions** 
 - WarpDrive version: WarpDrive-1.12.2-1.5.5
 - Forge version: release 1.12.2-forge1.12.2-14.23.5.2836
 - Modpack name/version: Custom Pack: Minecraft 1.12.2
 - Other notable mods & version: ComputerCraft: cc-tweaked-1.12.2-1.83.1.jar (No CC 1.12.2)

**Additional context**

I'm playing with the mod in creative mode.

**Comment by LemADEC** [comment]
Your configuration is probably corrupted, it defaults to something like that:
```
tree_farm {
    # Maximum number of laser mediums
    I:max_mediums_count=5

    # Maximum scan radius without any laser medium, on X and Z axis, measured in blocks
    I:max_radius_no_laser_medium=3

    # Bonus to maximum scan radius per laser medium, on X and Z axis, measured in blocks
    I:max_radius_per_laser_medium=2

    # Maximum reach distance of the laser without any laser medium, measured in blocks
    I:max_reach_distance_no_laser_medium=8

    # Bonus to maximum reach distance per laser medium, measured in blocks
    I:max_reach_distance_per_laser_medium=6
}
```

Also, check the radius property in LUA, if you set it to 1, you'll get the same effect as you described here.

**Comment by 4thharbinger** [comment]
Thanks, I removed the config files for the mod to replace them and it fixed it. I also reinstalled the mod.
