### ISSUE TITLE
Integration With The Matter Overdrive mod

### ISSUE THREAD

**Issue by PrettyHeatToast** [LemADEC/WarpDrive#39]
I would like to request some kind of integration with the matter overdrive mod as it is also inspired by Star Trek, I would also like to request a change of the internal name of the transporter block so you can play with both mods at the same time.

**Comment by LemADEC** [comment]
3 blocks can have the same names in 2 different mods. I understand it can be confusing for the player but from gameplay perspective it shouldn't matter.

**Comment by PrettyHeatToast** [comment]
It doesn't work when trying to boot the game as it gives the following error. http://pastebin.com/abu0dFCt

**Comment by LemADEC** [comment]
That's very interresting. Thanks for the logs!

**Comment by LemADEC** [comment]
Blocks are automatically prefixed by modid, while tile entities are not. WarpDrive and MatterOverdrive both fails to workaround that Forge weakness, hence they're incompatible.
