### ISSUE TITLE
Disabling the breathing system

### ISSUE THREAD

**Issue by Trip-kun** [LemADEC/WarpDrive#392]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my systems (power, radiation, oxygen) aren't compatible or there are multiple.
**Describe the solution you'd like**
I would like an option to disable the breathing system. 
**Describe alternatives you've considered**
I have an alternative to the breathing system in advanced rocketry, which I would prefer to use for unity.
**Additional context**
All I want is a config option to disable the breathing system

**Comment by LemADEC** [comment]
Seeing how the other breathing mod are lag fest compared to WarpDrive, I don't quite understand your motivation here.
Also, you can already choose which dimension requires air or not, for quite some time.

**Comment by Trip-kun** [comment]
I dislike the way the that the WarpDrive breathing works

**Comment by Trip-kun** [comment]
I found the correct config though, thanks

**Comment by LemADEC** [comment]
> I dislike the way the that the WarpDrive breathing works

that still doesn't tell me what the problem is

**Comment by Trip-kun** [comment]
The problem was I wanted to disable the oxygen. Which I found in the config after you pointed it out. There is no problem any more

**Comment by Trip-kun** [comment]
Thanks for the awsome work on the mod
