### ISSUE TITLE
Any block duplication bug while ship jumping

### ISSUE THREAD

**Issue by Noire86** [LemADEC/WarpDrive#393]
**Describe the bug**
Any block can be duplicated at the right moment while ship jumps.

Explanation video https://www.youtube.com/watch?v=0f43-rAUYlw&feature=youtu.be

**Versions** (latest is not a valid answer)
 - WarpDrive version:  1.7 1.4.2 latest
 - Forge version: 1614

**Comment by LemADEC** [comment]
Player are supposed to get nausea potion effect during jump, how comes it's not happening on the video?
How do you know when is the right time to break the blocks?

**Comment by Noire86** [comment]
Nausea is disabled in config.

I dunno, we found it experimentally, by trying to repro this dupe in the last seconds of jump. It is sure a bit random, but with a proper skill it is possible to dupe items at will.

**Comment by LemADEC** [comment]
Well, there's no easy fix, especially on 1.7.10. You can enable nausea and increase the block transfer rate, but that's pretty much it.

**Comment by LemADEC** [comment]
A workaround will be added to next public version for 1.12.2. We'll see how it holds.
