### ISSUE TITLE
Cant Disable Breathing in Config

### ISSUE THREAD

**Issue by Trip-kun** [LemADEC/WarpDrive#395]
**Describe the bug**
When I try and disable breathing in the space and hyperspace dimensions in the config, they still require

**To Reproduce**
1. Install Warp Drive
2. Change Config so Space and Hyperspace dont require oxygen/breathing
3. Create a world
4. Create a ship and fly to space
5. Observe still having the breathing alerts and damage
**Expected behavior**
When the dimension doesn't require breathing it shouldn't produce alerts and damage

**Screenshots**
n/a
**Logs**
Link to pastebin/gist or equivalent logs
n/a
**Versions** (latest is not a valid answer)
 - WarpDrive version: 	WarpDrive 1.5.7 Alpha for 1.12.2
 - Forge version: forge-14.23.5.2838
 - Modpack name/version: n/a
 - Other notable mods & version: n/a

**Additional context**
n/a

**Comment by LemADEC** [comment]
Space and Hyperspace are non breathable, whatever is set in the celestialObjects configuration.
This is the intended behavior.

**Comment by TripTripy** [comment]
:( Well, that's irritating. Shouldn't it follow the celestialObjects configuration instead of just auto defaulting to non breathable?

**Comment by Trip-kun** [comment]
Is there any way to disable this at all? Or am I stuck

**Comment by Trip-kun** [comment]
The reason I want to disable it is because I want players to use the advanced rocketry oxygen system instead.

**Comment by LemADEC** [comment]
WarpDrive space uses WarpDrive air system.
AdvancedRocketry has an history of breaking others mods dimension, gravity and breathing systems, don't expect support when using such a mod in your pack.

**Comment by Trip-kun** [comment]
All I wanted was to disable the breathing system. Would be a nice option.
