### ISSUE TITLE
Tooltips on sneak

### ISSUE THREAD

**Issue by Kahra** [LemADEC/WarpDrive#397]
Hi,
in the config.yml file, the parameter "ON_SNEAK" doesn't work for all the 
S:tooltip_SOMETHING lines.

The values ALWAYS, NEVER and ADVANCED_TOOLTIPS work fine, but "ON_SNEAK" doesn't do anything when I press the vanilla shortcut for sneaking (aka Left Shift).

I'm using the standard 1.4.2 version of WarpDrive.

**Comment by LemADEC** [comment]
Thanks for report!
I did fix that bug on 1.12.2, here 2f0cd4adb2cbea7c5ab5ed40bdb06434a76fc4e2
There's no plan to update the 1.7.10 at this time.
