### ISSUE TITLE
Computer Craft Dependencey for 1.12.2

### ISSUE THREAD

**Issue by Domsmasher1** [LemADEC/WarpDrive#400]
![image](https://user-images.githubusercontent.com/47263379/64321614-39d1ad00-d004-11e9-9b24-27c2e78b31a7.png)

I can not find this verson of computer craft and am wondering if there is anything I can do to fix this
using latest 1.12.2 verson

**Comment by LemADEC** [comment]
The change logs tells your specifically what to do, go read them!
