### ISSUE TITLE
crash when shooting laser cannon at force field

### ISSUE THREAD

**Issue by mzldh** [LemADEC/WarpDrive#401]
**Describe the bug**
server crashed when shooting laser cannon at basic force field, other tiers are not tested yet

**To Reproduce**
1. set up a laser cannon and a force field
2. shoot laser cannon at force field
3. See error

**Expected behavior**
server side crash

**Screenshots**

**Logs**
Link to pastebin/gist or equivalent logs
https://pastebin.com/asSGcdtJ
**Versions** (latest is not a valid answer)
 - WarpDrive version: 1.5.6
 - Forge version: 1.12.2-14.23.5.2838
 - Modpack name/version: world war minecraft 11, most recent at sep/8/2019
 - Other notable mods & version: 

**Additional context**

**Comment by LemADEC** [comment]
This only happens with the scanning frequency

**Comment by LemADEC** [comment]
Fixed in dev, will be in the next public release
