### ISSUE TITLE
Laser farm is not detected [open computers]

### ISSUE THREAD

**Issue by NCrashed** [LemADEC/WarpDrive#402]
**Describe the bug**
Laser farm is not mounted as component in `df` and doesn't have any output for Analyzer.

**To Reproduce**
1. Build farm as in screenshot
2. Install OpenOS on computer
3. Run `df`
4. See no warpdriveLaserTreefarm among devices

**Expected behavior**
A tree farm is mounted as device in `/mnt` as according to tutorial https://github.com/LemADEC/WarpDrive/wiki/Laser-tree-farm#usage-with-computercraft

**Screenshots**
![Screenshot from 2019-09-18 02-33-44](https://user-images.githubusercontent.com/2116167/65087084-f9d3d800-d9bc-11e9-9867-7cc6128bfb80.png)

![Screenshot from 2019-09-18 02-37-19](https://user-images.githubusercontent.com/2116167/65087183-559e6100-d9bd-11e9-9ebf-28babee57b67.png)

**Logs**
Sorry, no logs.

**Versions** (latest is not a valid answer)
 - Minecraft: 1.12.2
 - WarpDrive version: 1.12.2-1.5.7
 - Forge version: 14.23.5.2846
 - Modpack name/version: custom
 - Gregtech CE version: 1.8.6.437 

**Additional context**

**Comment by LemADEC** [comment]
1- your version is outdated by 1 month
2- you need to add a computer interface upgrade to connect machines, unless the interface is part of the original recipe

**Comment by NCrashed** [comment]
Thanks! Installing the upgrade inside the tree farm actually helped. I wish it was in wiki page.

**Comment by LemADEC** [comment]
yes, the wiki only covers 1.7.10 for now
