### ISSUE TITLE
Crashed after jumping

### ISSUE THREAD

**Issue by KIRILLAND78** [LemADEC/WarpDrive#403]
After usual jump server crashed. We played on my friend`s server.
Here are server log and crashlog.

 - WarpDrive version: 1.5.9 Beta for 1.12.2
 - Forge version: 14.23.5.2838
 - Modpack name/version: Our own modpack
 - Other notable mods & version: Many oc addons. Yes. Without IC2 or something like that.
[log-1.txt](https://github.com/LemADEC/WarpDrive/files/3665581/log-1.txt)
[log-2.txt](https://github.com/LemADEC/WarpDrive/files/3665582/log-2.txt)

**Comment by LemADEC** [comment]
There's nothing related to WarpDrive in that crash log.
There's no ship jumping in that server log.
Crash is 3h older than the server log, seems pretty much unrelated.

Please provide proper logs.

**Comment by KIRILLAND78** [comment]
Seems like something related to Open Computers. Really sorry for disturbing.
