### ISSUE TITLE
WarpDrive only supports IC2 energy in the overworld

### ISSUE THREAD

**Issue by PiggleMcDiggle** [LemADEC/WarpDrive#404]
I cannot use any kind of IC2 cable to transfer power across components (e.g reactors to laser mediums) I have not found any scenario in which it works so I can only power things by direct contact by putting a capacitor or reactor down directly by a laser medium or other machine.

I am using the Linux Mint 19 Tara 64-bit Operating System.
Mods:
CC: Tweaked (1.82.2)
IndustrialCraft 2 (2.8.170-ex112)
WarpDrive(1.12.2-1.5.9.SNAPSHOT)
Are there different versions I should be using, and where can I download them? All mods stated are for Minecraft 1.12.2 also.
I also am running a few other mods yet I had this issue without them too. (BetterFoliage, WorldEdit, MPM, JEI, NEI, CodeChickenLib, Vanilla Builder's Extension.)

I expect the power from the zero point module to power the laser medium yet it does not.

SCREENSHOT: https://imgur.com/a/XepXpIp
LOGS: https://pastebin.com/m2j1jkje

Thank you for your help.

**Comment by LemADEC** [comment]
IC2 energy flows only in the overworld (DIM0). I've no idea what's causing that issue.

**Comment by PiggleMcDiggle** [comment]
Are there any different versions or mods that you typically use with Warp Drive?

**Comment by LemADEC** [comment]
IC2 works by itself in other dimension, but it doesn't work with WarpDrive outside the overworld.

**Comment by PiggleMcDiggle** [comment]
That's odd, because this issue persists in the overworld and I've seen lots of videos of people using cables in space. How are we meant to power our spacecraft if IC2 does not work?

**Comment by LemADEC** [comment]
other energy network are supported, like GregTech, forge and RedstoneFlux. There's just IC2 being a bit peculiar on 1.12.2.

**Comment by LemADEC** [comment]
Fixed in next update
