### ISSUE TITLE
Fails to Load with Chisel&Bits mod

### ISSUE THREAD

**Issue by ROMVoid95** [LemADEC/WarpDrive#405]
**Describe the bug**
Mod incompatibility with Chisel & Bits.
I have tried changing the configs and both mods in many area's. The result is the same

Mod launches when Chisel and Bits is removed.
**Logs**
Crash Log: https://paste.dimdev.org/atemitanav.md

**Versions** (latest is not a valid answer)
 - WarpDrive version: 1.12.2-1.5.10.SNAPSHOT
 - Forge version: 1.12.2-14.23.5.2847
 - Modpack name/version: 
 - Other notable mods & version: chiselsandbits-14.33

**Additional context**

**Comment by LemADEC** [comment]
Chisel and bits isn't supported.
Use Little Tiles with WarpDrive, that mod is actually supported, and maintained.

**Comment by LemADEC** [comment]
I did a quick check on the related source code for that `getTileEntitySafely()` method: the comments are right, it's stupid. There's probably a dup bug or crash coming with their current implementation.
https://github.com/AlgorithmX2/Chisels-and-Bits/blob/2dca498fb31ff20bba77d8030447faac81ca5966/src/main/java/mod/chiselsandbits/helpers/ModUtil.java#L273

**Comment by ROMVoid95** [comment]
i also saw that comment, my modding experience is still "beginner" level, was trying to figure out WHY that method is throwing an error with this mod. But thanks for looking into it. We are in fact using LittleTiles and while i have no issue with it, many people that are playing prefer Chisel (and its addons).

**Comment by LemADEC** [comment]
I've added a fix on my side, should be in the next release, whenever it comes out.
