### ISSUE TITLE
NPE at boot with FTB Quests

### ISSUE THREAD

**Issue by FrostCreeper07** [LemADEC/WarpDrive#408]
**Describe the bug**
When loading minecraft with warpdrive in it minecraft crashes with a java.lang.NullPointerException error. VanillaFix says suspected mods are this one and ftb quests.

**To Reproduce**
1. Click Play
2. Wait For Crash
3. See Error
4. 

**Expected behavior**

**Screenshots**

**Logs**
https://pastebin.com/qQ2Dp5VA

**Versions** (latest is not a valid answer)
 - WarpDrive version: 1.5.11
 - Forge version: 14.23.5.2847
 - Modpack name/version: Stranded on Planet Yuma 5 (Unreleased) 
 - Other notable mods & version: 

**Additional context**

**Comment by LemADEC** [comment]
That's an ftbquests bug, causing NPE when asked for block's hardness.

**Comment by LemADEC** [comment]
Actually, there's also a bug on my side, so I'll have to fix that one.

**Comment by twothe** [comment]
Getting the same error in my own mod pack: https://paste.dimdev.org/udaqibowok.mccrash
