### ISSUE TITLE
1.12.2 Crash at boot with LogisticPipes

### ISSUE THREAD

**Issue by FomaDima** [LemADEC/WarpDrive#410]
**Describe the bug**
start game and crash

**Logs**
https://pastebin.com/RHdr7Jrx

**Versions** (latest is not a valid answer)
 - WarpDrive version: in logs last for 1.12.2
 - Forge version:  in logs last for 1.12.2

 - Other notable mods & version: all in logs

**Comment by Pentasis** [comment]
Not sure if it is the same issue but mine crashes at start as well: https://paste.dimdev.org/upasetivum.mccrash
Version 1.12.2-1.5.11.SNAPSHOT

If it isn't, just say so and I'll post it as a new issue.

**Comment by LemADEC** [comment]
@FomaDima that's fixed in next update.
@EvertX that's MatterOverdrive bug has a workaround in next update.

**Comment by LemADEC** [comment]
Fixed 1.12.2-1.5.12
