### ISSUE TITLE
Compatibility with Galacticraft Oxygen

### ISSUE THREAD

**Issue by Archilyte** [LemADEC/WarpDrive#413]
**Is your feature request related to a problem? Please describe.**
Compatibility with Galacticraft oxygen (or its equipment, at least)

**Describe the solution you'd like**
A config option to disable Galacticraft oxygen, like how Advanced Rocketry does it (for now)

**Describe alternatives you've considered**
Make Galacticraft oxygen equipment be compatible with Warpdrive oxygen.

**Comment by Nyabloody** [comment]
Also while we talk about it... The Air Generator from WarpDrive and the Oxygen Sealer from Galacticraft fight between each other to try to make a room "breathable".

I noticed often that the Oxygen Sealer take the priority over the Air Generator making it impossible to breath in a space station inside the WarpDrive dimensions.

Making it also unadvisable to enable the isBreathable="false" for any Galacticraft dimensions because of this bug.

**Comment by Archilyte** [comment]
For now I am using this workaround

- Get Advanced Rocketry
- Make Advanced Rocketry disable Galacticraft oxygen (via config files)
- Use CraftTweaker (or something else) to disable everything else in Advanced Rcoketry (and oxygen stuff from Galacticraft) unless you want some stuff from Advanced Rocketry

However, this workaround is pretty annoying, and doesn't make sense to use a mod which was meant for one thing to be used for a completely different thing.

**Comment by LemADEC** [comment]
Next update should have some basic handling for this: as long as a dimension is declared in the Celestial Map, the Galacticraft oxygen gear will be ignored in that dimension. You'll still need the environmental protection. You'll still see your oxygen reserve overlay.

**Comment by Archilyte** [comment]
That's fine, I guess. The overlay is going to be a bit annoying, but other than that its all good.

Any info on when this update will come out?

**Comment by Nyabloody** [comment]
Maybe I didn't get it but the next update will disable Galacticraft Oxygen? Wouldn't it better to let us the choice to either use one or another within the config?

**Comment by Archilyte** [comment]
I agree with @Korvynus. I would prefer to have Galacticraft oxygen enabled, since 

1.  The oxygen generators actually consume oxygen (unlike WarpDrive air generators which only consume power)
2.  Galacticraft has separate inventory slots for oxygen tanks and masks

**Comment by LemADEC** [comment]
As already said above, as long as a dimension is declared in the Celestial Map, the Galacticraft oxygen gear will be ignored in that dimension.
It's not a global setting, it's the same as gravity: dimensions declared in the celestial map are using WarpDrive oxygen and gravity, others are on their own.

As for Galacticraft approach to air in space, please note that in reality, vegetation only recycles air, it doesn't generate it. While this approach is original, it's implementation is fairly laggy for servers during production and transportation of air. I prefer to use CPU for simulating air propagation and leaks.

**Comment by Archilyte** [comment]
>  please note that in reality, vegetation only recycles air, it doesn't generate it.

That's not what I am talking about though. I was saying what if the Warpdrive air generators consumed Oxygen (as in a separate fluid) like how the generators in Galacticraft and Advanced Rocketry does.

**Comment by LemADEC** [comment]
You're not consuming oxygen in space, you're recycling it through filters. In much larger setups you can use a biodome to the same effect.
You only consume air when you initially fill an area that was built in space, or you've an air leak. In other words, you consumption should be extremely slow.
Now, in terms of gameplay, it's already a pain to use a face of the air generator for power. I didn't want to add another building constrains with a hardly use oxygen pipe. I had to do that in a few Galacticraft space stations and it was a major pain.

**Comment by Seggan** [comment]
I agree Galacticraft compatibility should be added.

**Comment by Archilyte** [comment]
@LemADEC But still, there should be a option which allows Galacticraft oxygen systems to take over Warpdrive oxygen systems.

**Comment by VirtualZer0** [comment]
@LemADEC i can't believe you just keep ignoring such an obvious request. The oxygen system in Galactic Craft looks much more preferable and comprehensive to many people, as it does to me. I don't care if it is more productive or not, I want to use it, but you choose to completely disable it despite the fact that it is much better designed. Your oxygen system in my modpack, by the way, does not work at all, unlike the system in GC.

**Comment by LemADEC** [comment]
As explained many times by many peoples, Galacticraft oxygen is laggy, leaks memory and doesn't support additional dimensions.
It's also fairly unrealistic and remains completely unexplained in-game.
WarpDrive does NOT disable oxygen from Galacticraft in that mod's dimensions, unlike other space mods by default.
WarpDrive gives you the choice to add dimensions to its system through the celestial map configuration. This gives you easy integration and much smoother experience for players.
You clearly didn't read any history of this specific ticket, actually necro posting on an unrelated issue in your specific setup.
Furthermore, you obviously didn't read the mod's provided configuration which is largely commented, and already answer most of your needs.
I'm pretty sure you didn't read the wiki, nor the in-game manual, not even check the tutorials on the mod, so yeah... just fuck off.

**Comment by VirtualZer0** [comment]
Between non-working and non-optimal mechanics, I'd rather choose non-optimal. Anyway, I just remove the code that blocks Galacticraft's oxygen from your mod and now everything works as I wanted.

**Comment by director777-moderator** [comment]
@VirtualZer0 как это сделать. я тоже хочу удалить этот долбанный код на гравитацию и кислород

**Comment by director777-moderator** [comment]
> Как неоднократно объясняли многие люди, кислород Galacticraft тормозит, теряет память и не поддерживает дополнительные измерения. Это также довольно нереалистично и остается совершенно необъяснимым в игре. WarpDrive НЕ отключает кислород в Galacticraft в измерениях этого мода, в отличие от других космических модов по умолчанию. WarpDrive дает вам возможность добавлять измерения в свою систему с помощью конфигурации небесной карты. Это обеспечивает легкую интеграцию и более удобный опыт для игроков. Вы явно не читали историю этого конкретного билета, а на самом деле некропостили по несвязанной с вами проблеме в вашей конкретной настройке. Более того, вы, очевидно, не читали предоставленную конфигурацию мода, которая в значительной степени прокомментирована и уже отвечает большинству ваших потребностей. Я почти уверен, что вы не читали ни вики, ни внутриигрового руководства, ни даже не читали обучающие материалы по моду, так что да... просто пошли на хер.

бухнул?
