### ISSUE TITLE
Problem with JAVA

### ISSUE THREAD

**Issue by Oz1m4nd145** [LemADEC/WarpDrive#415]
In the try to configuratelasers by using Computercraft it sends a red msg "Java Exception Thrown: java.lang.RuntimeException:Missing Computer interface upgrade.

i have installed Java 7 & 8 to try to make it work

**Comment by LemADEC** [comment]
There's an issue template, it's not optional.
Only Java 1.8 is supported, refer to the official download.
You need a Computer interface to use block, either in the recipe or through an upgrade.
