### ISSUE TITLE
Crash when using a non-keyboard key for SNEAK

### ISSUE THREAD

**Issue by waffle112** [LemADEC/WarpDrive#417]
**Describe the bug**
Game crashes on startup or a few minutes in by looking in the inventory after changing controls. Game points to Warpdrive and Inventory Tweaks as potential causes

**To Reproduce**
1. Launch game on computer using 
	Radeon RX 590 Series
	Driver version:	26.20.15002.61
	Driver date:	12/4/2019
	DirectX version:	12 (FL 12.0)
2. mouse = Logitech g502 (newer version) w/ logitech g hub
	Physical location:	PCI bus 31, device 0, function 0
2. open controls and changed sneak key to button 5 on mouse
3. open inventory

**Expected behavior**
game works as normal

**Logs**
https://gist.github.com/waffle112/64268e9202a23e5a59b50ab0c400a92a

**Versions** (latest is not a valid answer)
 - WarpDrive version: 1.5.11
 - Forge version: 14.23.5.2847
 - Modpack name/version: testpack ver 2.8.5 -> 
https://www.curseforge.com/minecraft/modpacks/techraptor
 - Other notable mods & version: 

**Additional context**

**Comment by LemADEC** [comment]
This is not a graphic issue, this is keyboard controls issue. What key did you use for Sneaking?

**Comment by waffle112** [comment]
Sorry, I guess I forgot to change the title when I realized it was a mouse issue and not a graphics issue. I tried using both button 5 and 4 as sneak and both caused an issue where opening the inventory caused the game to crash. In addition, WAILA saw everything as unnamed.
