### ISSUE TITLE
Server crash when restoring ImmersiveEngineering connectors

### ISSUE THREAD

**Issue by NCrashed** [LemADEC/WarpDrive#419]
**Describe the bug**
Server crashed when tried to restore with `component.warpdriveShipScanner.deploy(<shipName>, <x>, <y>, <z>, <rotation>)` command. Exception:
```
Dec 18 21:42:09 main minecraft-server[23385]: [21:42:09] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
Dec 18 21:42:09 main minecraft-server[23385]: java.lang.NullPointerException: null
Dec 18 21:42:09 main minecraft-server[23385]:         at cr0s.warpdrive.compat.CompatImmersiveEngineering.restoreExternals(CompatImmersiveEngineering.java:366) ~[CompatImmersiveEngineering.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at cr0s.warpdrive.event.JumpSequencer.state_moveExternals(JumpSequencer.java:1182) ~[JumpSequencer.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at cr0s.warpdrive.event.JumpSequencer.onUpdate(JumpSequencer.java:327) ~[JumpSequencer.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at cr0s.warpdrive.event.AbstractSequencer.updateTick(AbstractSequencer.java:24) ~[AbstractSequencer.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at cr0s.warpdrive.event.WorldHandler.onServerTick(WorldHandler.java:129) ~[WorldHandler.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_694_WorldHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:752) ~[EventBus.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:702) ~[EventBus.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
Dec 18 21:42:09 main minecraft-server[23385]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**To Reproduce**
1. Follow https://github.com/LemADEC/WarpDrive/wiki/Frequently-Asked-Questions#how-can-i-restore-a-ship-from-schematic
2. Execute the deploy command with the ship in attachement.

**Expected behavior**
Restored ship was expected.

**Logs**
[crash.txt](https://github.com/LemADEC/WarpDrive/files/3980659/crash.txt)

**Versions** (latest is not a valid answer)
 - WarpDrive version: 1.12.2-1.5.9
 - Forge version: 14.23.5.2846
 - Modpack name/version: 
 - Other notable mods & version: 
	- ImmersiveEngineering-0.12-92
    - ironchest-1.12.2-7.0.72.847
    - industrialcraft-2-2.8.187-ex112
    - OpenComputers-MC1.12.2-1.7.4+8ec532326
    - ProjectRed-1.12.2-4.9.4.120
    - ThermalExpansion-1.12.2-5.5.4.43
    - appliedenergistics2-rv6-alpha-4

**Additional context**
Failed schematic:
[restore.zip](https://github.com/LemADEC/WarpDrive/files/3980664/restore.zip)

**Comment by LemADEC** [comment]
What version of Immersive Engineering was used when saving that schematic?

**Comment by NCrashed** [comment]
Immersive Engineering 0.12 - 92

https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/2799143

**Comment by LemADEC** [comment]
ImmersiveEngineering connectors have no tile entities when restoring but do have them on jump, that's weird. I wonder if it's because you've removed NuclearCraft along the way.

**Comment by LemADEC** [comment]
Actually, it's fairly old and well hidden bug in the sequencer, it'll be fixed in the next version.
