### ISSUE TITLE
In game starmap

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#422]
**Is your feature request related to a problem? Please describe.**
I can't think of a simple way to keep track of where celestial objects are, especially in game.

**Describe the solution you'd like**
A block which shows a star map, like a hologram, or just the coordinates of planets for an easier implementation.

**Describe alternatives you've considered**
I can't find any other mod that lets you make your own custom map in game. Please let me know if you know of one. Currently I am using an online coordinate grid, which removes the immersion and is harder to use whilst playing.

**Comment by LemADEC** [comment]
OpenComputers has a holographic projector you can program.
WarpDrive radar comes with a basic script to project coordinates on a screen, you can easily modify it to add your own map.

In the long term, there'll be some form of navigation map that player fills over time.

**Comment by ghost** [comment]
Thanks for the advice
