### ISSUE TITLE
3000t max mass but 4000t required for hyperspace

### ISSUE THREAD

**Issue by Deathtanium** [LemADEC/WarpDrive#424]
So, I am not sure whether this is a bug. In short, I noticed that the maximum mass for a ship is 3000t while the minimum mass for hyperspace is 4000t. That makes it impossible to access hyperspace.

I am using a Corvette core and I have built my ship in creative mode. I am operating it using OpenComputers. The ship's mass is ~1700t. The max mass specified for the core is 3000t, while the minimum mass for engaging hyperdrive is 4000t. This does not seem to be a programming error, but I just don't know what to do about this. Thank you greatly for your time.

**Comment by Deathtanium** [comment]
![Screenshot (47)](https://user-images.githubusercontent.com/21280260/71425257-331c8380-264f-11ea-81f1-212277a691f7.png)

**Comment by Deathtanium** [comment]
Apologies, I have now found the proper guide to reach hyperspace. Sorry for the inconvenience. I will close this issue, if that's ok.

**Comment by LemADEC** [comment]
A Corvette ship mass can go from 1728 to 13824 tons.
The 3000 tons max is for landing/moving on a planet.
