### ISSUE TITLE
redstone signal crash in warpdriveCommons

### ISSUE THREAD

**Issue by infiniteblock** [LemADEC/WarpDrive#425]
**Describe the bug**
placing a lever next to a computer running warpdrive scripts flick lever and computer crashes

**To Reproduce**
1.  place ship core/accelerator,
2.  place computer
3.  place switch next to computer screen
4.  flick lever quickly open computer screen to see crash

**Expected behavior**
computer to handle the redstone signal

**Screenshots**
https://cdn.discordapp.com/attachments/316657437631447041/662153819622473752/unknown.png

**Logs**
N/A

**Versions** (latest is not a valid answer)
-   WarpDrive version: WarpDrive-1.12.2-1.5.10
-   Forge version: 14.23.5.2838
-   Modpack name/version: WorldWarMinecraft11-11.3.0
-   Other notable mods & version: 

**Additional context**

**Comment by LemADEC** [comment]
Fixed in next update
