### ISSUE TITLE
warp drive Commons:45: Colour not supported, error on Advanced when making Laser for ship

### ISSUE THREAD

**Issue by SingleLimaBean** [LemADEC/WarpDrive#426]
Whenever I try to set up my laser by going in the advanced computer it says "warp drive Commons:45: Colour not supported" I don't understand what I did wrong, it worked around 1 months ago this has never happened and I need help solving it.

![2020-01-19_10 16 08](https://user-images.githubusercontent.com/60068612/72683372-c60cda00-3aa4-11ea-9778-a37b3e8f77e4.png)

**Comment by LemADEC** [comment]
There's an issue template, it's not optional, use it!
