### ISSUE TITLE
Crash: java.lang.NoClassDefFoundError: icbm/classic/lib/emp/CapabilityEMP

### ISSUE THREAD

**Issue by bradyrussell** [LemADEC/WarpDrive#433]
**Describe the bug**
When combined with ICBM and other mods, such as nuclearcraft, warpdrive crashes if any of its blocks are placed / loaded.

**To Reproduce**
1.  Install mods listed below
2.  Create new world
3.  Place a warpdrive block (I use air raid siren)
4.  See error and crash

**Logs**
https://hastebin.com/aguyokacos.md

**Versions** (latest is not a valid answer)
-   WarpDrive version:  WarpDrive-1.12.2-1.5.12
-   Forge version: 14.23.5.2838
-   Modpack name/version: Custom
-   Other notable mods & version: 
Hwyla-1.8.26-B41_1.12.2
ICBM-classic-1.12.2-4.0.0b70
NuclearCraft-2.18o-1.12.2
OpenComputers-MC1.12.2-1.7.5.192

With just these mods the error is present.

**Additional context**
I have had this happen in my custom modpack even after removing nuclearcraft, but had no luck isolating what else causes it.

**Comment by LemADEC** [comment]
ICBM updated its API with the so called "blast rewrite". You need to use an older version of ICBM until I can update the compatibility module.

**Comment by AutonomicPerfectionist** [comment]
Could you provide the version of ICBM that works? I've tried 3.3.0 which is one of the oldest for 1.12.2 on curse and it still crashes.

**Comment by bradyrussell** [comment]
I believe ICBM-classic-1.12.2-3.3.0b65 will work, whereas ICBM-classic-1.12.2-4.0.0b70 will not.

**Comment by AutonomicPerfectionist** [comment]
Nevermind, the file I had was a renamed 4.0.0b70 for some reason. Thanks anyways

**Comment by LemADEC** [comment]
any ICBM-1.12.2-3.3.x should work with WarpDrive 1.12.2-1.5.12.
Anyway fix it's fix in the next update, which should be out soon (c).

**Comment by LemADEC** [comment]
Fixed in https://github.com/LemADEC/WarpDrive/commit/41dd3e7c98944fefd648dafd638ff84c45b11ba4
