### ISSUE TITLE
Items wrongly created during scanner's ship materialization

### ISSUE THREAD

**Issue by RedShakespeare** [LemADEC/WarpDrive#435]
**Describe the bug**
When using the shipscanner to materialize a former schematic,  all components in the computer case become other items. (in my own case, items appear to be those in mod GalaxySpace)

**To Reproduce**
1.  Scan a former spaceship with the shipscanner.
2.  Move to another place, put a set of OC Computer(including keyboard and screen), power source(like an MFSU in mod industrial 2 exp.), a ShipController, a ShipCore and a Ship Scanner correctly according to command lines, error logs and java codes(which is not mentioned by any tutorial videos and wiki doesn't seem to help much about it...) 
3.  Install OpenOS and warpdriveShipController ,reboot the computer, interrupt the controller GUI with Ctrl+C, then open lua command lines to activate the shipscanner.
![image](https://user-images.githubusercontent.com/44523519/74605960-72bf9300-5107-11ea-9274-04aa33ca9626.png)
4. Get aboard the deployed ship, check the computer case on that.
5. See unexpected items.
![image](https://user-images.githubusercontent.com/44523519/74606020-eeb9db00-5107-11ea-9e6a-8978b8369599.png)
![image](https://user-images.githubusercontent.com/44523519/74606022-f4afbc00-5107-11ea-9e11-50247dbd3897.png)
![image](https://user-images.githubusercontent.com/44523519/74606025-faa59d00-5107-11ea-97fa-476c7699926e.png)

**Expected behavior**
The new computer should be completely the same as the old one in both hardware and software.

**Screenshots**
See "To Reproduce"

**Versions** (latest is not a valid answer)
-   WarpDrive version:1.7.10-1.4.2 
-   Forge version: 10.13.4.1614-1.7.10
-   Modpack name/version: (Self-mixed, not a released modpack)
-   Other notable mods & version: 
    OC-1.7.10-1.7.5.1290-universal
    IndustrialCraft-2-2.2.828-exp
    GalacticraftCore,-Planet,micDoodleCore-1.7-3.0.12.504
    GalaxySpace-1.7.10-1.2.12

**Additional context**
Searched "Warp Drive mod" on youtube before raising this issue, and maybe I'm not the only one who has trouble put the wiki tutorial into practice...

**Comment by RedShakespeare** [comment]
By the way, really I thought there could have been pre-designed spaceship in the ship tokens until I renamed my own ship schematic as "42"... Maybe some can be added in next version? (Well, I may raise another issue about it separately...?)

**Comment by LemADEC** [comment]
Ship scanner doesn't need installation on the computer, it's just direct LUA methods to call.
To save a ship, you just need to jump. You only need to save with a ship scanner when the ship can't jump (for example, if you build in the overworld a ship too big for a planet, etc.).

Only blocks are converted. To transfer items, you need to use the same level.dat, specifically the same mapping of item ids. So, to transfer between different world/maps, you'll have to replace the items and make a new save. That limitation is specific to 1.7.10 and older.

You can already make custom ship tokens, just rename the schematic to the token# and move it the warpdriveSchematic folder (in the root).

**Comment by RedShakespeare** [comment]
Thx a lot! I didn't expected to be replyed so quickly lol
Besides, it took me around 1 hour making attempts and more time thinking before I finally figured out how to put things in the right place (before I raised this issue)... maybe put the reply here into wiki tutorial can help? Just a little advice  =v=

(-Did I really say anything about "installing a ship scanner"?)
(-And I hope more content producers (including myself if possible) can share ship tokens on the Internet for this extrordinary-designed mod (so that more design choices can be available, expect for starting designing from nothing(especially for greenhands.) ) )

**Comment by LemADEC** [comment]
Technically, you could use a WorldEdit schematic too, but you loose chest/block contents because that format don't support it. So, there's already lots of schematics available ;)

**Comment by LemADEC** [comment]
The Server FAQ section of the wiki already covers ship tokens usage, here: https://github.com/LemADEC/WarpDrive/wiki/Frequently-Asked-Questions#how-can-i-restore-a-ship-from-schematic
This could use a dedicated page in the wiki.

**Comment by LemADEC** [comment]
Wiki is replaced with in-game documentation. The latest has a dedicated page on schematics and data fixer. Hence closing as of WarpDrive-1.12.2-1.5.14.
