### ISSUE TITLE
Conflict with Tardis mod, galacticraft, or something else doctor who... or just JEI

### ISSUE THREAD

**Issue by Hawkfang42** [LemADEC/WarpDrive#436]
**Describe the bug**
The game crashes during mod loading

**To Reproduce**
1. start game.
2. wait

**Expected behavior**
  Game loads normally
**Screenshots**
None

**Logs**
https://pastebin.com/5sGWTxxz

**Versions**
-   WarpDrive version: 1.5.12 release
-   Forge version: 14.23.5.2847
-   Modpack name/version: no modpack/this is a homemade modpack
-   Other notable mods & version:
  weeping angels version 41
  The Roundel mod 8.0 public beta
  New TARDIS Mod version 0.1.2
  Doctor Who Regeneration version 2.1.0
  MicdoodleCore 1.12.2 version 4.0.2.244
  Doctor Who k9 1.12.2 version 1.3.3.0
  Just Enough Items 1.12.2 Version 4.15.0.293
  Immersive Engineering 0.12-92
  Galacticraft-Planets-1.12.2-4.0.2.244
  GalacticraftCore-1.12.2-4.0.2.244
**Additional context**
it worked just fine before I added this mod.

**Comment by LemADEC** [comment]
Please post the full debug log on gist or pastebin.
That's probably a bug in the Tardis mod which happens to be exposed by WarpDrive.
Report this to Tardis dev team.

**Comment by Hawkfang42** [comment]
Full debug log? what do you mean by that? I know I posted the crash log, so I am afraid I do not understand. (about the debug log part)

**Comment by LemADEC** [comment]
A crash report is just a subset of the server logs as found in the logs folder.

**Comment by LemADEC** [comment]
any update on this?
