### ISSUE TITLE
WarpDrive paired with New TARDIS Mod causes server to crash during startup (1.12.2)

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#439]
**Describe the bug** 
Running a server with WarpDrive mod & New TARDIS Mod on minecraft 1.12.2 causes the server to crash before finishing startup.

**To Reproduce** 

    1. Setup a forge 1.12.2 server
    2. Add WarpDrive mod & New TARDIS Mod into the mods folder
    3. Run server
    4. Server crashes

**Expected behavior** 
Server loads world & stays open

**Logs** 

   Server Log: https://pastebin.com/FFZSxerG
   Crash Log: https://pastebin.com/QV3QErGJ
   Debug Log: https://pastebin.com/BjB7LSZ4

**Versions**

    WarpDrive version: 1.5.12
    Forge version: 14.23.5.2847
    Other notable mods & version: New TARDIS Mod (0.1.4)

**Comment by LemADEC** [comment]
Dup of #436 
This is bug in the TARDIS mod, nothing we can do on our side.
