### ISSUE TITLE
Spawn outside of the world border and killed on server

### ISSUE THREAD

**Issue by Mahnez** [LemADEC/WarpDrive#440]
**Describe the bug**
I spawn outside of the world border and will be killed in survival mode.

**To Reproduce**
1.  Install the mod on server
2.  Start server
3.  Log in to server

**Expected behavior**
Being able to make spaceships and fly them

**Logs**
Can't find 'em

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.12
-   Forge version: 1.12.2 - 14.23.5.2847
-   Modpack name/version: None
-   Other notable mods & version: Nothing much

**Comment by LemADEC** [comment]
Logs and mods list are not optional.
We also need your configuration.
Is it a new world save or did you add the mod to an existing one?

**Comment by Mahnez** [comment]
Got it working, thanks to you on the discord.

**Comment by LemADEC** [comment]
for reference in case someone as a similar issue:
When adding WarpDrive to an existing map, you need to adjust overworld center or world border to account for your current base location.
Recentering is easier but implies to adjust or remove the Nether entry in the Celestial Map.
Resizing implies to adjust all planets position (see the FAQ), which is a bit more involved.
