### ISSUE TITLE
davncies viehicles error

### ISSUE THREAD

**Issue by DabbingEevee** [LemADEC/WarpDrive#441]
davincies vehicles mod allows for air ships and boats, but when you mount the ship, it all disappears

**To Reproduce**
1.  install https://www.curseforge.com/minecraft/mc-mods/davincis-vessels
2.  creatw a airship orwhatever
3.  place down a warp core
4.  assemble and mount

**Expected behavior**
i expected it to convert to a entity, except it just all disappears

**Logs**
https://pastebin.com/NHd8vuud

**Versions** (latest is not a valid answer)
-   WarpDrive-1.12.2-1.5.12
-   1.12.2-forge1.12.2-14.23.5.2847
-   N/A
-   davincisvessels-1.12.2-6.340

**Additional context**

**Comment by LemADEC** [comment]
logs are incomplete.
DaVinci is buggy and no longer supported, it's probably a bug on their side.

**Comment by LemADEC** [comment]
No update for 7+ days, no logs to proceed, closing
