### ISSUE TITLE
New TARDIS Mod crash

### ISSUE THREAD

**Issue by legonorris201** [LemADEC/WarpDrive#442]
**Describe the bug**
Game crashes on startup when WarpDrive and New TARDIS Mod are installed

**To Reproduce**
1.  Download New TARDIS Mod here:
2.  Put in mods folder
3.  Start Minecraft
4.  Watch it crash

**Expected behavior**
Minecraft starts up as normal with both mods loaded and active.

**Logs**
[Tardis crash.txt](https://github.com/LemADEC/WarpDrive/files/4361700/Tardis.crash.txt)

**Versions** 
-   WarpDrive version: 1.12.2-1.5.12
-   Forge version:  1.12.2-14.23.5.2838
-   Modpack name/version: N/A
-   Other notable mods & version: New TARDIS Mod: Any version

**Additional context**
If the problem is on the side of the New TARDIS Mod and cannot be fixed here, I can report it to them. Thank you for looking into this.

**Comment by LemADEC** [comment]
Dup of #439 
Search existing issues before creating duplicates.
