### ISSUE TITLE
Computer unable to startup

### ISSUE THREAD

**Issue by forcemaster06** [LemADEC/WarpDrive#443]
**bug description**
After I have built my ship and used the appropriate ship core, powered it and placed the advanced computer on any side of the core, it gives the message “connecting... Checking right warpdriveShipCore wrapping! startup:33: attempt to call field ‘isInterfaced’(a nil value)”

**To Reproduce**
1.  Build a ship within required parameters of ship core (core type does not matter)
2.  Place core, power source (source used is zero point module) and computer as instructed by the github page “first ship, first jump”
3.  Right click on computer
4.  See error

**Expected Behavior**
I expected to be prompted to name the ship
**Screenshots**
![image](https://user-images.githubusercontent.com/61894372/77596178-aabdb100-6ed1-11ea-813a-94094de985f2.jpeg)
![image](https://user-images.githubusercontent.com/61894372/77596188-b4471900-6ed1-11ea-9c12-4ea060d65d08.jpeg)
![image](https://user-images.githubusercontent.com/61894372/77596200-bc06bd80-6ed1-11ea-940b-7d82588a9f34.jpeg)

**Logs**
Not sure what to put here

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.9
-   Forge version: 1.12.2-forge1.12.2-14.23.5.2847
-   Modpack name/version: N/A
-   Other notable mods & version: cc-tweaked-1.12.2-1.86.1

**Additional context**
I just got the mod, so I might just be making a dumb mistake. I also just updated the version to 1.12.2-1.5.12, and the problem still applies. The core used in the pictures was a shuttle core, and the block count was within the 26X26X26
limit, and the 3000 block maximum. Also, in the picture, the computer is on the side, but the same result happens with the computer on top.

**Comment by LemADEC** [comment]
You version is outdated, please try again with latest version from the official repository (1.12.2-1.5.12).
You might need to replace the ship core and enable all logging in the mod configuration.
We'll need the debug.log file if that is still reproduced.

**Comment by LemADEC** [comment]
I can't reproduce it with latest mods: WarpDrive 1.12.2-1.5.12 + CC: Tweaked 1.12.2-1.86.2.

**Comment by forcemaster06** [comment]
The same problem still occurs in 1.12.2-1.5.12. I’ll enable the logging and replace the core today

**Comment by forcemaster06** [comment]
Nevermind. It appears cc: tweaked was the cause. I updated to the latest and it worked.
