### ISSUE TITLE
1.12.2 Missing Textures

### ISSUE THREAD

**Issue by BuffJokester2448** [LemADEC/WarpDrive#444]
1.12.2 Default Creative Shuttle having a random Missing Textures at back of ship and roof,pls fix this bug

**Comment by LemADEC** [comment]
Please post a screenshot and the id of the block in question.

**Comment by LemADEC** [comment]
Also, the template isn't optional. Make a new issue using the template!

**Comment by StalkerMeyr** [comment]
Hello, faced the same problem 
WarpDrive: 1.5.23
ic2: 2.8.188-ex112

![2021-07-19_12 57 09](https://user-images.githubusercontent.com/54806075/126144461-dd626285-a5c5-4e4d-9964-385d919d98e1.png)
![2021-07-19_12 57 49](https://user-images.githubusercontent.com/54806075/126144463-d9894a12-5fbb-497c-8787-780a257e31a4.png)
![2021-07-19_12 59 23](https://user-images.githubusercontent.com/54806075/126144465-261c6d97-3bae-40e6-9716-fa546f537580.png)
