### ISSUE TITLE
Gravity in space is not changed, same as overworld gravity

### ISSUE THREAD

**Issue by IteratorW** [LemADEC/WarpDrive#445]
**Describe the bug**
Using a default celestial objects config, there's still earth's gravity in space.

**To Reproduce**
1. Use the /space command
2. Experience earth gravity

**Expected behavior**
Normal space gravity

**Logs**
Link to pastebin/gist or equivalent logs

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.12
-   Forge version: 1.12.2-2838-7.2.1-RC4010
-   Modpack name/version: null
-   Other notable mods & version: list of all my mods: https://pastebin.com/3d9sRq1K

**Comment by LemADEC** [comment]
You've a conflicting mod, remove them until it works to find which one. I would start with ItemPhysics.

**Comment by IteratorW** [comment]
Alright, this is an incompatibility with GalactiCraft. And please.... aren't you going to tell that I need to remove this mod? :)

**Comment by LemADEC** [comment]
Galacticraft shouldn't interfer with gravity here. What versions are you using?

**Comment by IteratorW** [comment]
GalacticraftCore-1.12.2-4.0.2.252
Galacticraft-Planets-1.12.2-4.0.2.252
MicdoodleCore-1.12.2-4.0.2.252

**Comment by IteratorW** [comment]
also, can I ask you some questions here to not create more issues, or you're against "offtops" ?

**Comment by LemADEC** [comment]
4.0.2.244 already have the issue. We need to find which version started the regression.
Please do join Discord if you have question more than issues :).

**Comment by IteratorW** [comment]
Alright, thanks :)
My guess that the coremods are conflicting when patching. Maybe they're touching the same class or something.

**Comment by LemADEC** [comment]
1.12.2-4.0.1.184 also have the issue, sounds like I forgot to test that one.

**Comment by LemADEC** [comment]
Fixed in dev, will be in next public release

**Comment by LemADEC** [comment]
Fixed in https://github.com/LemADEC/WarpDrive/commit/cc20769d946f6571bb079e4147b1a73f0b89419e
