### ISSUE TITLE
somehow your mod affeckts vanilla worldborders

### ISSUE THREAD

**Issue by ZEROX7** [LemADEC/WarpDrive#446]
**Describe the bug**
wehn i install your mod in my personal modpack and create a new world chunk borders get shrunk to only 5k in radius and can not be moved or enlarged

**Versions** 
-   WarpDrive version: 1.5.12
-   Forge version: 14.23.5.2854 or 14.23.5.2847 doesnt rly matter wich one
-   Other notable mods & version: idk if its because of another one

here is the latest log:
https://1drv.ms/u/s!AoGi5ELkm7SZlkUTlRGt-NGjVOPS?e=edaCRJ
too big for pastebin

**Comment by ZEROX7** [comment]
just found the changlog and so its not a bug but why is the overworld size limited to only 10k?

**Comment by IteratorW** [comment]
I'm sure it depends on what you have in celestialObjects-default.xml

**Comment by ZEROX7** [comment]
waht does change wehn i change the setting in celsetialobjects-default.xml i am confused about the orbit thing that was statet in the xml

**Comment by IteratorW** [comment]
Parameter `<size x="10000" z="10000" />` in every `celestialObject` is the worldborder size. WarpDrive should affect all the worldborders in the dimensions that are specified in a celestial objects config. You can remove `celestialObject` with dimension worldborder of which you don't want to be affected.

**Comment by LemADEC** [comment]
The mod is about exploring the celestial map as defined in celestialObjects-*.xml configuration file. Flying through space implies planets have limited size so they can fit in the global map, so each dimension/planet defined as a celestial object has a virtual world border defined by the size element.
You can't reach space from or land on a planet unless it's part of the CelestialMap.

The orbit area is the region in the space dimension where your ship is considered in orbit of a planet. In this region, you can move your ship down below Y=0 to land your ship on that planet. Does that make sense to you?

**Comment by ZEROX7** [comment]
so you take the aktual world size directly and insert it into the space
dimension cords directly to have a realistic representation?

Am Di., 21. Apr. 2020 um 20:26 Uhr schrieb LemADEC <notifications@github.com

**Comment by LemADEC** [comment]
yes, there's no scaling, it's a direct 1:1 transfer.

**Comment by LemADEC** [comment]
No update for 1 week, assuming fixed

**Comment by Archilyte** [comment]
bruh
EDIT: i mean, idk if its fixed or not, but like, at least wait for the guy who made the issue to respond before closing it...
