### ISSUE TITLE
Editing a Class file

### ISSUE THREAD

**Issue by 90mindblogspotcom** [LemADEC/WarpDrive#447]
I used Recaf it solved the problem recaf is best software for hacking class files
I used set.ee JBE java bytecode editor and he doesnt have a support or forum so i cant get help.
Please Help Java Minecraft Bytecode Editor
Java Bytecode Editor cant edit Minecraft mods.
Pass 3a:
Verifying method: values
Instruction invokevirtual182 26 constraint violated: Class '[Lcom.pixelmonmod.pixelmon.battles.attacks.Effectiveness;' is referenced, but cannot be loaded: 'VERIFIED_REJECTED
Repository.lookup() failed. FILE NOT FOUND?
I opened this file said verify file without coding editing; it just cant verify file it keep saying it cant find the file but file it is looking is already open! It is searching for its own self and cant find it

**Comment by LemADEC** [comment]
This has no relation with WarpDrive. Also, Pixelmon is an illegal mod, so no support will be provided.

**Comment by 90mindblogspotcom** [comment]
:D :D But i am illegally hacking it

**Comment by cookiedragon234** [comment]
I’m able to reproduce this error using latest master of warp drive

**Comment by LemADEC** [comment]
We're not supporting illegal activites, nor trolls
