### ISSUE TITLE
Ship laser cannon does no damage

### ISSUE THREAD

**Issue by Lacunaethemoontraa** [LemADEC/WarpDrive#449]
Fairly new to this mod so I apologize if this is just a mistake on my part.

The issue Im currently having is that the laser cannon does absolutely nothing to its target regardless of material, even at point (nearly) blank range. 

the setup has a laser cam w/ 2 basic mediums connected to 3 lasers, each w/ 3 advanced mediums connected with plenty of power. everything is tuned and connected as it should be. when fired the laser does nothing at all to the target. It makes the sound and all of the beams shoot out, but even at 4 blocks from a stone target with all components charged to capacity, it fails to break any blocks. (doing this test on earth btw)

Is there some sort of config setting that I need to adjust? Is it an actual bug with my install? or am I missing something right in front of me. 

MC Version: 1.12.2
Forge: 14.23.5.2836
Warpdrive version: 1.5.12.SNAPSHOT
CC:Tweaked:1.83.1

**Comment by LemADEC** [comment]
2 basic laser mediums are nothing compare to the power you can give to those lasers. Check the official tutorial on 1.7.10 which still applies for the most part.
https://www.youtube.com/watch?v=OyORV35ojcg
