### ISSUE TITLE
The skybox in space is rendered pretty dim, depending on draw distance.

### ISSUE THREAD

**Issue by IteratorW** [LemADEC/WarpDrive#450]
**Describe the bug**
This issue isn't because of optifine - it can be reproduсed with and without it.

**To Reproduce**
1. Used clean client w/ only warpdrive for testing
2. Went to space, saw really dim skybox. Increased draw distance which made it more bright.

**Expected behavior**
Draw a skybox with brightness independent of your video settings.

**Screenshots**
Here's the skybox with lowest distance:
![2020-04-30_00 30 46](https://user-images.githubusercontent.com/30198566/80928910-96ae7e80-8db0-11ea-958f-fd2818eb4c92.png)
A little more:
![image](https://user-images.githubusercontent.com/30198566/80928917-a0d07d00-8db0-11ea-8834-f4a504592bb7.png)
Even more:
![image](https://user-images.githubusercontent.com/30198566/80928918-a5953100-8db0-11ea-87ca-6b5951749c44.png)

**Logs**
I think it's not needed, since there are no any unusual messages when this issue happens.

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2.1.5.13
-   Forge version: 14.23.5.2847
-   Modpack name/version: null
-   Other notable mods & version: null 

**Additional context**
It appears to be the same on 1.7, but a little bit different. Skybox doesn't render completely only under 4 chunks which is OK, but on 1.12 it's rendered pretty dim on 8 chunks, which is a default option, and it's not at its fullbright even at 15.

**Comment by LemADEC** [comment]
Skybox is culled at low distance to help players with flint level computers. This happens around 5 chunks of render distance. By extension, adding brightness won't help here.

Optifine used to offset the chunk range earlier in 1.12. It was also hiding asteroids behind the skybox at some point. I didn't retest it recently.

**Comment by IteratorW** [comment]
How dimming the skybox will make better performance? Like,.it still renders it at least. Or maybe I really misunderstand something /shrug

**Comment by LemADEC** [comment]
Culling means the 3D object isn't projected on screen at all.
Fog/dimming is there to avoid a sharp transition of object as they enter in the line of sight.
Those are common 3D rendering things implemented in the base game. The mod just leverage them.

**Comment by IteratorW** [comment]
Oh ok, just didn't get why the fog is needed.

**Comment by IteratorW** [comment]
Think it's not the case anymore after last updates, tests showed everything is OK. Closing.
