### ISSUE TITLE
tree farm, raw rubber

### ISSUE THREAD

**Issue by nonenothing** [LemADEC/WarpDrive#453]
**Describe the bug**
Tree farm dont get raw rubber from jungle tree.
Yes, in the jungle biom.
Yes, try with and without computer interface.

**To Reproduce**
Just try it.

**Screenshots**
Haha.

**Logs**
Funny.

**Versions** (latest is not a valid answer)
-   WarpDrive version:  1.5.13
-   Forge version: 14.23.5.2838
Other mod - IE.

**Comment by LemADEC** [comment]
There's no need for jungle biome, just the Jungle tree.
The laser needs to be in rubber collection mode, otherwise you'll get the logs.
And yes, it works with ImmersiveEngineering-0.12-92
![image](https://user-images.githubusercontent.com/4776032/82066663-ff122f80-96cf-11ea-813f-1135e9575897.png)

**Comment by nonenothing** [comment]
> in rubber collection mode

By default this mode?
And /farm 1 1 - right?

**Comment by LemADEC** [comment]
there's no /farm command. You don't need a computer, a freshly crafted farm already works for rubber collection as show on the screenshot above.

**Comment by nonenothing** [comment]
Didn't work.
And in logs only "Harvest/tap tick" - no "Tapping jungle wood"

**Comment by LemADEC** [comment]
well, you've yet to post your logs, so how would I know?

**Comment by LemADEC** [comment]
Any news on getting the logs so I can actually check what's going on?

**Comment by netherever** [comment]
Can't find any usefull in log.
For myself problem solved (some change in recipes, shame on me)

**Comment by LemADEC** [comment]
No logs provided, no help, closing
