### ISSUE TITLE
Mekansim mod doesent work with Warp Drive

### ISSUE THREAD

**Issue by TheGamingGoat** [LemADEC/WarpDrive#454]
**The Bug**
When I try jumping with almost anything related to power with Mekanism it says ship snagged.
When I try jumping with a Mekanism wind generator or a Mekanism Universal Cable it says Ship snagged at item.transmitter.name and when i jump with a wind generator it does ship snagged at tile.generator.name.

**How to repreduce**
You can reproduce this by trying to jump at all with a Mekanism cable, Wind generator and i believe a solar panel, anything that's a sorta multi block.
**Versions**
I am using the Latest version of Forge, Warp Drive and Mekanism.

**Comment by LemADEC** [comment]
Ship snagged means you dimensions are incorrect. Sneak right click the ship core to see your dimensions.
Latest isn't a version. Read the issue template and actually use it next time.
