### ISSUE TITLE
Incompatible with TARDIS mod

### ISSUE THREAD

**Issue by benjierex** [LemADEC/WarpDrive#457]
Kinda niche issue i guess, but the game crashes on startup. Works perfectly fine when i uninstall one of the two. Also it's obviously the issue if you look at the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  WarpDriveCore (WarpDrive-1.12.2-1.5.14.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/7/20 12:47 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WarpDrive (warpdrive)
Caused by: java.lang.StackOverflowError
	at net.tardis.mod.common.blocks.BlockMultiblock.getMasterState(BlockMultiblock.java:29)
	at net.tardis.mod.common.blocks.BlockMultiblock.func_176195_g(BlockMultiblock.java:92)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403)
	at net.tardis.mod.common.blocks.BlockMultiblock.func_176195_g(BlockMultiblock.java:92)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403)
	at net.tardis.mod.common.blocks.BlockMultiblock.func_176195_g(BlockMultiblock.java:92)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403)
	at net.tardis.mod.common.blocks.BlockMultiblock.func_176195_g(BlockMultiblock.java:92)
...

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 947223000 bytes (903 MB) / 1289748480 bytes (1230 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version                | Source                        | Signature                                |
	|:----- |:------------- |:---------------------- |:----------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft     | 1.12.2                 | minecraft.jar                 | None                                     |
	| LCHIJ | mcp           | 9.42                   | minecraft.jar                 | None                                     |
	| LCHIJ | FML           | 8.0.99.99              | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge         | 14.23.5.2854           | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | WarpDriveCore | 1.12.2-1.5.14.SNAPSHOT | minecraft.jar                 | None                                     |
	| LCHIJ | cctweaked     | 1.88.0                 | cc-tweaked-1.12.2-1.88.0.jar  | None                                     |
	| LCHIJ | computercraft | 1.88.0                 | cc-tweaked-1.12.2-1.88.0.jar  | None                                     |
	| LCHIJ | tardis        | 0.1.4                  | tardis-0.1.4.jar              | None                                     |
	| LCHIE | warpdrive     | 1.12.2-1.5.14.SNAPSHOT | WarpDrive-1.12.2-1.5.14.jar   | f7be6b40743c6a8205df86c5e57547d578605d8a |

	Loaded coremods (and transformers): 
WarpDriveCore (WarpDrive-1.12.2-1.5.14.jar)
  cr0s.warpdrive.core.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.75' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

Is there anything i can do locally to fix this?

**Comment by LemADEC** [comment]
Issue template is NOT optional. Use gist or pastebin for reports.
It's a Tardis issue with handling their multiblock structure, report it to them.

**Comment by LemADEC** [comment]
Dup of #439
