### ISSUE TITLE
Lasers not doing any damage

### ISSUE THREAD

**Issue by jinjungsang** [LemADEC/WarpDrive#458]
When firing the laser at anything nothing is done. It shows the beam but does nothing. Tried shooting different blocks with different hardness nothing happened. Entities don’t die either. 

**To Reproduce**
Just set up a laser cannon and fire it. 

**Expected behavior**
I expected the blocks to break/explode
**Screenshots**

**Logs**
Link to pastebin/gist or equivalent logs

**Versions** (latest is not a valid answer)
-   WarpDrive version: latest
-   Forge version: 
-   Modpack name/version: 
-   Other notable mods & version: 

**Additional context**

**Comment by LemADEC** [comment]
Laser cannon works fine on the official packs.
Your setup description is incomplete. Pictures are required, along with actual values involved.
Logs are not optional.
As the template says, latest is not a valid answer.
Forge version is not optional.

This is not a valid issue report, update it or it'll be closed without further notification.

**Comment by LemADEC** [comment]
No update for 2 weeks, assuming fixed
