### ISSUE TITLE
Air Generator Improvements

### ISSUE THREAD

**Issue by PrettyHeatToast** [LemADEC/WarpDrive#46]
I would like to suggest some improvements to the air generator.
-Make air translucent or only show the block on the edge of the air bubble.
-Increase the range of the air generator
-Make the air bubble static so it doesnt constantly change size

**Comment by LemADEC** [comment]
Air is already translucent, showing the edges unless there's a solid block. It looks a bit 'loaded' when the air is building up. An alternate option is to only show the exterior faces, like glass, but it doesn't really look natural as far as I can remember.

Air generator is supposed to cap at 15 blocks radius but it's a bit tedious to reach that range, so it's more like 10. Technically, we need a full rewrite if we want to go further than that, see related issue entry.

The bubble is dynamic to show the air leakage. Sadly, this cause a lot of block updates and consume a lot of bandwidth. My personal record is 700kB/s before it starts to lag me out with by moon carved base. Anyhow, to address that, we need a rewrite, see previous point.

**Comment by LemADEC** [comment]
There was indeed a bug in the air propagation along X+ due to MC1.7 porting. Please refer to #30 for the other issues.

**Comment by PrettyHeatToast** [comment]
The problem seems to be that air blocks inside a bubble sometimes dissappear making it look like this.
![2015-08-11_17 02 10](https://cloud.githubusercontent.com/assets/13708542/9200957/c910e074-404a-11e5-9760-bc6e49e92fc9.png)

**Comment by TheNumenorean** [comment]
Good ship design

**Comment by PrettyHeatToast** [comment]
Thanks, the outside looks a bit derpy though.

**Comment by LemADEC** [comment]
When you're walking around, you're actually breathing air. If you stay too long in place, that block will be cleared from all air.
When reloading chunks, air is no longer propagating, so you'll end up with empty blocks in the middle of your bubble. You should be able to 'kick start' it by placing/removing a block next to an air generator.

For the record, each open side count for an air generator, more open sides means faster propagation.

**Comment by TheNumenorean** [comment]
This method does not make any sense at all physics wise.

**Comment by LemADEC** [comment]
Already covered by #30, closing this
