### ISSUE TITLE
Accelerators

### ISSUE THREAD

**Issue by CTH999** [LemADEC/WarpDrive#460]
Okay, my info might be out of date, but I remember that a while back, particle accelerators didin't work in singleplayer worlds. So, my request is simple. Could that be changed to work?

Okay, so here's my soloution. From what I understood, it was the void shell, where you Desinged it to use features from the server. What I'm asking is, could you make it not require a server? I really want to make it into a weapon as you said in the wiki you could (:

**Comment by LemADEC** [comment]
Discord is there for such support requests.

**Comment by CTH999** [comment]
> Discord is there for such support requests.

Okay... great, if this was support. This is a suggestion though. I was saying "If they work on single player, great, if not, I _suggest_ making it work on single player. But, based on your responses to my other suggestions. I think you just don't care.

**Comment by LemADEC** [comment]
Discord is a communication platform. It's there to talk in writing and voice.
Ignoring my answers will get you nowhere.

**Comment by CTH999** [comment]
> Discord is a communication platform. It's there to talk in writing and voice.
> Ignoring my answers will get you nowhere.

I wasn't ignoring, I was just explaining in more depth.

Also, if suggestions are supposed to be in discord, why is there a dedicated button here? (Also, seems I should just give up on not getting a discord account)
