### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by CTH999** [LemADEC/WarpDrive#461]
I have one main pet peeve when it comes to large, complex mods. And that is lack of documentation. This wiki is great and all, but it can be annoying to have to flip between the browser and the game. And, it's always nice to have something visualize a structure in-world.

So, I suggest a guidebook (Weather you use an API (Adding a dependency), or your own), that can show a basic idea of a desing, a quick, but helpful, summary, and a link to the wiki if you need more info.

I also think it should be some sort of computer, since this is a high-tech mod, and a manual... well...

But, just an Idea
after all, it's your mod!

**Comment by LemADEC** [comment]
It's already in there, read the change logs and try the mod before asking questions

**Comment by CTH999** [comment]
> It's already in there, read the change logs and try the mod before asking questions

3 things:

- If you have an in-game guide, I sure don't see it
- What changelogs? They aren't on curseforge, can't find them here...
-"Try the mod before asking questions". Kinda "funny" (Not really), since I have been using this mod for years now, and just downloaded the newest copy (The one realesed 2 days ago). So, I must say, your comment was not only rude, it made assumptions that where wrong. (The first part was fine, but the "and try the mode before asking questions" was quite sarcastic. It doesn't take much longer to say "You really should double check, since, as mentioned in the changelogs, there is a guide." If anything, it's less wordy. Or just don't go sarcastic. I must say, I have more ideas for this mod, but I think instead I'll just not put them here.

**Comment by LemADEC** [comment]
Once again, forcing your idea instead of actually reading answers and checking:
![image](https://user-images.githubusercontent.com/4776032/85943971-e4201580-b933-11ea-8ac8-e77ececa07e6.png)

**Comment by CTH999** [comment]
> Once again, forcing your idea instead of actually reading answers and checking:
> ![image](https://user-images.githubusercontent.com/4776032/85943971-e4201580-b933-11ea-8ac8-e77ececa07e6.png)

I'm sorry if it came across rude and as if I was forcing it on you. I was just trying to put in a suggestion, and obviously the style I chose was a problem (The "I'm frustrated when". I've never been good with those...). So, sorry for sounding forcefull.

I do have one favor to ask. Could you add Patouli as a "Recomended" dependency (Optional), and maybe link it? Also, maybe add OC and CC: Tweaked as required, mentioning that only one is needed? Just a favor!

**Comment by LemADEC** [comment]
Optional dependencies have added. I thought it was an API only thing.
