### ISSUE TITLE
Computers

### ISSUE THREAD

**Issue by CTH999** [LemADEC/WarpDrive#462]
Okay, you guys have an issue. The 2 main computer mods (Computer Craft and Open Computers) aren't update much, or at all

So, here's a solution. Add your own computer system! (Obviously OC style!). This would allow you to make it exactly like you need, and it would work great with the guide idea, which is over [here](https://github.com/LemADEC/WarpDrive/issues/461). You could also add in "Base chips" (Some are loot, some are craftable, some are both, some require uncraftable loot...). These include basic operating system desings, a basic desing for an accelerator (But, with pre-set features!), lasers, transporters... but, one of them is the "basic editor", which creates a basic Drag n' Drop programing system, which makes stuff you desing, but still not as good as what you can make by programing something directly!

For instance, maybe the default warp-drive program, you can warp to a specific location, but you could write one that has an auto-piolot! Even better? The antimorphic (Whatever it's called, the one that's in the mod), doesn't have a chip, since it's powerful, you need to write your own! (Give people a reason to learn intricite coding)

Of course, his should be compatible with Open Computers (OC), Computer Craft (cc), and maybe of pnumaticraft, represurized's coding! And, systems in this allow you to interact with the world... but you know, that's up to you (Yeah, like everything else here isn't (:  )

But, this is just my idea. Ultimatly, it's your mod and your choice.

P.S. I'm positive it's compatible with OC, but if it isn't, please do that. Computer Craft isn't recieving any updates, whereas OC gets rare, sporiatic updates. Just saying!

**Comment by LemADEC** [comment]
CC: Tweaked is largely improving ComputerCraft, as already explained in the change logs...
