### ISSUE TITLE
Space has Lack of Distance

### ISSUE THREAD

**Issue by CTH999** [LemADEC/WarpDrive#463]
I know you have mentioned this in the config, I just think it _needs_ to be fixed (I'm working on a modpack, but it has a lot of planets using AR, and I want this mod to be able to get to them too. But, to take distance into account, I have to use more than the "recomended" distance. So, here's a question. Why does that distance cause issues? (The 220 km)

It's nowhere near the overworld's world border limitation, so why is it limited there? What I think you should do is create another dimension, make it like the overworld, but maybe have, instead of void, a special block that causes suffocation, but can be walked through (Warp Drive Space Air?), then planetoids could, in some cases, actualy generate a breatable atmosphere by not having this block (Breaking a block replaces it, unless it is surrounded by naturaly (Non preasurized), breathable air, in which case that's what it's replaced by.

That should give me enough distance, as should it with anyone!

But, that's just a suggestion!
Ultimatly, it's your mod!

**Comment by LemADEC** [comment]
The configuration comment tells you where and why the limitation is there, watch the video before pretending it can be changed.

**Comment by CTH999** [comment]
> The configuration comment tells you where and why the limitation is there, watch the video before pretending it can be changed.

Okay, look here. I didin't know about a video, the config, as far as I could tell, said "Charecter will start shaking, then death" (Slight summary, so I didin't find it there.

and, I'm not "pretending" it can change, I'm putting out possible workarounds. Would they work? Maybe. Maybe Not. But, just because someone comes up with an idea that you think is impossible is no reason to be rude! (Yes, that is how you came across. Rude and ungrateful)

**Comment by LemADEC** [comment]
Like I said, the video is linked in the configuration comments: https://github.com/LemADEC/WarpDrive/blob/MC1.12/src/main/resources/config/celestialObjects-default.xml#L31
You are asking for support without reading those comments, that is rude.
Answering without checking those actual comments, that is rude too.

**Comment by CTH999** [comment]
> Like I said, the video is linked in the configuration comments: https://github.com/LemADEC/WarpDrive/blob/MC1.12/src/main/resources/config/celestialObjects-default.xml#L31
> You are asking for support without reading those comments, that is rude.
> Answering without checking those actual comments, that is rude too.

I didin't mean to sound like I was asking for support, and I thought I read those comments (Obviously I missed it, eh)?

So, sorry.
