### ISSUE TITLE
Compatibility of GalacticraftCore and WarpDrive 1.12.2 

### ISSUE THREAD

**Issue by wdsjmine** [LemADEC/WarpDrive#466]
**Describe the bug**
When I play GalacticraftCore and WarpDrive 1.12.2 ,there are no monsters in the dungeons of the moon, but if I take the WarpDrive off, nothing will happen.

**Expected behavior**
There will have monsters in the moon dungeons.

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.16
-   Forge version: 14.23.5.2854
-   Modpack name/version: 1.12.2
-   Other notable mods & version: GalacticraftCore-1.12.2-4.0.2.280 GalacticraftCore-1.12.2-4.0.2.280 MicdoodleCore-1.12.2-4.0.2.280 industrialcraft-2-2.8.220-ex112 cc-tweaked-1.12.2-1.89.2

**Comment by LemADEC** [comment]
If you declare a dimension as non-breathable in WarpDrive, only mobs with the LivingWithoutAir tag will survive there.
You can enable breathing logs to see the id of entities who were rejected from spawning and add them to the dictionary configuration file.

**Comment by wdsjmine** [comment]
How to add them?

**Comment by LemADEC** [comment]
Read the dictionary configuration file, it's all explained there...

**Comment by wdsjmine** [comment]
Thanks

**Comment by wdsjmine** [comment]
How to enable breathing logs？

**Comment by wdsjmine** [comment]
I can't find breathing logs, although I search it.

**Comment by LemADEC** [comment]
enable_breathing_logs in the warpdrive/config.yml file

**Comment by wdsjmine** [comment]
How to use it?

**Comment by wdsjmine** [comment]
Sorry, I am a novice

**Comment by wdsjmine** [comment]
I open it but I can't find it, where is breathing logs.

**Comment by LemADEC** [comment]
Please don't spam comments, there's really no need to make a new comment for each line. Think of what you want to say, then write it down, then post your comments.
Also, come on the official Discord for this kind of help.
