### ISSUE TITLE
Openmodularturrets turret blocks are always considered anchors

### ISSUE THREAD

**Issue by Doobig10** [LemADEC/WarpDrive#467]
As far as I can tell, openmodularturrets turret blocks are not automatically listed in the dictionary file but are still considered anchors, upon trying to add the block (I used the disposable turret to test) It still would not overwrite this preference, Im not sure quite whats going wrong as it might be my poor understanding but I would greatly appreciate any help.

Hopefully the attachment works, had to change my dictionary to a text file for upload. If its my own stupidity I greatly apologise but I figured id ask in case.

[dictionary.txt](https://github.com/LemADEC/WarpDrive/files/4949189/dictionary.txt)

**Comment by LemADEC** [comment]
Issue template is NOT optional, Use it!
