### ISSUE TITLE
Ship not able to launch (Movement aborted! Entering protected area)

### ISSUE THREAD

**Issue by Reliphyte** [LemADEC/WarpDrive#468]
**Describe the bug**
The ship won't launch into space because of:
(Movement aborted!
Entering protected area at (-840 -335 -335).
Not enough space after adjustment.)

**To Reproduce**
Just launching the ship

**Expected behavior**
The ship starts the pre-jump checklist, the core warms up, the it says movement aborted.

**Logs**
Link to pastebin/gist or equivalent logs
https://hasteb.in/gohesujo.md (The full log is too large, if you want that I can upload it to dropbox)

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.17
-   Forge version: 1854
-   Modpack name/version: LoA Test 2.6
-   Other notable mods & version: CC tweaked 1.89.3
**Additional context**
This happens in both Singleplayer and on the modpacks server

**Comment by LemADEC** [comment]
You've a mod, plugin or spawn protection covering the area.
Remove said protection, or build away from it and you'll be fine.

**Comment by Reliphyte** [comment]
This happens away from spawn and without plugins. What are known mods that cause this?

**Comment by LemADEC** [comment]
Post your full logs with enable_break_place_logs set to true.
We'also need your mods list.

**Comment by Reliphyte** [comment]
Mods: https://gyazo.com/5ef676a2454c7482738c05bd2718093d
And how do I enable that?

**Comment by LemADEC** [comment]
it's part of the mod's configuration

**Comment by Reliphyte** [comment]
[latest.log](https://github.com/LemADEC/WarpDrive/files/4991818/latest.log)

**Comment by LemADEC** [comment]
I see no ship movement in that log...

**Comment by Reliphyte** [comment]
Towards the bottom it says it tried to moved but it was blocked.

**Comment by Reliphyte** [comment]
It might be a plugin, I tested again in SP and it worked, how can I work around this?

**Comment by LemADEC** [comment]
Those are client logs on a server, we need the server side logs.

**Comment by Reliphyte** [comment]
Here is the server side
[latest.log](https://github.com/LemADEC/WarpDrive/files/5003366/latest.log)

**Comment by LemADEC** [comment]
Log file is truncated.
Essentials and CoreProtect are errorring: remove or fix them.
It's definitely another mod or plugin cancelling the block placement. Start by removing all plugins from your setup.

**Comment by Reliphyte** [comment]
Fixed CoreProtect, sadly can't update Essentials yet.

It was TownyAdvanced causing the issues, know of any fixes? I've tried disabling it in all worlds, but it still happens.

**Comment by LemADEC** [comment]
I've yet to see Towny works properly in modded...

**Comment by Reliphyte** [comment]
I found a way to fix it, and everytime someone goes into space, it crashes the server with no log.

**Comment by Reliphyte** [comment]
Turns out, it's just the dimension generating itself...it lags the server on a 6700k...

**Comment by LemADEC** [comment]
sounds like your setup is messed-up

**Comment by Reliphyte** [comment]
What do you mean setup?

**Comment by LemADEC** [comment]
Crashes the server with no logs implies you've a hard crash in the JRE, which means your server wasn't setup properly or you have some HW failure. Either way, this is not the place for support, there's Discord for that, hence closing this ticket.
