### ISSUE TITLE
Transporter beacon does not charge

### ISSUE THREAD

**Issue by Famous5000** [LemADEC/WarpDrive#470]
**Describe the bug**
The transporter beacon simply won't charge after trying to put it next to an energy source physically and attempting to insert it directly into an RF charger.

**To Reproduce**
1.  Get a transporter beacon from creative inventory
2. Attempt to insert it into a wired charger from EnderIO or other extra energy providers

**Expected behavior**
The transporter beacon should recharge from the power stored inside of capacitors, regardless of where it was spawned from.

**Screenshots**

**Logs**
Link to pastebin/gist or equivalent logs

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.17.SNAPSHOT
-   Forge version: 14.23.5.2854
-   Modpack name/version: Custom modpack
-   Other notable mods & version: 

**Additional context**

**Comment by LemADEC** [comment]
Dup of #357
