### ISSUE TITLE
Cubic Chunks + Higher space Y level

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#472]
**Is your feature request related to a problem? Please describe.**
Its not really a problem.. I just want to use the available space there is for me to use
**Describe the solution you'd like**
Make the Y level configurable and make support for Cubic Chunks

**Describe alternatives you've considered**
Ehh.. I can't think of any other alternatives

**Additional context**
(...)

**Comment by LemADEC** [comment]
Adding CubicChunks support would require to rewrite air generators and force field data structures. As such, this won't happen on 1.12 unless someone makes a pull request addressing it.
