### ISSUE TITLE
Transport Beacon

### ISSUE THREAD

**Issue by Rebelord01** [LemADEC/WarpDrive#473]
So I was trying to charge my transport beacon as I've been toying with it, so i placed it on a creative energy cell from thermal expansion. When I placed it a nearby wire from thermal dynamics (the best one available) connected now the game crashes when ever i try to load the world 

here's the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WarpDriveCore (WarpDrive-1.12.2-1.5.18.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/7/20 10:08 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cr0s.warpdrive.block.movement.TileEntityTransporterCore.updateBeacon(TileEntityTransporterCore.java:933)
	at cr0s.warpdrive.block.movement.TileEntityTransporterBeacon.pingTransporter(TileEntityTransporterBeacon.java:131)
	at cr0s.warpdrive.block.movement.TileEntityTransporterBeacon.func_73660_a(TileEntityTransporterBeacon.java:91)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cr0s.warpdrive.block.movement.TileEntityTransporterCore.updateBeacon(TileEntityTransporterCore.java:933)
	at cr0s.warpdrive.block.movement.TileEntityTransporterBeacon.pingTransporter(TileEntityTransporterBeacon.java:131)
	at cr0s.warpdrive.block.movement.TileEntityTransporterBeacon.func_73660_a(TileEntityTransporterBeacon.java:91)

-- Block entity being ticked --
Details:
	Name: warpdrive:transporter_beacon // cr0s.warpdrive.block.movement.TileEntityTransporterBeacon
	Block type: ID #485 (tile.warpdrive.movement.transporter_beacon // cr0s.warpdrive.block.movement.BlockTransporterBeacon // warpdrive:transporter_beacon)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-7,133,-6), Chunk: (at 9,8,10 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #485 (tile.warpdrive.movement.transporter_beacon // cr0s.warpdrive.block.movement.BlockTransporterBeacon // warpdrive:transporter_beacon)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Warp Drive
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -5274335160531557962
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 335908 game time, 335908 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 7648 (now: false), thunder time: 100516 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 559416800 bytes (533 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                | Source                                              | Signature                                |
	|:------ |:------------------- |:---------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                 | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                 | 9.42                   | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                 | 8.0.99.99              | forge-1.12.2-14.23.5.2847.jar                       | None                                     |
	| LCHIJA | forge               | 14.23.5.2847           | forge-1.12.2-14.23.5.2847.jar                       | None                                     |
	| LCHIJA | WarpDriveCore       | 1.12.2-1.5.18.SNAPSHOT | minecraft.jar                                       | None                                     |
	| LCHIJA | appliedenergistics2 | rv6-stable-7           | appliedenergistics2-rv6-stable-7.jar                | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | cctweaked           | 1.89.2                 | cc-tweaked-1.12.2-1.89.2.jar                        | None                                     |
	| LCHIJA | computercraft       | 1.89.2                 | cc-tweaked-1.12.2-1.89.2.jar                        | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358              | CodeChickenLib-1.12.2-3.2.3.358-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.1                  | RedstoneFlux-1.12-2.1.1.1-universal.jar             | None                                     |
	| LCHIJA | cofhcore            | 4.6.6                  | CoFHCore-1.12.2-4.6.6.1-universal.jar               | None                                     |
	| LCHIJA | cofhworld           | 1.4.0                  | CoFHWorld-1.12.2-1.4.0.1-universal.jar              | None                                     |
	| LCHIJA | jei                 | 4.15.0.296             | jei_1.12.2-4.15.0.296.jar                           | None                                     |
	| LCHIJA | pneumaticcraft      | 1.12.2-0.11.15-398     | pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar | None                                     |
	| LCHIJA | theoneprobe         | 1.4.28                 | theoneprobe-1.12-1.4.28.jar                         | None                                     |
	| LCHIJA | thermalfoundation   | 2.6.7                  | ThermalFoundation-1.12.2-2.6.7.1-universal.jar      | None                                     |
	| LCHIJA | thermalexpansion    | 5.5.7                  | ThermalExpansion-1.12.2-5.5.7.1-universal.jar       | None                                     |
	| LCHIJA | thermaldynamics     | 2.5.6                  | ThermalDynamics-1.12.2-2.5.6.1-universal.jar        | None                                     |
	| LCHIJA | warpdrive           | 1.12.2-1.5.18.SNAPSHOT | WarpDrive-1.12.2-1.5.18.jar                         | f7be6b40743c6a8205df86c5e57547d578605d8a |

	Loaded coremods (and transformers): 
WarpDriveCore (WarpDrive-1.12.2-1.5.18.jar)
  cr0s.warpdrive.core.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by LemADEC** [comment]
Your version is outdated, update and post your new logs or close the issue

**Comment by LemADEC** [comment]
No update, assuming fixed
