### ISSUE TITLE
cant attach modems to force field in 1.12

### ISSUE THREAD

**Issue by iceyrazor** [LemADEC/WarpDrive#474]
on the 1.12 version of this mod, i can not attach computer craft modems to the force field projector

**Comment by LemADEC** [comment]
The issue template isn't optional, use it!

**Comment by iceyrazor** [comment]
when i opened this post it did not pop up for some reason

**Comment by iceyrazor** [comment]
**Describe the bug**
on the force field projector, i can not place a computer craft modem to it
but when i set a computer next to it, and put in the computer interface item. works fine

**To Reproduce**
Steps to reproduce the behavior:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error
dont understand these inputs. but its pretty self explanatory to the description of the bug.
have cc-tweaked (computercraft) 1.12.2 1.89.2
and warp drive 1.12.2 1.5.19
try to place a wired modem on a forcefield projector block... you cant

**Expected behavior**
the ability to place wired modems on the force field projector block. so that i can hook up my own massive controller script

**Screenshots**
If applicable, add screenshots to help explain your problem.
not really needed

**Logs**
Link to pastebin/gist or equivalent logs
bug does not cause any console errors or warnings so not needed

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.19
-   Forge version: 1.12.2
-   Modpack name/version: no mod pack.
-   Other notable mods & version: cc-tweaked 1.82.2

**Additional context**
i belive its just somthing you forgot to add when updating the mod. should this be considered a feature request??? idk :/

**Comment by LemADEC** [comment]
ComputerCraft wireless modems only connect with computers. They're extension devices to it, they're not universal remote block access thingies.
ComputerCraft wired modems exists in 2 forms:
- the panel, which requires a full solid face to be placed,
- the full block which can be placed anywhere.
You need to use the latest for the Forcefield projector.

**Comment by iceyrazor** [comment]
please give me time time actully post, this is not solved. (i only just realized)

the modems can attach to the cloaking block and ship core and the bottom side of the force field relay. and when i do. it gives the computer registered commands such as "enable" ect

on the 1.7.10 version of the mod, you can attach wired modems to the force field projector. so why was this not allowed in this version???

**Comment by LemADEC** [comment]
It's allowed to connect with the full block version of the wired modem. The change in behavior is due to the model of the project which changed a couple times over the last year.

**Comment by iceyrazor** [comment]
ah ok

**Comment by iceyrazor** [comment]
that worked thanks. idk why i didn't try that. ill close this now

**Comment by iceyrazor** [comment]
also, even though i figured it out. i found a mis phrasing on text. please see this https://github.com/LemADEC/WarpDrive/issues/475
