### ISSUE TITLE
Galacticraft oxygen system support

### ISSUE THREAD

**Issue by Cr3nydFalc0nSK** [LemADEC/WarpDrive#476]
I'm always frustrated when I have to make another set of a space suit, because I can't use GC ones in warp drive space dimension. Warp drive is so amazing mod, I admire him very much, how he can keep combatibility with other mods despite its complexity. But one thing, which which is apparently forgotten is compatibility with GC or AR oxygen system (or just space suit). There are many reasons to prefer a GC system over a WD system.

I think the easiest way to solve it, is simply when I wear GC oxygen mask, tanks, Warp drive will it recognise that I'm wearing the space suit and it won't show me any warnings or take damage. It will also work on celestial objects with breathable = false.

Thank you for understanding and reading my feature request.

**Comment by LemADEC** [comment]
Templates for issues and features aren't optional.
GC and AR oxygens are laggier and incompatible with WarpDrive.
WarpDrive oxygen is supported in any dimension declared in the celestial map, notably disabling GC oxygen system in such dimensions.
