### ISSUE TITLE
Reactor Effects missing

### ISSUE THREAD

**Issue by yeetmcskeet11** [LemADEC/WarpDrive#477]
For some reason the reactor is not displaying the effects. I have tried removing all other mods including optifine. I have been running the latest verion of the mod but i have worked my way down a few versions to see if was just an issue with the current version. I have tried a fresh install of minecraft as well.

**Expected behavior**
I played with this mod some time last year and was impressed by the star like effect that the reactor produced. I can not rerember the version i was running though.

Currently when i start the reactor the containment lasers target where the center of the effect should be, the reactor functions fine genirating energy but for some reason the blue cylinder thing on the top of the reactor block just sits there. 

![2020-12-03_20 39 57](https://user-images.githubusercontent.com/53002374/101001549-02f19a80-35ab-11eb-89c7-fc6e9410b268.png)
![2020-12-03_20 39 48](https://user-images.githubusercontent.com/53002374/101001083-65966680-35aa-11eb-956d-5ebe69cdb7e7.png)

Versions
-   WarpDrive version: 1.5.19 Release for 1.12.2
-   Forge version: 14.23.5.2854
-   Other notable mods & version: cc-tweaked-1.12.2-1.89.2

Spent the last two hours tinkering with just about everything and im at wits end. Help please before i end up pulling out my hair

**Comment by LemADEC** [comment]
It's a forge change that broke it some time ago

**Comment by LemADEC** [comment]
Turns out I've also broken it, so yeah...
