### ISSUE TITLE
Landing and boarding craft(ships)

### ISSUE THREAD

**Issue by TheGoldenDragonofepicness** [LemADEC/WarpDrive#478]
So my idea is landing/boarding craft. Smaller ships that require power just like normal ships that a player would build. This would be capable of entering space just like a normal ship. Before use, you would need to charge them. You would charge them by landing them on a charging pad(a 3x3 structure a player would build). When the charging pad is receiving power and there is a landing/boarding craft on it, it would charge them up. This landing/boarding craft would behave more like a mount. You would directly control them instead of. They would have passenger seats and possibly weapons(maybe as an upgrade). They would allow easier short distance transportation and make moving items up from the overworld to a ship that's too big to enter the overworld much easier. They would drain through their power fairly quick though. I thought this would be fun because it would allow for the transportation of players and resources. Additionally, they could have a small inventory.

**Comment by LemADEC** [comment]
You can already use a shuttle (un)docking from a space ship to move players and resources.
You can also do that with the transporter setup.
Adding a flyable entity with custom volumes is whole mod by itself with its own issues and doesn't add much to what's already provided here.
