### ISSUE TITLE
Leviathans and mapping

### ISSUE THREAD

**Issue by TheGoldenDragonofepicness** [LemADEC/WarpDrive#479]
So this is more of 2 ideas in one. So my first idea is a configurable option for a new mob that could be added. The Leviathan. They would be turned off by default. How they would work is that when they are turned on, ia f player stays in one place for too long, they would spawn and attack the player, and the ship. They would target the player first, but they would also go for the ship's power source. They would be able to do a lot of damage and break blocks in order to reach their goal. Upon the player leaving the area, despawn. If they are teleported with the ship, they will despawn. My second idea is "holo-map". Basically, a way to automatically map uncharted space with a cool looking device. It would be a block that takes up a 2X2 area. it would be slightly shorter than a normal block. When it's powered, it would display a map of everywhere the ship has been. When right-clicked on, it would open up a GUI so a player can move around where it's displaying.

**Comment by LemADEC** [comment]
Similar ideas are already part of the roadmap. Thanks for the suggestion.
