### ISSUE TITLE
Laser revamp

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#48]
This issue tracks ideas on how to modify the current laser cannon in terms of gameplay

As a follow-up from #36, @lellasone said

> • Adding mechanics where larger lasers spend more of their energy in explosion (vs penetration) could make for more interesting design and combat choices about how large of a laser to use. (It would also make all those variable length designs much more justifiable)
> 
> • Similarly adding some kind of block vs shield tradeoff with frequency could make for much more interesting tactical combat. (having shield blocks treated as say 15 blocks of reinforced stone with that number variable with frequency at a trade off against block damage efficiency)

Before I took over the mod, explosion were making massive damage, over 200+ blocks radius. I've nerfed it to focus on other bugs until we agree on proper scale of effects.
Currently, as of 1.3.2, the laser boosting is needed to break iridium block hull. It should be also useful to damage forcefield, which requires an area effect, with some kind of 'memory' (currently, ARS/MFFS are based on straight on/off state of each block).

I like the idea of adjusting the laser efficiency against a given block depending on its frequency.

In both cases, we need a few examples to put that into an equation.

**Comment by lellasone** [comment]
Some kind of damage effect on force fields would be a very cool (and important) mechanic.  Are you thinking penetration as well or more of what the EMP (originally) did to MFFS force fields? 

What are you thinking of in terms of examples? do you mean using in-game mechanics or trying to work back from real world laser behavior. (I would be happy to help find options in any case)

**Comment by LemADEC** [comment]
I was thinking about cumulative effect. Currently, it's one shot kills the force field. I would prefer a 'charge' diminishing with shot fired and increasing with field generator production.

I've tried the 'realistic' route and it would implies to rewrite the core mechanisms of the game, so not really good.
We could do a first run of examples with something like:

| Main laser level | 2nd booster laser level | block | effect |
| --- | --- | --- | --- |
| 1 | none | dirt | broken |
| 1 | none | stone | no effect |
| 2 | none | stone | broken |
| 4 | none | obsidian | broken |
| 8 | 3 | iridium block | broken |

or a matrix, google doc is your friend :)

**Comment by LemADEC** [comment]
Fixed in 60d30163386508877919aebfc3e51f444994fda0
