### ISSUE TITLE
Incompatibility with WarpDrive and The New Tardis Mod

### ISSUE THREAD

**Issue by LocusHydra** [LemADEC/WarpDrive#482]
My game crashed on startup...

launch the game with WarpDrive and The New Tardis Mod

![crash](https://user-images.githubusercontent.com/75547092/106555234-296c7d00-64eb-11eb-8e13-0390c53b36c8.png)

**Crash Report**
https://pastebin.com/4BMrh1K0

**Versions** 
-   WarpDrive version: WarpDrive-1.12.2-1.5.19
-   Forge version: 14.23.5.2824

**Other Mods** 
- foamfix-0.10.11-1.12.2, 
- JustEnoughIDs-1.0.3-48, 
- OptiFine_1.12.2_HD_U_F5, 
- tardis-0.1.4A,

**Comment by LemADEC** [comment]
Dup of #436
This is bug in the TARDIS mod, nothing we can do on our side.
