### ISSUE TITLE
java.lang.RuntimeException and Chunkloading spam

### ISSUE THREAD

**Issue by DocCyblade** [LemADEC/WarpDrive#484]
**Describe the bug**
Upon updating from 1.12.2-1.5.20 to 1.12.2-1.5.21 our server has started to lag and at one point crashed. Looking into the crash logs we found the errors "java.lang.RuntimeException" along with a ton of spam in the logs. It does this on a server and on single player mode. 

You can download the mod pack from Curse
https://www.curseforge.com/minecraft/modpacks/squirrelpak-mc12/files

**Logs**
https://gist.github.com/DocCyblade/fd22188081f5ef153b1249d3898a099e

**Versions**
-   WarpDrive version: 1.12.2-1.5.21
-   Forge version: 14.23.5.2854
-   Modpack name/version: SquirrelPAK MC 12 / V0.6.0-RC1

**Additional context**
We had no issues reported until we updated to 1.12.2-1.5.21. I tested this rolling back to  1.12.2-1.5.20 and no issues are noted.

**Comment by LemADEC** [comment]
1.5.21 is a bad build as I forgot to disable some developer only stuff.
You can try disabling the chunk reloading logs in the configuration for now, or rollback to 1.5.20 until a new version comes out.

**Comment by LemADEC** [comment]
From a quick check at that modpack, consider using LittleTiles instead of Chisel'n bits. The latest won't work with WarpDrive's ship rotation.

**Comment by DocCyblade** [comment]
@LemADEC Thanks for the feed back. Is the debug logging causing the java.lang.RuntimeException? I will take a look at LittleTiles.

**Comment by LemADEC** [comment]
Those Exceptions are there to track down chunk reloading issues, they're not errors per say.

**Comment by DocCyblade** [comment]
Gotcha, I will revert to .20 and I checked out LittleTiles, looks like a good drop in replacement. Thanks again

**Comment by LemADEC** [comment]
This is fixed in version 1.12.2-1.5.22. You still need to disable the chunk_reloading logs in the configuration.
