### ISSUE TITLE
[Question] about warp

### ISSUE THREAD

**Issue by Exzept1on** [LemADEC/WarpDrive#486]
I can't teleport to hyperspace. I connected 6 EV-level lines to the core. But it is still written that there is not enough energy.
![2021-04-02_18 31 55](https://user-images.githubusercontent.com/52341158/113415832-3bcf3e00-93ea-11eb-8aa4-7afc64d8d79a.png)

**Comment by LemADEC** [comment]
Issue template is mandatory.
Shuttle are too small to reach hyperspace, read the tool tips.
