### ISSUE TITLE
[Feature] Using galacticraft equipment in space

### ISSUE THREAD

**Issue by Exzept1on** [LemADEC/WarpDrive#489]
**Is your feature request related to a problem? Please describe.**
I can't breathe in space using galacticraft equipment

**Describe the solution you'd like**
Add to the config file, things that you could wear to breathe in space or use for this. Or add simple spacesuit support from Galacticraft and ExtraPlanets.

**Describe alternatives you've considered**
Config file in which you can specify what items will not be spent on health in space.

**Additional context**
No.

**Comment by LemADEC** [comment]
already doable through the dictionary configuration

**Comment by Exzept1on** [comment]
😊 Thanks
