### ISSUE TITLE
Error ic2 in default ships

### ISSUE THREAD

**Issue by StalkerMeyr** [LemADEC/WarpDrive#493]
Hello, an error with the ic2 mod in the default ships
WarpDrive: 1.5.23
ic2: 2.8.188-ex112
![2021-07-19_12 57 49](https://user-images.githubusercontent.com/54806075/126145166-7311d77b-f252-439e-a5e7-27f4a08cc099.png)
![2021-07-19_12 59 23](https://user-images.githubusercontent.com/54806075/126145168-72c6886d-8177-4c9f-b869-52a7e1f8da7e.png)
![2021-07-19_12 57 09](https://user-images.githubusercontent.com/54806075/126145169-9b83dcf0-0d8d-4155-a4f2-63d8817a7259.png)
Do you need logs?

**Comment by LemADEC** [comment]
That's a bug in IC2 that fails to implement the ITileEntityProvider interface in their base BlockTileEntity class. This is required for all blocks with TileEntity to registrer that interface. Until they fix it, you'll get corrupted blocks like the one shown in black and purple in your screenshot.

**Comment by StalkerMeyr** [comment]
So we just have to wait?

**Comment by LemADEC** [comment]
You would have to report the bug to them, assume they still support 1.12.2 and wish to fix it, then wait for the fix.

**Comment by LemADEC** [comment]
Not upgrade for 6+ months, not a WarpDrive issue
