### ISSUE TITLE
Enantiomorphic Reactor lasers are visible while cloaked.

### ISSUE THREAD

**Issue by jhammerberg** [LemADEC/WarpDrive#496]
Enantiomorphic reactor stabilization lasers are visible even while they're under and tier two cloak.

To reproduce simply create a reactor and cloak it using a cloaking array and back away for the cloak to take affect.

Expected behavior should be that the reactor lasers should disappear, otherwise the cloak's purpose would be useless.

![Inked2021-08-08_22 47 35_LI](https://user-images.githubusercontent.com/22381811/128656104-c512631b-7df0-4038-8466-f31e20c5ad19.jpg)
(the reactor setup in the background wasn't in the cloaking area.)
![2021-08-08_22 47 40](https://user-images.githubusercontent.com/22381811/128656107-d3191535-681e-47ab-8ae6-b7434e0e321e.png)

I am using Warpdrive 1.5.20, and the results were taken from World War Minecraft 11. If this issue has already been resolved in the latest version then could you please update World War Minecaft's version so that my base can remain hidden.

**Comment by jhammerberg** [comment]
Adding on that: it seems like lift lasers are also visible while cloaked

**Comment by LemADEC** [comment]
Particles effects aren't cloaked, that's a change from 1.12 due to the way particles are handled now.

**Comment by LemADEC** [comment]
Fixed in dev
