### ISSUE TITLE
Ship Controller

### ISSUE THREAD

**Issue by DustedRyuki** [LemADEC/WarpDrive#497]
This is more of a question and a report, When i got do the inner workings of the ship, theres no ship controller on the 1.12.2 version of the mod? I'd love to know why since i wanna get my ship working.  also the Remote ship controller dosent work.

Btw It'd help if theres some tutorials on how to use the 1.12.2 version with open controllers.

**Comment by LemADEC** [comment]
Github is for issues. Support goes on the official Discord.
There's a pinned message in mod's channel with the most notable changes on 1.12.2.
