### ISSUE TITLE
Massive ship not jumping

### ISSUE THREAD

**Issue by rieling** [LemADEC/WarpDrive#498]
Hello my problem is i jerry rigged the configs to allow massive ships i built a star wars venator that is quite massive about 448 blocks wide and i tried to warp it and it doesnt warp in the command prompt i get the thread

[00:02:54] [Server thread/INFO] [warpdrive]: TileEntityShipCore 'Venator' @ world (-130 94 -152) Connected, EXECUTE, Enabled, 2 controllers, warm-up 0, cool down 0

EXECUTE as if its in command

do you know what the problem is and if theres a way to make it jump or if me jerry rigging your code was a bad desicion

**Comment by LemADEC** [comment]
There's an issue template, it's not optional, use it.

**Comment by LemADEC** [comment]
No update for 19 days, no logs provided, no template followed, hence closing
