### ISSUE TITLE
Transformation failed for net/minecraft/world/chunk/Chunk (0/1), aborting...

### ISSUE THREAD

**Issue by infiniteblock** [LemADEC/WarpDrive#499]
Warpdrive throws the following error with spongeforge:
[main/ERROR] [WarpDriveCore]: Transformation failed for net/minecraft/world/chunk/Chunk (0/1), aborting..
Without Spongeforge it says its a client-side only transformation .

Is this going to cause issues or?

**To Reproduce**
1.  Setup clean forge server
2.  Add spongeforge
3.  Start server
4.  Read log.

**Expected behavior**
Skip this transformation?

**Screenshots**
N/A

**Logs**
Forge without sponge: https://pastebin.com/7ZggumMD
Forge & Sponge:  https://pastebin.com/NvSm7PAk

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.23 
-   Forge version: 1.12.2 - 14.23.5.2855 (Recommended)
-   Modpack name/version: Intergalactic Conflict
-   Other notable mods & version: 
SpongeForge 1.12.2-2838-7.3.0 (Recommended)

**Additional context**
N/A

**Comment by infiniteblock** [comment]
Outputs of 
FMLLoadingPlugin.logger.info(Thread.currentThread().getName());

Client Side
[20:30:23] [Client thread/INFO] [WarpDriveCore]: Client thread
Forge
[20:34:20] [Server thread/INFO] [WarpDriveCore]: Server thread
Spongeforge
[20:36:40] [main/INFO] [WarpDriveCore]: main

https://github.com/LemADEC/WarpDrive/blob/8da67d506ff76bc1d0d7590899b52bf3418f53b3/src/main/java/cr0s/warpdrive/core/ClassTransformer.java#L663

if ( Thread.currentThread().getName().equals("Server thread")
          || Thread.currentThread().getName().equals("main")) {

**Comment by zediious** [comment]
Can confirm this as well on a SpongeForge server running latest WarpDrive version.

`[04:20:51] [main/ERROR] [WarpDriveCore]: Transformation failed for net/minecraft/world/chunk/Chunk (0/1), aborting...`

**Comment by LemADEC** [comment]
It's client side only transformation, there's no consequence from failing this on a server.
