### ISSUE TITLE
Can't break hull blocks WarpDrive-1.12.2-1.5.21 - WarpDrive-1.12.2-1.5.23

### ISSUE THREAD

**Issue by infiniteblock** [LemADEC/WarpDrive#500]
After building a ship and jumping it once it does its update check you can no longer break hull blocks in survival (with or without a security station). Tested with fresh map,fresh forge server with no spongeforge ect. version WarpDrive-1.12.2-1.5.20 works fine o_O so does your wwm server? hmm

place enough hull blocks to get min mass, place a core and power source with pc, jump it , wait for the ship to check its self then attempt to break some hull....

Ship should let players break hull without security station or follow the security station intended behavior.

**Logs**
N/A no errors produced

**Versions** (latest is not a valid answer)
-   WarpDrive version: WarpDrive-1.12.2-1.5.21 to WarpDrive-1.12.2-1.5.23
-   Forge version: 1.12.2 - 14.23.5.2855
-   Modpack name/version: 
-   Other notable mods & version: 
CC:T cc-tweaked-1.12.2-1.89.2

**Comment by infiniteblock** [comment]
just compiled WarpDrive-1.12.2-1.5.23 with the PlayerHandler.java & WorldHandler.java from version WarpDrive-1.12.2-1.5.20 and it fixes the issue with breaking blocks after jump but of course isn't the ideal fix.

**Comment by infiniteblock** [comment]
this bug cant be reproduced in single player worlds

**Comment by infiniteblock** [comment]
![image](https://user-images.githubusercontent.com/5800555/131431303-e85bb86e-cc2a-477d-a309-35d02bc38572.png)

**Comment by zediious** [comment]
Can confirm this bug, unable to break hull blocks at all after initiating a jump, server-side only.

**Comment by infiniteblock** [comment]
adding the "return;" seems to correct this issue... also at first i did event.settCanceled(false); first and that seemed to work....

`private` void doCancelEventForNonMembers(@Nonnull final PlayerEvent event,
	                                       @Nonnull final BlockPos blockPos, @Nonnull final IBlockState blockState) {
		final EntityPlayer entityPlayer = event.getEntityPlayer();
		final boolean isCrewMember = checkMaintenanceAndCrew(event, entityPlayer, blockPos, blockState);
		
		// restrict mining/access to members only
		if ( !isCrewMember
		  && !entityPlayer.isCreative() ) {
			if (Commons.throttleMe("cancelingEventForNonMember")) {
				WarpDrive.logger.info(String.format("Cancelling event for non-member %s",
				                                     entityPlayer));
			}
			event.setCanceled(true);
		}
		WarpDrive.logger.info(String.format("NOT Cancelling event for member %s",
				                                     entityPlayer));
		return;
	}`

**Comment by infiniteblock** [comment]
The code I used is not going to fix I tested in single player where the bug isn't in effect

**Comment by infiniteblock** [comment]
Running version WarpDrive-1.12.2-1.5.20 on Client and WarpDrive-1.12.2-1.5.23 Compiled as mod_version=1.5.20 stops the bug..

**Comment by infiniteblock** [comment]
are you going to acknowledge this or should i get more people to just keep reporting it?

**Comment by LemADEC** [comment]
Disrespectful to the author, hence closing
