### ISSUE TITLE
WarpDrive - Ae2 bug

### ISSUE THREAD

**Issue by infiniteblock** [LemADEC/WarpDrive#501]
**Describe the bug**
jump a ship into a chunk that spawns a ae2 meteor deletes the ship when meteor spawns

**To Reproduce**
1.  jump a ship into a chunk that a meteor spawns in at same time....

**Expected behavior**
your ship to land.

**Screenshots**

**Logs**
log only shows successful jump

**Versions** (latest is not a valid answer)

WarpDrive version: WarpDrive-1.12.2-1.5.21 to WarpDrive-1.12.2-1.5.23
Forge version: 1.12.2 - 14.23.5.2855
CC:T cc-tweaked-1.12.2-1.89.2
appliedenergistics2-rv6-stable-7.jar

**Additional context**
Guess you wont fix this too? oh well we patched it for now

**Comment by infiniteblock** [comment]
Oh this is soo funny you just ignore any bug i post because your soo upset lmao

**Comment by LemADEC** [comment]
Disrespectful to mod author, hence closing.
