### ISSUE TITLE
Mod author attitude.

### ISSUE THREAD

**Issue by infiniteblock** [LemADEC/WarpDrive#502]
You know you just proved everyone's point on you, you are a child deliberately not fixing bugs in an attempt to stop others hosting servers of  the mod you chose to take over development of and attempt to make private, this is why you have no staff and no players. Thank God I no longer play on your scummy pay to play server seems your user base moved to mine as well 🔥(funny you try to trash talk me but I have your entire player base)

**Comment by LemADEC** [comment]
Salty and disrespectful, once again
