### ISSUE TITLE
IC2 Classic energy system breaks after jumping to the previous position

### ISSUE THREAD

**Issue by NCrashed** [LemADEC/WarpDrive#503]
**Describe the bug**
IC2 classic energy system breaks if one jumps forth and back at the same location. Important note that cables have to be replaced in different layouts either the bug doesn't reproduce. When the bug has occurred the energy system might be broken and the core might lose power, it depends on new and old layout differences. 

**To Reproduce**
1.  Build a ship, place some glass cables and several machines.
2.  Jump +10 Y
3.  Important! Rebuild energy network, break some cables and place the other way.
4.  Jump -10 Y
5.  See that cables are connected to old positions where they were at step 1.

**Expected behavior**
Cables don't connect to empty spaces or blocks that should be connected to them.

**Screenshots**
![2021-10-06_03 32 41](https://user-images.githubusercontent.com/2116167/136122970-cfca7f27-26ab-4ff9-9f9a-ba1481d0ebba.png)
![2021-10-06_03 33 16](https://user-images.githubusercontent.com/2116167/136122974-e9a98aa6-f2d0-4b68-ad78-03b2dc3a2b47.png)
![2021-10-06_03 34 03](https://user-images.githubusercontent.com/2116167/136122984-92429879-f8bc-470c-bfea-5410442622e6.png)

Breaking and replacing bugged cable portions does not fix the problem. Here the cable was completely removed, then layed out differently and MFSU was added on top of the bugged portion (which is protruding upwards). MFSU appears connected but does not charge.

![photo_2021-10-06_03-49-55](https://user-images.githubusercontent.com/2116167/136123553-22b40c99-ca47-4f13-9279-03a3aeef31ce.jpg)

Another way to reproduce is to jump back to the previous position minus or plus one block without rebuilding the network, like jumping 10 blocks up and 11 blocks down. The cables will appear like they are trying to merge with "phantom cables" by one block.

![photo_2021-10-06_03-33-52](https://user-images.githubusercontent.com/2116167/136123594-f34eef73-e0ad-45b8-b7ea-58b5bc44bc36.jpg)
jpg)
![photo_2021-10-06_03-51-11](https://user-images.githubusercontent.com/2116167/136123619-1d868edc-3264-42da-90e6-000c29506b8c.jpg)

**Logs**
Please, ignore errors about missing block types from other mods. I removed all other mods that are not needed to reproduce the bug from the client.

https://gist.github.com/NCrashed/857e37992814ca2e784224342160fd60

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2 1.5.23 (latest git)
-   Forge version: 1.12.2-14.23.5.2847-PROJECT
-   IC2Classic+1.12-1.5.5
-   cc-tweaked-1.12.2-1.89.1

** Additional context**

The broken energy system can be fixed by restarting a single-player session or server.

**Comment by LemADEC** [comment]
`World::removeTileEntity()` is calling `TileEntity::invalidate()`.  
In the case of IC2 Classic `BasicEnergyTile::invalidate()` calls `BasicEnergyTile::onChunkUnload()` which disconnects from the energy network through `EnergyTileUnloadEvent`.  
So this feels like an IC2 Classic issue at play here.

**Comment by NCrashed** [comment]
I tried to call `BasicEnergyTile::onChunkUnload()` explicitly but it didn't help. 

Also, I noticed that there are two bugs. One is server-side when a cable is not removed from the energy network and the second one is client-side when surrounding cables change their model to connect to the phantom cell of the energy grid.

**Comment by LemADEC** [comment]
That confirms there's a bug in IC2 Classic handling of invaliding tiles and, probably unloading chunks. So, we can add a workaround for the ship jumping case, but any server using that mod is still exposed to memory leaks.
Can you do the same test with IC2 Experimental?

**Comment by LemADEC** [comment]
IC2Classic+1.12-1.5.5.2.1 reproduces the issue, while industrialcraft-2-2.8.221-ex112 doesn't.
Thanks for your suggested fix. I've found a more generic way to solve it directly in the sequencer, that should improve compatibility with other mods.
