### ISSUE TITLE
Elytra in space makes people fly upwards when used

### ISSUE THREAD

**Issue by Kistras** [LemADEC/WarpDrive#508]
**Describe the bug**
Elytra in space makes people fly upwards when used

**To Reproduce**
1.  Equip elytra
2.  Go in space
3.  Fly
4.  Y goes brrrr

**Expected behavior**
Being unable to fly/not being yeeted into infinity

**Video**
[Here (will download 8MB video)](https://cdn.discordapp.com/attachments/526089596765995038/913833596173828096/2021-11-26_21-44-30.mp4)

**Logs**
That thing does not produce any logs

**Versions**
-   WarpDrive version: 1.5.23
-   Forge version: 14.23.5.2855
-   Modpack name/version: 1.12.2
-   Other notable mods & version: 
mekanism 9.8.3.390, opencomputers 1.7.5.192, optifine HD U G5, emoticons 1.0.1

**Additional context**

**Comment by LemADEC** [comment]
Elytra lore and effects are based on atmosphere so it shouldn't work without one, notably in space and hyperspace.
Elytra will still have over/undersized push with non-vanilla gravity, but that's expected and fun, so we'll keep it for now.
Fixed in dev.
