### ISSUE TITLE
i want to expand the world border but it keeps crashing

### ISSUE THREAD

**Issue by xXspeedfistXxD** [LemADEC/WarpDrive#509]
ok so im trying to expand the world border to 150k blocks so i can get the infinity stones but i try and increase it and every time it crashes could you please help here are the .xml files
[celestialObjects-Galacticraft+ExtraPlanets.zip](https://github.com/LemADEC/WarpDrive/files/7656995/celestialObjects-Galacticraft%2BExtraPlanets.zip)
s

**Comment by LemADEC** [comment]
There's an issue template, it's not optional, use it or your issue will be ignored.

**Comment by xXspeedfistXxD** [comment]
> There's an issue template, it's not optional, use it or your issue will be ignored.
ok do i create a new issue or is there a way to edit this one im new to git hub

**Comment by LemADEC** [comment]
you edit through the "..." menu or create a new issue, up to you
