### ISSUE TITLE
Construction Foam Glitches

### ISSUE THREAD

**Issue by PrettyHeatToast** [LemADEC/WarpDrive#51]
-When you cover cables in construction foam and then warp the ship with the cables on it the cables will lose the foam*.

-Construction foam will return to the standard texture after being warped*.

*These effects  seems to be visual and only happens to some pices of construction foam and not all the time.

Image:
![2015-08-11_20 41 50](https://cloud.githubusercontent.com/assets/13708542/9206708/b4de80e2-4069-11e5-826e-f0ac82da2c18.png)

**Comment by LemADEC** [comment]
That's interesting.
Can you try to reproduce with a ship having less than 3k blocks?

**Comment by LemADEC** [comment]
Bug is confirmed, related to IC2 client/server sync

**Comment by LemADEC** [comment]
For IC2, this impacts at least:
- [x] cables in construction foam
- [x] cables and construction foarm colors
- [x] active machines
- [x] heat generator orientation (filtering bug fixed)
- [x] reactor particle effects (IC2 bug, nofix)
- [x] mass fabricator sound effect (tested: it's not needed)
- [x] private blocks (code review says it's not needed)

**Comment by LemADEC** [comment]
Fixed in 9788ade634160befe6c6a58ad18b0a1f9dac0683
