### ISSUE TITLE
Unable to Make the world border bigger

### ISSUE THREAD

**Issue by xXspeedfistXxD** [LemADEC/WarpDrive#510]
**Describe the bug**
I am unable to edit the world border to the size I want and request assistance

**To Reproduce**
1.  Go to C:\Users\.........\curseforge\minecraft\Instances\the pack of fun\config\warpdrive
2.  Click on celestialObjects-default.xml and celestialObjects-Galacticraft+ExtraPlanets.xml
3.  Scroll down to z and x sizes and try to increase the size over 100k
4.  save changes and start game 
5.  See error

**Expected behavior**
it crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/95593769/144951877-c30f94cf-dfee-4b69-a887-bd6ae62fd980.png)

**Logs**
[Link to pastebin/gist or equivalent logs](https://paste-bin.xyz/20964)

**Versions** (latest is not a valid answer)
-   WarpDrive version: WarpDrive-1.12.2-1.5.23.jar
-   Forge version: 14.23.5.2855
-   Modpack name/version: The Pack of Fun 1.12.2
-   Other notable mods & version: appliedenergistics2-rv6-stable-7.jar | AsmodeusCore-1.12.2-0.0.28.jar | cc-tweaked-1.12.2-1.89.2.jar |  
CommonCapabilities-1.12.2-2.4.8.jar | conarm-1.12.2-1.2.5.10.jar | Draconic-Additions-1.12.2-1.17.0.45-universal.jar | Draconic-Evolution-1.12.2-2.3.28.354-universal | ExtraPlanets-1.12.2-0.7.3.jar | GalaxySpace-1.12.2-2.0.17.jar | GalacticraftCore-1.12.2-4.0.2.280.jar | HeroesExpansion-1.12.2-1.3.5.jar | jei_1.12.2-4.16.1.301.jar | MatterOverdrive-1.12.2-0.7.1.0-universal.jar | More-Planets-1.12.2-2.2.1-GC280.jar | MorePlanetsExtras-1.12.2-1.0.jar | StarMaker-1.12.2-0.0.4.jar | twilightforest-1.12.2-3.11.1021-universal.jar | 
TConstruct-1.12.2-2.13.0.183.jar | WarpDrive-1.12.2-1.5.23.jar

**Additional context**
my configs for warpdrive [celestialObjects-Galacticraft+ExtraPlanets.zip](https://github.com/LemADEC/WarpDrive/files/7664922/celestialObjects-Galacticraft%2BExtraPlanets.zip)

**Comment by LemADEC** [comment]
The map needs to pass the consistency checks at boot. There's many comments in the default celestial map (celestialObjects-default.xml) that explain how it works. You can use a map viewer pinned in the official discord channel to help you visualize the map. There's a few dedicated pages to read also in the in-game manual that explain the context.  
When consistency check fails, the crash logs tells you what text to look in the full logs to understand the issue.

**Comment by xXspeedfistXxD** [comment]
could you send a link to the discord server or where the link is for the discord server please and thank you

> The map needs to pass the consistency checks at boot. There's many comments in the default celestial map (celestialObjects-default.xml) that explain how it works. You can use a map viewer pinned in the official discord channel to help you visualize the map. There's a few dedicated pages to read also in the in-game manual that explain the context. When consistency check fails, the crash logs tells you what text to look in the full logs to understand the issue.

**Comment by LemADEC** [comment]
the link is on CurseForge, or here: https://discordapp.com/invite/5EbFJpG

**Comment by xXspeedfistXxD** [comment]
thank you

> the link is on CurseForge, or here: https://discordapp.com/invite/5EbFJpG
