### ISSUE TITLE
Debug Log Spam

### ISSUE THREAD

**Issue by reuy** [LemADEC/WarpDrive#511]
**Describe the bug**
No abnormalities in the mod's actual performance, but the debug log gets absolutely clogged with this entry that seems to both pertain to locks and warpdrive. It repeats this error, apparently for every single block in the game, which causes the debug log to fill with literally 100,000 entries. It seems to start late into Forge's startup process, and continue late into gameplay.

**To Reproduce**
View Console output late into startup process

**Expected behavior**
No excessive log spamming

**Screenshots**
![image](https://user-images.githubusercontent.com/30891685/147357369-58c0f65d-9406-4544-8484-250e3f725dcd.png)

**Logs**
Link to pastebin/gist or equivalent logs
https://pastebin.com/Td1J8WNw

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.23 SNAPSHOT
-   Forge version: 14.23.5.2860
-   Modpack name/version: Custom Mod List
-   Other notable mods & version: Locks

**Additional context**

**Comment by LemADEC** [comment]
Screenshot of logs has no use for us.
Pastebin is truncated, can't use it.

Seeing that the Locks mod is introducing an exception in vanilla block, that's probably a bug on their side. Consider yourself lucky the game even start here.

**Comment by LemADEC** [comment]
Clearly a bug on their side, here: https://github.com/Melonslise/Locks/blob/1.12.2/src/main/java/melonslise/locks/common/util/LocksUtil.java#L86-L94

**Comment by LemADEC** [comment]
The Locks mod has this issue with other mods and it's no longer maintained, hence closing it our end.
