### ISSUE TITLE
ICBM Launcher Compatability

### ISSUE THREAD

**Issue by lellasone** [LemADEC/WarpDrive#512]
**Describe the bug**
ICBM missile launchers no longer accept new missiles from thermal expansion ducts after a jump. 

**To Reproduce**
0.  Build/generate/ect a shuttle. 
2.  Place an ICBM missile launcher containing a Tier 3 controller, a Tier 2 launcher, and a Tier 1 frame. 
2.  Place a coated item duct leading from a chest to the launcher as shown, then place a tier 1 servo by the chest and activate. 
3.  Place several missiles in the chest, one should load itself into the launcher.
4.  Connect an energy source, then launch the missile. (optional)
5. Jump the ship forward 40 blocks. 
6. If there is a missile currently in the launcher, launch that. 

**Expected behavior**
Prior to the jump new missiles will travel down the duct and load into the missile launcher. After the jump no new missiles will travel down the jump until the central piece of the launcher is broken and placed again. Missiles already in their launchers will remain there, and can be launched without major issue. 

**Screenshots**

Before the jump (note the loaded missile)
![2022-01-03_06 39 45](https://user-images.githubusercontent.com/13009896/147934814-e5154c45-16f1-4187-8050-3a6dc64490d2.png)

After the jump (note no loaded missile)
![2022-01-03_06 47 56](https://user-images.githubusercontent.com/13009896/147934741-28d084ca-3ff7-43e8-b7f8-e56e468d75cd.png)

(ICBM client terminal post jump)
![icbm error log](https://user-images.githubusercontent.com/13009896/147934573-12946201-aa75-4bfd-9451-2d1199f37303.png)

**Logs**
Link to pastebin/gist or equivalent logs

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.23
-   Forge version: 1.12.2-14.23.5.2847
-   Modpack name/version: The Chicken Stares Back / Unpublished.
-   Other notable mods & version: (ICBM-classic) 1.12.2-4.0.1b75 

**Additional context**
My best guess is that this issue has to do with the weird way that ICBM handles their blocks (they disappear if you walk far away). That said it would be really nice if launchers were compatible, particularly now that there is OC integration, since that allows for a whole new way to fight. 

I can provide a ship file (for the shipyard), and I am more than happy to conduct any additional testing needed.

**Comment by LemADEC** [comment]
We're missing the full debug logs here.  
Try to reproduce in single player with less mods and possibly using an older version, notably WarpDrive-1.12.2-1.5.19.  
ThermalDynamics version is missing.
Also, the first picture shows incorrect connection on the ducts. I remember a bug with the ICBM support for loading missiles between the launcher, the control panel and the support frame. It might work better with the launcher itself, not the control panel.  
The ship schematic would be good to have too.  
The log spam seems to refer to the AE2 block below the launcher. Are you actually using it in this setup? AE2 has known issues with connection at chunk loading, even more with ExtraCells, so you want to avoid unnecessary proximity with those blocks.

**Comment by LemADEC** [comment]
Also, try to reload the chunk/world to see if that's enough to recover.

**Comment by lellasone** [comment]
Okay, I'll give that a try and report back.

**Comment by lellasone** [comment]
That was the issue, thank you! I switched around the launchers to be fed from the bottom and they now stay working for linear and rotational jumps. 

For AE, I am mostly using it as a way to load the ship's magazine so it is not critical. Is there a lag risk using AE on warp drive ships because of the frequent chunk reloads? 

For reference on future bugs (I'm also running into an issue with being unable to break blocks that I'll play with more on the weekend) should I try with 1.12.2-1.5.19 before reporting? 


The working setup in case anyone else runs into this and is wondering: 
![image](https://user-images.githubusercontent.com/13009896/148550475-2b7832a5-6ade-4897-9dc5-3f881d89e821.png)

**Comment by LemADEC** [comment]
Thanks for the detailed answer and screenshot.

The AE2 issue with chunk loading will drop adjacent blocks as item. In extreme cases, it'll crash the server completely.  
As such, I'm not surprised it's causing log spam here.
Now, if a log spam persist like very tick, it'll lag the server and eventually crash it, so it's a good idea to address them.

I understand the original issue is fixed, so I'll close this ticket.

Regarding 1.5.22, there's client side bug with the security station that'll invalidate your crew list after a jump. Reconnecting to the server will fix it if I remember right, maybe just switching dimension is enough. It's fixed in dev, waiting for other fixes before publishing it.
