### ISSUE TITLE
Force Field Projectors - Scale Upgrade

### ISSUE THREAD

**Issue by jhammerberg** [LemADEC/WarpDrive#513]
Force fields are super useful for making your ship secure, but it's really hard to fit them to your ship perfectly. You can also use the plane shape for airlocks or doors, but even with no range upgrades its a 17x17 plane which is larger than any flat side of my ship at least.

If there was a scale upgrade added to force field projectors that allowed you to scale up or down the force field down to some degree it would open a lot of opportunities for using them in other scenarios. Of course, the upgrade should be limited to not be able to scale it more or less than a range upgrade could, so 15 blocks plus or minus. 

This problem might also be fixed by adding custom force field shapes, but that might add more problems than the first solution.

**Comment by LemADEC** [comment]
You can already scale, offset and rotate the force field projection with LUA properties `min`, `max`, `translation` and `rotation`. 
There a controller script in the plan, you can try it here for CC:Tweaked: https://github.com/LemADEC/WarpDrive/blob/MC1.12/src/main/resources/assets/warpdrive/lua.ComputerCraft/warpdriveForceFieldController/startup
