### ISSUE TITLE
Support Thaumcraft 6's Verdant Sustainer Charm as an Oxygen Supply

### ISSUE THREAD

**Issue by RandomExplosion** [LemADEC/WarpDrive#514]
**Is your feature request related to a problem? Please describe.**
My suggestion is similar to the matteroverdrive android breathing problem from a few years ago. 

**Describe the solution you'd like**
I think it would be nice to have an option in the config to allow the Sustainer Verdant Charm from thaumcraft 6 to supply oxygen to a player. Similar to how support was added for MatterOverdrive androids to not require oxygen in space.

**Describe alternatives you've considered**
There's always the problem of balance but I think it should be left up to the players to determine this in the config.

**Additional context**
[Charm Wiki Page](https://ftb.fandom.com/wiki/Verdant_Heart_Charm)

**Comment by LemADEC** [comment]
Thaumcraft 6 is broken and no longer maintained. My limited time is for bug fixes and upgrading to newer version.
However, I'm fine if someone makes a merge request for it.

**Comment by RandomExplosion** [comment]
> Thaumcraft 6 is broken and no longer maintained. My limited time is for bug fixes and upgrading to newer version. However, I'm fine if someone makes a merge request for it.

Maintenance was handed over to the cofh team wasn't it? Either way i see what you mean.

**Comment by LemADEC** [comment]
> Maintenance was handed over to the cofh team wasn't it? Either way i see what you mean.

They've the sources, that's it.

**Comment by RandomExplosion** [comment]
> > Maintenance was handed over to the cofh team wasn't it? Either way i see what you mean.
> 
> They've the sources, that's it.

Ah right, thanks
