### ISSUE TITLE
[Backpoted support] Backport Request for gallacticraft and addons for 1.7.10

### ISSUE THREAD

**Issue by Shibva** [LemADEC/WarpDrive#515]
**Is your feature request related to a problem? Please describe.**

Backporting Support for GC, Extra Planets, MorePlannets, and else. or at least have it where it would generate a default celestial for the mods present that are compact

would also be nice if the oxygen generator would be able to produce a few seconds worth of GC oxygen, just long enough for the oxygen sealers to update and kick back in

**Comment by LemADEC** [comment]
GC Oxygen was very laggy and unstable until the rewrite they did on 1.10 or something. As such, it didn't make sense to support it and there still no reason to do it.
A GC CelestialMap for 1.7.10 is already found in the issue tracker here: https://github.com/LemADEC/WarpDrive/issues/350#issuecomment-407247847 . The default map on 1.12 can also be backported to 1.7.10 fairly easily.
