### ISSUE TITLE
[1.7.10] [OpenComputers] getMaxJumpDistance() is returning 0

### ISSUE THREAD

**Issue by TechTastic** [LemADEC/WarpDrive#517]
getMaxJumpDistance() is returning true and 0 after the ship is configured

I am writing an autopilot script for a server I plan on and in the process of this, my ship kept snagging on itself

So after putting up some print() code, the problem was revealed to be getMaxJumpDistance() not returning the correct number

When booting into the normal WarpDrive program, it has all the correct numbers. Going into Movement reveals that the max is not 0.

Is there something that needs to happen before I call getMaxJumpDistance and similar API based code?

**Comment by LemADEC** [comment]
Template isn't optional, use it or get ignored
