### ISSUE TITLE
I'm confused.

### ISSUE THREAD

**Issue by masterblaster221** [LemADEC/WarpDrive#519]
When I build my ship every block is a anchor block; such as iron blocks and hull's off of Warp Drive mod. I'm guessing it's a bug.
I'm using version 1.5.26 and Open Computers to control my ship.

**Comment by LemADEC** [comment]
There's an issue template, it's not optional, use it!
Also, make sure to delete your configuration folder to restart fresh and post your full debug logs on gist or pastebin.
