### ISSUE TITLE
LUA scripts update for 1.7

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#52]
ComputerCraft added a new 'key_up' event which is not handled by existing scripts, causing lag and errors on screen.
OpenComputers has no default scripts.
Most peripheral names have changed to help with cross-mod compatibility.

List of scripts to be tested and updated for ComputerCraft:
- [x] cloaking core
- [x] mining laser
- [x] enantiomorphic reactor
- [x] radar
- [x] ship controller
- [x] updater

List of scripts to be ported to OpenComputers:
- [x] cloaking core
- [x] mining laser
- [x] enantiomorphic reactor
- [x] radar
- [x] ship controller

**Comment by YuRaNnNzZZ** [comment]
1cbcd7b partially fixes this issue for the warp core/controller part. (but it's not using key_up event)

**Comment by LemADEC** [comment]
List of scripts to be tested and updated for ComputerCraft:
- [ ] cloaking core
- [ ] mining laser
- [ ] enantiomorphic reactor
- [ ] radar
- [ ] ship controller

List of scripts to be ported to OpenComputers:
- [ ] cloaking core
- [ ] mining laser
- [ ] enantiomorphic reactor
- [ ] radar
- [ ] ship controller

**Comment by LemADEC** [comment]
Integrated Computer craft scripts are all updated.
