### ISSUE TITLE
Could not get provider type for dimension X

### ISSUE THREAD

**Issue by MaapleWaafles** [LemADEC/WarpDrive#521]
**Describe the bug**
java.lang.IllegalArgumentException: Could not get provider type for dimension 750, does not exist - When trying to enter the new world through warp space, in game console log reports:

Your_ShipName: Movement Aborted!

Unable to Load Dimension Insert_Name 
.
Check console for a missing mod or misconfiguration 

From what I understand, this means that a dimension is usually overlapping. However I have checked the Configs and can confirm the only dimension ID for 750 is the one I want to traverse to. I also want to note the original Dim ID was 290 but I changed it to 750 to try and see if the ID's changing would make a difference but alas no dice. I can usually pick up my errors based on the log reports but from what I'm reading I can't pinpoint what is going wrong and where. Galacticraft Planets work fine however.

**To Reproduce**
Install aliensvspredator-6.0.0.63
Add Dimension based off config to celestialObjects
Enter the world

**Expected behavior**
Successful entering into new dimension

**Logs**
[latest.log](https://github.com/LemADEC/WarpDrive/files/8749283/latest.log)
[celestialObjects-Galacticraft+ExtraPlanets.txt](https://github.com/LemADEC/WarpDrive/files/8749288/celestialObjects-Galacticraft%2BExtraPlanets.txt)
[config - aliensvspredator.txt](https://github.com/LemADEC/WarpDrive/files/8770224/config.-.aliensvspredator.txt)
[config - WarpDrive.txt](https://github.com/LemADEC/WarpDrive/files/8770225/config.-.WarpDrive.txt)

**Versions (latest is not a valid answer)**

WarpDrive-1.12.2-1.5.28
Forge version: 14.23.5.2854
Modpack name/version: 1.12.2

Other notable mods & version:
A lot, but the main ones of interest are:
aliensvspredator-6.0.0.63
mdxlib-3.0.0.26

**Comment by LemADEC** [comment]
there's an issue template, it's not optional, use it!

**Comment by MaapleWaafles** [comment]
> there's an issue template, it's not optional, use it!

Apologies, edited as requested

**Comment by LemADEC** [comment]
`Unable to Load Dimension` means either the dimension id is incorrect of Forge failed to load that dimension. Under normal conditions, overlapping dimensions will prevent the game to start.
Chances are you can't load that dimension through other ways like the `/space 750` command.
It's most likely an invalid registration of the dimension in the AvP mod.

**Comment by TwilightHound** [comment]
maaplewaadles you said "Enter the world", how do you do that?
