### ISSUE TITLE
Warpgate implementation

### ISSUE THREAD

**Issue by TwilightHound** [LemADEC/WarpDrive#522]
**Describe the bug**
i can go to hyperspace with [H], but when i hit [3] it says "not implemented".

**To Reproduce**
1. build a ship with superior black stained hull, at least 4000 blocks of it
2. use a corvette ship core.
3.  put an advanced computer directly on top of the core
4. put any power source (i used a creative power cube from mekenism mod) directly to the side or on the bottom.
5. right click the computer
6. name the ship anything
7. press "3"
8. look at line four of text.
9. says "not implemented"

**Expected behavior**
a list of warp gates or a tutorial telling me how to make one.
**Screenshots**
![image](https://user-images.githubusercontent.com/48195169/171743819-b3434a35-b508-4e89-be7b-e3a4c4ad8bf4.png)

**Logs**
https://mclo.gs/SspWQnu

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.28.jar
-   appliedenergistics2-rv6-stable-7.jar
-   cc-tweaked-1.12.2-1.82.1.jar
-   Mekanism-1.12.2-9.8.3.390.jar
-   mystcraft-1.12.2-0.13.7.06.jar
-   Patchouli-1.0-23.6.jar
-   Forge version: 1.12.2 - 14.23.5.2860

**Comment by LemADEC** [comment]
Warpgates never really work due to early design flow, so it was removed pending a redesign. The screen and messages referring to it are just placeholders.

**Comment by TwilightHound** [comment]
> Warpgates never really work due to early design flow, so it was removed pending a redesign. The screen and messages referring to it are just placeholders.

how to get to other dimensions via ships then?

**Comment by LemADEC** [comment]
Warpgates are only to travel between hyperspaces, which you can't do right now.

**Comment by TwilightHound** [comment]
> Warpgates are only to travel between hyperspaces, which you can't do right now.

when will it be avalible? (eta)
