### ISSUE TITLE
cloaking device works fine in singleplayer, but doesn't hide ship in multiplayer.

### ISSUE THREAD

**Issue by TwilightHound** [LemADEC/WarpDrive#524]
**Describe the bug**
i built a ship in a singleplayer world, but when i put that world on my server, the cloaking device says it worked but the ship is still visible

**To Reproduce**
1. build an object you want to hide.
2. place a cloaking core dead center of the object
3. put any power source (i used a creative power cube from mekenism mod) next to the cloaking core.
4. with a 2 block gap between core and coil put a cloaking coil on all six sides of the core.
5. on the outside of the object, in a direct line between inner coil and outer coil, place a cloaking coil at the outer limit of your build.
6. place an advanced computer on top of the cloaking core, then open it and type enable.
8. move 7 blocks away from the outer cloaking coils.
**Expected behavior**
the ship should vanish, but it doesn't on a server, only on a singleplayer world.

**Screenshots**
![image](https://user-images.githubusercontent.com/48195169/173250069-fda13d3f-aedd-4f8a-9259-5f9bb1b7a240.png)

**Logs**
https://mclo.gs/4wH2QMP

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.28.jar
-   Forge version: 1.12.2 - 14.23.5.2860
-   patchouli-1.0-23.6.jar
-   Mekanism-1.12.2-9.8.3.390.jar
-   cc-tweaked-1.12.2-1.82.1.jar
-   appliedenergistics2-rv6-stable-7.jar

**Comment by LemADEC** [comment]
It works fine on the official servers, so you've most likely forgot something.
Check if the beams are showing, the core actual energy level and the state of the core and coils.

**Comment by TwilightHound** [comment]
> It works fine on the official servers, so you've most likely forgot something. Check if the beams are showing, the core actual energy level and the state of the core and coils.
the beams are on, i coppied the world from singleplayer to a server. i even rebuilt the cloaking structure. when i rightclick the core, it does not throw any codes, it just says cloak is online when i check the computer.

**Comment by LemADEC** [comment]
How did you transfer the world?

What does the core exactly says when you right click it?

**Comment by LemADEC** [comment]
No update for 4+ weeks, assuming fixed
