### ISSUE TITLE
Wiki Format Request: Include slight edits for old versions

### ISSUE THREAD

**Issue by Shibva** [LemADEC/WarpDrive#526]
This is probs a bit different from seeing a report being made for the wiki

anyhow, I am currently using warp drive in an old version, and when It was erroring. Being a noob at Lua in general, I thought I was doing something wrong. 

but it  turns out that after toying around and learning about getting methods in the Lua interpreter, I found that some of the names of the handlers are not correct

I can only assume that statements like .laser1.freq(100) are correct in more updated versions, but I was wondering if you can make a wiki edit to inform the user reading it that it might need a slight adjustment for older versions

that is all

**Comment by LemADEC** [comment]
There's LUA API change logs page specifically for that, here: https://github.com/LemADEC/WarpDrive/wiki/LUA-change-logs
