### ISSUE TITLE
[1.7.10] line 22 of main laser is calling nil

### ISSUE THREAD

**Issue by Shibva** [LemADEC/WarpDrive#527]
To clarify, im understanding that the wiki entry stuff may have been susceptible to change and the code posted on such may not be relevant to the 1.7.10 version. Regardless, it appears the CC code examples are mostly stable except for 2 things, one that I was able to correct.

on line 22 of the "main" laser code, an error message generates when attempting to call a nil value
"attempt to call nil"

while mine has been altered ever slightly, the erroring line is referring to 
``myX, myY, ,myZ = laser.pos()``

id appreciate it if I could get help wtih this, though will understand if such support wont be given as well

**Comment by Shibva** [comment]
Never mind

it turns out it was a simple thing I dint see, just like the other issue, this version doesn't understand the shorthand expression
simply changing ``laser.pos()`` to ``laser.position()`` corrected the error, just like how I had to change ``freq`` into ``beamFrequency`` to get it to work

The issue is resolved, but I do insist on keeping it open till one of yall see it, it sort of goes in tandem with #526

**Comment by LemADEC** [comment]
Read the API change logs when porting scripts between version, here: https://github.com/LemADEC/WarpDrive/wiki/LUA-change-logs
