### ISSUE TITLE
Worldborder Has Shrunk

### ISSUE THREAD

**Issue by Goodbuster98** [LemADEC/WarpDrive#528]
The worldborder has shrunk from 30 million blocks to around 10500. I have tried using the /worldborder set command but it doesn't change the world border, and up until installing warpdrive the world border was at 30 million. (On my server)

-   WarpDrive version: 1.12.2-1.5.28
-   Forge version: 1.12.2 (14.23.5.2860)

All Mods I'm using:
[1.12.2]+SecurityCraft+v1.9.1
aunis-1.12.2-4.10.1.0-client
cc-tweaked-1.12.2-1.89.2
ExtraPlanets-1.12.2-0.7.4
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
iChunUtil-1.12.2-7.2.2
jei_1.12.2-4.16.1.302
mcef-1.12.2-1.11b
mcef-1.12.2-1.11b-coremod
MicdoodleCore-1.12.2-4.0.2.280
MJRLegendsLib-1.12.2-1.2.1
OpenComputers-MC1.12.2-1.7.5.192
OptiFine_1.12.2_HD_U_E3
PortalGun-1.12.2-7.1.0
r2s-Core-1.12.2-1.7.0.RELEASE
r2s-Radio-1.12.2-1.4.2.RELEASE
SGCraft-2.0.5
Voice+Chat+Reloaded-1.2.5
webdisplays-1.12.2-1.1

**Comment by LemADEC** [comment]
Issue template isn't optional, use it!
Also, the world border is defined through you celestial map, check the in-game manual and largely commented default configuration.
