### ISSUE TITLE
virtual assistant commands not listed

### ISSUE THREAD

**Issue by TwilightHound** [LemADEC/WarpDrive#530]
**Describe the bug**
the virtual assistant commands are not listed
**To Reproduce**
place a virtual asistant right next to your ship core and suply it with power, mount a diamond tuned crystal on it.

**Expected behavior**
a list of commands should be avalable somewhere, maybe the manual?

**Versions** (latest is not a valid answer)
-   WarpDrive version: WarpDrive-1.5.28 Release for 1.12.2(https://www.curseforge.com/minecraft/mc-mods/warpdrive/files/3762066)
-   Forge version: 1.12.2 - 14.23.5.2860
-   Modpack name/version: n/a
-   Other notable mods & version: patchouli

**Additional context**

**Comment by LemADEC** [comment]
That's up to you to write the VirtualAssistant code and choose which commands to use.
