### ISSUE TITLE
Unable to Load a World

### ISSUE THREAD

**Issue by Hamsterpouch** [LemADEC/WarpDrive#532]
**Describe the bug**
Whenever i try to load my survival world, it gets stuck on 0%, which usually goes away so fast you can't really see it. It is NOT a crash, but the output log just says the same thing over and over again.

**To Reproduce**
1.  Go to space (all this using my modpack with my config options)
2.  Leave the world
3.  Close the gain (not necessary but both times this happened to me it was after i closed the game.)
4.  Attempt to re-open the world. 

**Expected behavior**
That world will not be loaded. You'll know this when it is stuck on the 0% in the dirt screen upon loading a world.

**Screenshots**

**Logs**
https://pastebin.com/aSQ0A3w9

**Versions** (latest is not a valid answer)
-   WarpDrive version: WarpDrive-1.12.2-1.5.27
-   Forge version: 1.12.2-forge-14.23.5.2859
-   Modpack name/version: My own modpack, doesn't have a version.
-   Other notable mods & version: hbm-1.6.9a-G

**Additional context**

**Comment by LemADEC** [comment]
We need the full logs, not a truncation, not a copy from console. We need the integral file. Consider using gist instead of pastebin,
We need a full list of mods with their version.

**Comment by Hamsterpouch** [comment]
Okay. Also know that the log is 78762 lines long. Ill get the mod list later, I'm busy with school today.
https://gist.github.com/Hamsterpouch/980bf4f5be9eb538070ddc02a2d2435a

**Comment by Hamsterpouch** [comment]
Important note: The thermal mods (foundation, core, and world) were not there at the time of this, so just ignore them.
![image](https://user-images.githubusercontent.com/84638785/192071039-c6bb0697-1e5a-4cad-a9e0-e768ab046718.png)
![image](https://user-images.githubusercontent.com/84638785/192071081-56d8b041-5ecb-43bc-a779-46a1a5fca919.png)
![image](https://user-images.githubusercontent.com/84638785/192071241-42eaf378-c69e-4a90-afb1-e1b90aa9f696.png)
![image](https://user-images.githubusercontent.com/84638785/192071308-601b3c43-2562-4856-a833-26cdd9cd32ec.png)

**Comment by LemADEC** [comment]
That's a bug in FuturePack trying to access data while the dimension isn't fully loaded:
```
[16:29:50] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: terraformer3 joined the game
[16:29:50] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Load@413484d0:
java.lang.RuntimeException: Critical error: there's no celestial object defining client dimension DIM-101, unable to proceed further
	at cr0s.warpdrive.world.AbstractWorldProvider.getSaveFolder(AbstractWorldProvider.java:46) ~[AbstractWorldProvider.class:?]
	at futurepack.common.dim.scanning.FPChunkScanner.onWorldLoad(FPChunkScanner.java:370) ~[FPChunkScanner.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1152_FPChunkScanner_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
```

**Comment by LemADEC** [comment]
There's also compability issues, for example:
```
[16:27:44] [main/WARN] [gg.essential.loader.stage2.EssentialLoader]: Found an old version of Mixin (0.8.2). This may cause issues.
```

**Comment by Hamsterpouch** [comment]
ok thank you. Essential isnt a problem, so ill contact future packs dev.

**Comment by Hunter24681** [comment]
@LemADEC 
I'm getting the same issue (similar log error, stuck at 0%) on a totally different modpack (RaCraft12).  The issue didn't occur until I generated the space dimension.  It might also require the player to be in space when quitting the game, but I'm not sure.  It may not be directly an error in warp drive, but it seems like something in the way it loads is likely to cause errors elsewhere

![image](https://user-images.githubusercontent.com/76822995/221894518-52578ea1-0de0-433a-a3c1-8ee13f4c7019.png)

The initial error is identical
![image](https://user-images.githubusercontent.com/76822995/221895353-7701b54f-1280-4282-ad10-56c09807b5a2.png)

And it looks to me like it fails when forge fires the AttachCapabilitiesEvent. This occurs immediately before the exception stacktrace
![image](https://user-images.githubusercontent.com/76822995/221896469-d486b93d-74a8-4bfc-8206-4b9cbbc347da.png)


Given that other mods don't cause this I think warpdrive is loading something differently?
Also confirmed by loading a pre space genration backup that the game loads fine before that.

Full log: https://paste.atlauncher.com/view/7615bd2e-7a0e-4f7e-809e-15d5b9f9880a
I can attach the full modlist if requested.

**Comment by LemADEC** [comment]
That's an known issue in TheBetweenLands and their implementation of capabilities, nothing new here, sadly.

**Comment by Hunter24681** [comment]
Wierd that it only manifests (so far) in the warpdrive dimension.  To be fair I haven't started betweenlands on this pack yet so maybe that would do it too. Thanks for the info!

Sorry to bother you about this again, but would you have a link to the betweenlands issue?  I wasn't able to find it

**Comment by Hunter24681** [comment]
And thanks!  Disabling the betweenlands saved my non-loading world!

**Comment by Hamsterpouch** [comment]
my issue is with future pack, as you probably saw. Solved/ prevented it by removing all future pack blocks in all warp drive dimentions.
