### ISSUE TITLE
error between Hbm's nuclear tech and Warp Drive

### ISSUE THREAD

**Issue by Varian12yt** [LemADEC/WarpDrive#534]
Describe the bug
Warp drive alters the functionalities of the "reactor access hatch" block of Hbm's Nuclear Tech mod Reloaded mod

to reproduce
1. Build a "big nuclear reactor"
2. cover with concrete to prevent radiation escape, put the reactor access hatch
3. put it to work (if you don't know the mod put water, coolant and uranium fuel to start it)

Expected behavior
being covered in concrete, the radiation shouldn't spread, but having the warp drive mod installed, for some unknown reason, the access hatch reactor loses its radiation isolation properties, and the radiation leaves the reactor and contaminates (this can be seen with a geiger), at first I thought maybe this was due to "cctweaked" and replaced it with "oc", but the problem continued so I uninstalled warp drive and the problem was fixed for some reason warp drive removes the properties of this block and I don't know if this will also happen with other blocks.

Logs

Versions

WarpDrive version: 1.5.28
Forge version: 14.23.5.2860
Modpack name/version: (none)
Other notable mods & version: "cctweaked"

**Comment by LemADEC** [comment]
The issue tracker has a template, it's not optional, use it: either make a new issue using it or update your original comment.

**Comment by Varian12yt** [comment]
sorry about before, i'm new to github
