### ISSUE TITLE
error between Hbm's nuclear tech and Warp Drive

### ISSUE THREAD

**Issue by Varian12yt** [LemADEC/WarpDrive#535]
**Describe the bug**
Warp drive alters the functionalities of the "reactor access hatch" block of Hbm's Nuclear Tech mod Reloaded mod
**To Reproduce**
1. Build a "big nuclear reactor"
2. cover with concrete to prevent radiation escape, put the reactor access hatch
3. put it to work (if you don't know the mod put water, coolant and uranium fuel to start it)

**Expected behavior**
being covered in concrete, the radiation shouldn't spread, but having the warp drive mod installed, for some unknown reason, the access hatch reactor loses its radiation isolation properties, and the radiation leaves the reactor and contaminates (this can be seen with a geiger), at first I thought maybe this was due to "cctweaked" and replaced it with "oc", but the problem continued so I uninstalled warp drive and the problem was fixed for some reason warp drive removes the properties of this block and I don't know if this will also happen with other blocks.

**Screenshots**
None

**Logs**
None

**Versions** (latest is not a valid answer)
- WarpDrive version: 1.5.28
- Forge version: 14.23.5.2860
- Modpack name/version: (none)
- Other notable mods & version: "cctweaked"

**Comment by Varian12yt** [comment]
like you said i reposted it, i don't know how to delete the previous bug report

**Comment by LemADEC** [comment]
we need logs and the version of other mods involved.

**Comment by Varian12yt** [comment]
ok, the mods involved would be Nuclear Tech Mod Reloaded (versión hbm-1.6.9a-G.jar) and Warpdrive (versión 1.5.28) (I already verified that cc tweaked is not the problem)

**Comment by Varian12yt** [comment]
Well, since you didn't answer what I said earlier, I wanted to comment that I'm new to reporting bugs and have no idea how to do a "log".

**Comment by LemADEC** [comment]
Your modpack includes multiple folders likes `mods` or `saves`. Of those folder is called logs. In that folder, you'll find notably 2 files named `latest.log` and `debug.log`. We need those 2 files.

**Comment by Varian12yt** [comment]
that is?
[latest.log](https://github.com/LemADEC/WarpDrive/files/9843023/latest.log)

**Comment by Varian12yt** [comment]
I can't find the debug.log file

**Comment by LemADEC** [comment]
Can't reproduce, not enough information provided
