### ISSUE TITLE
asteroid fields

### ISSUE THREAD

**Issue by Nikodim54** [LemADEC/WarpDrive#536]
Hello! I have a question. how can we reduce the number of asteroids created in outer space and at the same time remove supermassive asteroids? Otherwise, in many cases, this creates a rather large fps drawdown on weak devices. 

I hope that I wrote where it is necessary.
-   WarpDrive version:  1.12.2-1.5.19
-   Forge version: forge-1.12.2-14.23.5.2854
-   Modpack name/version: personal 1.12.2
-   Other notable mods & version: no

**Additional context**

**Comment by LemADEC** [comment]
Your version is way outdated, so first, make sure to update.
Second, the base game has notable memory leak and lag issues, consider adding the Foamfix mod to your pack.

**Comment by Nikodim54** [comment]
> Ваша версия сильно устарела, поэтому сначала обязательно обновите ее. Во-вторых, базовая игра имеет заметные проблемы с утечкой памяти и задержками, поэтому подумайте о добавлении мода Foamfix в свой пакет.

I replaced the yes version. but FoamFix is already standing. I would like to reduce the number of asteroids, as they introduce an imbalance in the assembly slightly. That's why I would like to reduce their number.

**Comment by LemADEC** [comment]
You can already adjust the content and size of asteroids in the fillserSets and structuers configuration files.
You can already adjust the probability of each structure in the celestialObjects configuration files.
