### ISSUE TITLE
1.12.2 Force field blocks crashes the client when minimap opened

### ISSUE THREAD

**Issue by TUNSOU** [LemADEC/WarpDrive#537]
**Describe the bug**
When Xaero's Minimap/Better PvP  is installed, once the minimap attempts to render the force field block the client crashes
Xaero's Worldmap is not OK, either.

The Journey Map is no problem, it doesn't render these blocks

**To Reproduce**
1.  Install  Xaero's Minimap/Better PvP/Xaero's Worldmap
2.  Open a save, place and enable a Forcefield Projector
3.   Client crashes the instant Force field blocks generated
**Expected behavior**
Making the force field block a common imperishable block as bedrock may help
**Screenshots**

**Logs**
Link to pastebin/gist or equivalent logs

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.5.28
-   Forge version: 2859
-   Modpack name/version: 1.12.2
-   Other notable mods & version: No
[crash-2023-01-25_17.53.38-client.txt](https://github.com/LemADEC/WarpDrive/files/10498215/crash-2023-01-25_17.53.38-client.txt)

**Comment by LemADEC** [comment]
This is a Xaero's World Map issue: the mod is requesting block information before the tile entity data was sent to client.

**Comment by TUNSOU** [comment]
So can it be solved? I dont want to use other minimap mods because I marked lots of waypoints using Xaero's.
If no way, it doesn't matter.Thank you

**Comment by LemADEC** [comment]
Like I said, issue is in the other mod, open an issue and ask them to fix their problem.

**Comment by yitianzhuangzhu** [comment]
You referenced this issue in the 2023 update, but no new version was released after 2022. I want to know if you will release further updates, or create a small patch for version 1.5.28 to reference this issue ：）
