### ISSUE TITLE
Can’t my warp drive to work

### ISSUE THREAD

**Issue by Slateturtle** [LemADEC/WarpDrive#539]
The warp drive code won’t work even though I put it in correctly. I’m playing on dreamcraft 2 and each time I set up a ship and put it together the code doesn’t startup. 
it doesn’t give me an error, it just won’t start. 
It might have something to do with the dreamcraft server.

**Comment by Destiny3378** [comment]
might wanna talk with the admins of said server, every recent version of WD I have used works just about flawlessly

**Comment by LemADEC** [comment]
There's an issue template, it's not optional.
Dream Craft 2 is based on MC 1.6.4 with an old buggy version of WarpDrive, many things won't work as it.
