### ISSUE TITLE
Incorrect texture file names in MC1.7 branch

### ISSUE THREAD

**Issue by iocmet** [LemADEC/WarpDrive#541]
https://github.com/LemADEC/WarpDrive/tree/MC1.7/src/main/resources/assets/warpdrive/textures/items/component
Lens, Motor, Superconductor, Zoom must be lowercase, causes missing texture for this items

**Comment by LemADEC** [comment]
There's an issue template it's not optional.
MC1.7 doesn't require resource names to be all lower case. That requirement came much later.

**Comment by iocmet** [comment]
But in 1.7.10 it does

**Comment by LemADEC** [comment]
The last update of the mod for 1.7.10 was 5 years ago, all textures are working just fine for everyone even before that, and you think there's a bug in the mod, really?

**Comment by iocmet** [comment]
Uh, in mod from curseforge texture file names is lowercase

**Comment by iocmet** [comment]
I downloaded mod source from https://github.com/LemADEC/WarpDrive/tree/MC1.7 compiled and i have this issue on 1.7.10

**Comment by LemADEC** [comment]
There's an issue template it's not optional.
