### ISSUE TITLE
Incompatibility with JSG Stargates when moved.

### ISSUE THREAD

**Issue by jhammerberg** [LemADEC/WarpDrive#543]
**Describe the bug**
Using the WarpDrive mod, the game/server will crash if a player goes through a Stargate that has been on a ship and moved while active.

**To Reproduce**
1. Get JSG and WarpDrive together
2. Make a ship with a Stargate on board and dial the Stargate to any address
3. Move the ship any distance with the Stargate still active
4. Go through the active Stargate after the ship has moved and the game/server will crash.

**Expected behavior**
I would hope the game would not crash, but short of that, some sort of check in place that prevents stargates from maintaining an active connection after being moved. Or a check on WarpDrive's side for an active Stargate that prevents the ship from moving (like is already implemented with SGCraft). I have already made an issue on the JSG GitHub for this bug since it is a 3rd party incompatibility.

**Video**
https://user-images.githubusercontent.com/22381811/231029052-1590b70c-69c9-4fff-8c84-1b6ce2c744fd.mp4

**Logs**
[crash-2023-04-10_20.58.10-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11195101/crash-2023-04-10_20.58.10-server.txt)

**Versions** (latest is not a valid answer)
-   WarpDrive version: 1.12.2-1.5.28.SNAPSHOT
-   Forge version: 14.23.5.2860
-   Modpack name/version: Interstellar Odyssey (Private Pack) 0.3
-   Other notable mods & version: JSG 1.12.2-4.11.0.5

**Additional context**
[JSG Bug Report](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/issues/243)

**Comment by LemADEC** [comment]
Dup of #523
