### ISSUE TITLE
[Question] Why active AE2 quantum chamber is hardcoded anchor?

### ISSUE THREAD

**Issue by iocmet** [LemADEC/WarpDrive#552]
https://github.com/LemADEC/WarpDrive/blob/90abf4fcde95537419275a2beb30fc8ec3fbb27b/src/main/java/cr0s/warpdrive/compat/CompatAppliedEnergistics2.java#L56
https://github.com/LemADEC/WarpDrive/blob/b691306a71abca73f66f8591235d600a436ea8e6/src/main/java/cr0s/warpdrive/compat/CompatAppliedEnergistics2.java#L60
Is there some specific reason for it? like some bug? or is it just gameplay mechanic?

**Comment by LemADEC** [comment]
All of the above: it's too complicated to implement and gameplay makes more sense with it disabled during jump.
