### ISSUE TITLE
Ship controller script not booting in 1.3.3

### ISSUE THREAD

**Issue by MechWarrior99** [LemADEC/WarpDrive#61]
I can not get any of the machines to accept power form any thermal dynamics ducts. Or Thermal expansions energy cells

**Comment by LemADEC** [comment]
Which version of both mods are you using?

**Comment by LemADEC** [comment]
This is a regression in the LUA script provided with the controller. You can fix it manually or wait for the next update. Sorry for that.

**Comment by LemADEC** [comment]
- Place a computer
- Create a "startup" script
  type "edit startup"
  leave it blank
  save it
- Move that computer next to a controller
- Reboot the computer (Ctrl-R)
- Type "rm startup"
- Type "cp warpdriveShipController/startup startup"
- Modify the script at line 473, replace "until not isAttached" with "until isAttached"
- Reboot the computer (Ctrl-R)
