### ISSUE TITLE
Broken world generation as we move configuration through XML

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#62]
Will update when finished. Until then, go to space at your own risk

**Comment by LemADEC** [comment]
See #68 for current state: stars, moons and gas clouds are no longer working.

**Comment by YuRaNnNzZZ** [comment]
old title is more appropriate for the current situation :)

**Comment by YuRaNnNzZZ** [comment]
Game crashing when worldgen tries to generate structure, but does [not find anything](https://gist.github.com/YuRaNnNzZZ/a3f82ebd8dfbdc2507c1). I tried copying structures-default.xml into config/warpdrive folder and i get [this error](https://gist.github.com/YuRaNnNzZZ/ae78c7737e64a2a74a72) in fml log (also that error on 2nd and 3rd line same for all loaded .xmls, but [this file](https://gist.github.com/YuRaNnNzZZ/481aac87abd253c22e96) works perfectly).

**Comment by TheNumenorean** [comment]
Put simply, it isn't done yet. When it is actually working we'll push 1.3.4

**Comment by YuRaNnNzZZ** [comment]
So, as 1.3.4 is out, i tested it out. Worldgen is still broken. I got same crash, but now it does not open default structures file with [this error](https://gist.github.com/YuRaNnNzZZ/73be03ad8cc80a58816f).

**Comment by TheNumenorean** [comment]
So, i was not expecting LemADEC to upload v 1.3.4 this soon, he didn't tell me he was doing it. World generation isn't finished yet. @LemADEC can we agree to wait for 1.3.5 until world gen is finished?

**Comment by YuRaNnNzZZ** [comment]
This is strange. I cleaned up `config/warpdrive` folder from XML files and everything works well.

**Comment by YuRaNnNzZZ** [comment]
Started new world and... same crash. It only crashes when trying to generate structures.

**Comment by LemADEC** [comment]
We have some outstanding bugs in the 1.3.3, it was not really an option to keep it.
It'll take time to stabilize worldgen, we need somehow to keep it stable while we work on it.

**Comment by LemADEC** [comment]
Try with empty XML files for now.
We need to add a XML schema.

**Comment by LemADEC** [comment]
That being said, we should have talk about it before hand :)

**Comment by YuRaNnNzZZ** [comment]
Tried with empty XML file. Crash. Can you add fallback config option for now?

**Comment by TheNumenorean** [comment]
That is fair enough. I can probably get it stable tonight. I will go through and just make sure it wont crash, then it should be stable enough. We could have the first part done in two days if we could agree on a method. :P Also, remember this is a super-early-access-alpha, i dont see where the expectation of stability comes from?

Also, in the future, lets use branches more, it really does help :)

EDIT: Officially, as far as im concerned, until we say otherwise worldgen crashes are a feature ;)

**Comment by TheNumenorean** [comment]
Proposal: I will work on the code to get it stable tonight, such that attempts at world generation do not cause severe crashes, though it also doesn't necessarily generate anything. Once this is achieved, i will push V1.3.5, so that the current version doesn't cause crashes. Then, ill create a development branch that we can continue working on world gen in, so that fixes can still be made to the main line in tandem, and the development doesn't break anything.

Opinions?

**Comment by LemADEC** [comment]
@YuRaNnNzZZ I've no XML in my config folder and it boots just fine for me.

We had to merge the branch to exchange on it, I've no regret on that. We should have made it an option it, that's all.
I need to fix the registries and cloaking before pushing 1.3.5.
Then I'll make the threaded framework for generating structures and force fields.

**Comment by TheNumenorean** [comment]
But, multiple people can work on a branch at the same time. I dont mean a fork, just a branch.

Regardless, the crashing appears to have stopped. What do you want to be in 1.3.5?

Also, what do you mean by threaded framework?

**Comment by LemADEC** [comment]
Threaded framework is a computation thread to run computation outside the main thread. Typically computing a list of blocks coordinates in space where to place/remove blocks. This is useful to compute complex/dynamic shapes like explosion, force fields or world generation. Then you can use a (tile)entity to apply those blocks progressively to the world, hence killing lag.

**Comment by LemADEC** [comment]
Need a proper plan for this, will create a new issue accordingly
