### ISSUE TITLE
Add a telemetry block

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#63]
New block used to localize your ship in space.
Having it on board, unlock the 'position()' method in scripts to localize a block relatively to ship core or globally in the world.
This would be required for the Radar map.

**Comment by ghost** [comment]
Why not GetPos() for current pos and GetOrigin() for pos where it first warped from?
(Make GetOrigin() and GetPos output be able to be stored into a table to make the ship use warpTo( tablename() )

**Comment by LemADEC** [comment]
"first warped from" is fairly ambiguous here.
I guess you're proposing a Ship log to trace where it went and such?

**Comment by ghost** [comment]
Yeah like that. That the data is stored in some virtual place in the machine

**Comment by LemADEC** [comment]
Ship log can already be done in LUA.
Telemetry has been replaced with the Sensor setup. No longer applicable, closing
