### ISSUE TITLE
Radar detection of nearby planets

### ISSUE THREAD

**Issue by sanovskiy** [LemADEC/WarpDrive#66]
The idea is that radar will detect planets nearby at cost of much bigger energy usage. Also the radar will have modes: detect players, detect ship cores or detect planets.

**Comment by LemADEC** [comment]
Yes, we need to update radar at some point. Let me create a new issue for that.

As for detecting planets, the main concern is that it would generate new chunks, which will kill the server almost instantly. I see multiple options to address that:
- don't generate new chunks, player will see the 'empty spots' anyway
- generate new chunks in a short range but very slowly

In the second case, it's more a space generator than a radar and server owners would disable it by default.
Any thoughts?

**Comment by LemADEC** [comment]
See #67

**Comment by FirstArchon** [comment]
the way transition planes work now is that going down at particular coordinates will take you to a particular dimension right? couldn't the radar just tell you the transition plane is where it ought to be based on coordinates without loading the chunks? ie the plane is (theoretically) 500 blacks that-a-way?

**Comment by LemADEC** [comment]
There's a confusion between planets and moons in this discussion:
- Transition planes are predefined, can be added to radar API easily.
- Moons in world generation should be seen on radar at some point, but only exist once the chunk is generated

**Comment by LemADEC** [comment]
Already covered in #67
