### ISSUE TITLE
Game crash when trying to generate gas cloud.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [LemADEC/WarpDrive#68]
When i enter the space and try to generate some chunks, it works fine until it tries to generate gas cloud.
Crash-report: https://gist.github.com/YuRaNnNzZZ/9f13e1f30796bb5e8df8
FML worldgen log part: https://gist.github.com/YuRaNnNzZZ/6ffe324f5161f8a7d7a9

**Comment by LemADEC** [comment]
Yes, the new world generation structures aren't working yet, moon, star and gaz clouds won't work until implementation is finished.
I've patched the gaz clouds part to fix the above one.  see bf2e325db38123980d7beb1b046862e61c1b8bed
