### ISSUE TITLE
Can't create ship

### ISSUE THREAD

**Issue by MechWarrior99** [LemADEC/WarpDrive#71]
I tweeted this but i thought i would say it here as well.  Every time i try and make a ship in the new 1.7 version the computer gets stuck and will not go any further than "ship core detected...". Any ideas?

**Comment by LemADEC** [comment]
Dup of #61

**Comment by LemADEC** [comment]
Please refer to your previous ticket, this is already fixed in dev version. There's a workaround explained in #61
