### ISSUE TITLE
Ship rotation and kinetic weapons

### ISSUE THREAD

**Issue by Sasszem** [LemADEC/WarpDrive#73]
Please add a forcefield-system, or integritation w/ one existing.

Forcefield-projector modules:
*Prevent warp: only whitelisted warpcores can warp under the field. If anybody else tries, drop them back(but cosume the jump energy)
*Laser-shield: Simply, lasers can't go under the shield. The generator loses energy on hit, depends on the laser's energy
*W-shield: MAke the radar to see the forcefield, except if a W-shield module is inserted.

Please add Photon-torpedoes!
Add a forcefield module to keep them off.
& add that the projector loses power when hit...

Please add some type of tractor-beam!

Please add a warp option: rotate, that rotates the entire ship by the multiples of 90°

**Comment by LemADEC** [comment]
Kinetic weapons, forcefield and Warp inhibition are already covered in other tickets.
Rotation will come with the FlyBy upgrade.

**Comment by Sasszem** [comment]
If it's a ST-based mod, please add:
(wait for it)
Tribbles! :laughing:

**Comment by LemADEC** [comment]
Rotation is done in dev, others are already tracked in dedicated tickets, hence closing
