### ISSUE TITLE
No structures and overworld biomes in space

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [LemADEC/WarpDrive#75]
I tested space worldgen again, as it should be fixed. It's not crashing anymore. But now it does not generate any structure because of `Skippping structure data file C:\Games\1.7.10\config\WarpDrive\structures-default.xml because the mods ,  are not loaded` error.
Also i get overworld biomes randomly generated in space, i think it's not normal.
Screenshots of biomes in space: [1](http://i.imgur.com/iCPuVLH.png), [2](http://i.imgur.com/YMqCDsT.png), [3](http://i.imgur.com/JYI9cUB.png), [4](http://i.imgur.com/itwsSia.png). (i used [this script](https://gist.github.com/YuRaNnNzZZ/ac00a4e76258dcce8d88) to display messages.)

**Comment by TheNumenorean** [comment]
Do spawning commands work? Did you try refreshing the files in config/WarpDrive?

**Comment by LemADEC** [comment]
The biomes were always vanilla, it's not a regression. You can check biomes with the F3 menu while moving around.

**Comment by TheNumenorean** [comment]
I fixed a bunch of issues, but it still doesnt seem to be working properly. If you want to test it, I tagged a Dev version which you can grab from releases.

**Comment by TheNumenorean** [comment]
Space generation is fixed in 1.3.5.1, which is at commit 00c1de21233683c3eb69bcd63e011ff30984200b
A download is available under releases. Asteroids still do not spawn, that will come soon.

**Comment by TheNumenorean** [comment]
![2015-08-25_23 45 12](https://cloud.githubusercontent.com/assets/809047/9487186/3a26bdbc-4b84-11e5-864d-2440291f680c.png)

**Comment by YuRaNnNzZZ** [comment]
[And again](https://gist.github.com/YuRaNnNzZZ/2e6f460440ac797a90fb). Can you add option to use old worldgen until new is completely fixed?

**Comment by YuRaNnNzZZ** [comment]
How soon asteroids will be fixed? It does not generating now, even cubic ones.

**Comment by TheNumenorean** [comment]
I am assuming you have tried deleting all the conf files and letting them regenerate?

**Comment by TheNumenorean** [comment]
They are spawning for me

**Comment by YuRaNnNzZZ** [comment]
Can you reopen it? I still have no asteroids. I'm using 1.3.9-dev (a5606731c2554ea498eaeaba9771d21616d7477e), removed all configs and STILL NO ASTEROIDS.
Just do a simple option in config that allow falling back to legacy worldgen. PLEASE.

**Comment by YuRaNnNzZZ** [comment]
oh, i just got 2 very small cubic asteroid with iron ore and stone/cobble only. Most of the time it generates 1-8 iron ore blocks between long distances .

**Comment by LemADEC** [comment]
Try to reload the world to confirm if those are actually asteroids and not moons.

**Comment by YuRaNnNzZZ** [comment]
Reloaded. These are actually asteroids.
![](http://i.imgur.com/Q2dVAJF.png)
![](http://i.imgur.com/erB8tAx.png)

**Comment by TheNumenorean** [comment]
How far have you explored?
