### ISSUE TITLE
Ore spawns in space need reviewing

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#79]
Moons are literally a gold mine. I did not choose very good default weights and ratios in the filler and structure files. If someone with a better feeling for that wanted to adjust those, they would be much appretiated.

**Comment by LemADEC** [comment]
Reuse the ratios from 1.6.4 ?

**Comment by TheNumenorean** [comment]
We can to a point, but they are nowhere as in depth as the new system allows.

**Comment by LemADEC** [comment]
We need to start somewhere

**Comment by TheNumenorean** [comment]
What i mean is that i already have, and also that the original values aren't entirely analogous to the new system.

**Comment by TheNumenorean** [comment]
Ideally, someone who had more of an opinion would take a look and adjust it.

**Comment by LemADEC** [comment]
Fixed in baede105460c5076734a25dda5e03a06c58fb58e
