### ISSUE TITLE
Transition Planes not working

### ISSUE THREAD

**Issue by Scakah** [LemADEC/WarpDrive#81]
As of the Newest version, i wanted to try transition planes,
and i copied everything from you're transition planes site,
installed GC an tried to warp from the moon.
No matter what i tried it would show the text message:
There's no valit transition plane for current dimension
moon.moon (-28)

**Comment by LemADEC** [comment]
1.3.5 doesn't load up planets definitions properly, see #77 
New version with the fix should be up tomorrow, hopefully
