### ISSUE TITLE
[1.7.10 Alpha] Biome Conflict I can't resolve normally

### ISSUE THREAD

**Issue by HyperMan19680** [LemADEC/WarpDrive#82]
24 is asked by: Deep Ocean (net.minecraft.world.biome.BiomeGenOcean), Space (cr0s.warpdrive.world.BiomeSpace)

I saw nothing in the config to change it.

**Comment by TheNumenorean** [comment]
We'll add a config option in the next release. Why is Deep Ocean set to that though? It is not the normal, or we would have seen this error by now.
