### ISSUE TITLE
RFTools compatibility

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#84]
As posted in Curse comments by Notawallplan:
"For a ship to enter a powered planet/dimension, the planet/dimension needs to be powered. This should prevent ships from landing on planets not technically there because their power vanished."

**Comment by LemADEC** [comment]
No idea how to do that.

**Comment by TheNumenorean** [comment]
I dont think this is really within the purview of this mod. In order to allow a ship to go to another dimension anyway, there needs to be a configuration set up for it, and that doesnt really fit with the RFTools mechanic.

**Comment by LemADEC** [comment]
Can't seem to find an easy way without changing RFtools with ASM, so I've opened a ticket on his Github.
We'll have to remember to blacklist certain dimensions depending on the related mod, that's the minimum we should do for now.

**Comment by LemADEC** [comment]
API was updated for us, see https://github.com/McJty/RFTools/issues/318

**Comment by LemADEC** [comment]
See #76
