### ISSUE TITLE
OpenComputers Hologram registered as log for laser tree farm.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [LemADEC/WarpDrive#86]
I looked into FML log to check for any .xml errors (I have no asteroids. AGAIN.) and accidentally saw that WarpDrive registers OC Holograms as log:
`[04:13:59] [Client thread/INFO] [WarpDrive/WarpDrive]: Active blocks dictionnary:`
`[04:13:59] [Client thread/INFO] [WarpDrive/WarpDrive]: - 19 ores: *ores list*`
`[04:13:59] [Client thread/INFO] [WarpDrive/WarpDrive]: - 4 logs: OpenComputers:hologram1, minecraft:log, minecraft:log2, OpenComputers:hologram2`
It's a bit funny, but it is a bug. I think you need to check for `logWood` entries instead of just `log`.
Edit: I'm using 1.3.7 version from GitHub releases, but it applies to the latest dev version too.

**Comment by LemADEC** [comment]
Yes, the 'logs' detection is a bit generous. I'll have to fix that up.
Regarding asteroids, try removing all XML files and rebooting, see if it helps?

**Comment by LemADEC** [comment]
Fixed in 564b6d968eef7a438ead80f35a3ef09deabc286a
