### ISSUE TITLE
Sand spawning in space

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#90]
![2015-09-09_16 30 49](https://cloud.githubusercontent.com/assets/809047/9776728/514fed96-5710-11e5-9a79-e4c7c3f40e4f.png)

**Comment by LemADEC** [comment]
Can't reproduce

**Comment by LemADEC** [comment]
A memory leak on worldObj was fixed.
Issue can't be reproduced before nor after that fix.
Closing until we can actually reproduce it.
