### ISSUE TITLE
Problem with the cloacking device

### ISSUE THREAD

**Issue by carlo9898** [LemADEC/WarpDrive#92]
sorry but i'm stil having some problems with the code of the cloacking device, Computercraft tells me this when i try to activate the cloack ".temp:2: attemp to call nil". I don't know how to solve it, can you help me please?

**Comment by LemADEC** [comment]
Can you share the code you are using?
What version of the mod?
Is it with ComputerCraft or OpenComputers?

**Comment by carlo9898** [comment]
i'm using this code 
c = peripheral.wrap("top")
c.setFieldFrequency(23)
c.setFieldTier(0)
c.enableCloakingField()
if c.isAssemblyValid() then print ("Valid assembly")
else print ("Invalid assembly!")
end

i have the 1.7.10 version and i'm using Computercraft

**Comment by LemADEC** [comment]
Where did you get this code?
This seems like an API from a long time ago...

**Comment by carlo9898** [comment]
yeah, i saw some video on youtube and they use this code

**Comment by LemADEC** [comment]
Cloaking core comes with pre-loaded script to get you an idea how to use it.
You might want to check the wiki too: https://github.com/LemADEC/WarpDrive/wiki/LUA%20API
