### ISSUE TITLE
Moons not showing up during world generation

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#94]
When a new moon is spawned in, most blocks won't show up into the client until they are reloaded

**Comment by CaptainMegavolt** [comment]
I've seen something similar to this. Not sure what caused it.

**Comment by LemADEC** [comment]
I know what's causing it, the issue is either to generate 4 times slower or implement a recovery system

**Comment by CaptainMegavolt** [comment]
Oh ok. It only happened once for me.

_--Supernova Industries Supreme Chairman Megavolt_

**Comment by CaptainMegavolt** [comment]
It happened to me again. I just did /generate moon and i had to reload the world to get it to show up in full. Before I reloaded the world, only a slice of the moon appeared.

**Comment by LemADEC** [comment]
It'll always be there on 1.7.10. Try to do F3+A to reload the chunks around you, should fix it.
