### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#96]
Normal and Hard IC2 sets are missing:
- [x] Warp helmet
- [x] Air tank
- [x] Enantiomorphic reactor & laser
- [ ] Transport beacon

**Comment by YuRaNnNzZZ** [comment]
Warp helmet and air tank does not needed when IC2 is loaded, as IC2 has its own helmet (scuba/quantum) and air cell.

**Comment by LemADEC** [comment]
I want the Warp helmet to absorb the nausea effect during jump.

**Comment by CaptainMegavolt** [comment]
IC2 quantum helmet should absorb nausea effect too.

**Comment by LemADEC** [comment]
Transport beacon recipe will come when the block actually works.
Nausea effect absorption is a different issue.
Recipes are fixed, closing
