### ISSUE TITLE
cr0s.warpdrive.block.TileEntityAbstractInterfaced.hashCode called on client in SSP

### ISSUE THREAD

**Issue by perkinslr** [LemADEC/WarpDrive#97]
This causes a NPE since worldObj.provider is null.  It's called by cofh.lib.util.LinkedHashList if cofh is installed, the solution seems to be to only include the dimension ID if it's server side, since that's the only time warpdrive calls hashCode, and cofh shouldn't ever compare tileentities across dimensions.

**Comment by LemADEC** [comment]
Please provide the use case and full crash logs.

**Comment by perkinslr** [comment]
The use case would be anytime you place a TileEntityAbstractInterfaced (like the ship core), it crashes in SSP, if cofh is installed.  I've already patched my copy and cleaned up, so I don't still have the full logs.  I'm including the stack trace that I used to find where to patch my copy.  

https://gist.github.com/perkinslr/8a288fd9c369e90a8d3c

And here's the patch that made the problem go away.

https://gist.github.com/perkinslr/380817ec90899aeb91c5

If you really need, I can probably roll back to stock and see if I can recreate the original crash, but I'd prefer to avoid taking the time to do that.  For reference, the mods installed were ic2 2.2.2.660, and CoFhCore 3.0.0B9-40, I'm pretty sure there's a newer version of cofh available, and I've not tried it with that, but I doubt it would make a difference.

**Comment by LemADEC** [comment]
I always test with CoFH and IC2 installed in SSP and SMP.
The versions you are referring too are obsolete and have now bugs impacting WarpDrive.

For the record, you are not supposed to use a tile entity before it's fully initialized and worldObj is defined, it's like trying to drive a car home while it's still on the mounting line waiting for its tires.

In short, you'll have to try to reproduce with latest CoFH and IC2.

**Comment by perkinslr** [comment]
Looks like that fixes it, sorry for the extraneous bug report, and thanks for the pointers in tracking down the issue.
