### ISSUE TITLE
Improve documentation of features and how to

### ISSUE THREAD

**Issue by Laurelai** [LemADEC/WarpDrive#98]
Its frankly a mess. Not enough details or specifics. No sane default code for enantiomorphic reactor use. People should not have to learn lua to use a minecraft mod. Better documentation of how to construct a warp drive. laser cannon has virtually no documentation except a picture that tells you to build it like that with nothing labeled. Overall the user friendliness needs to be improved. Doing so will make this a more popular mod.

**Comment by LemADEC** [comment]
Did you actually check the Wiki for the mod?

**Comment by Laurelai** [comment]
Yes. How else do you think i wound up here?
Laser setup https://github.com/LemADEC/WarpDrive/wiki/Laser%20setup%20(basic)
 Enantiomorphic reactor https://github.com/LemADEC/WarpDrive/wiki/Enantiomorphic%20reactor

Oh look the camera and monitor page doesnt even exist but your index says it does https://github.com/LemADEC/WarpDrive/wiki/Camera%20and%20Monitor

Did you actually check your own wiki?

**Comment by Harkole** [comment]
I am struggling with the EnanReactor too, just spent 3 hours trying to get it working without success (lots of holes in the ground however). Reactor works with ComputerCraft but lasers never fire, even though they are detected, to stablise it, if you're lucky you can dump the power before it explodes.

OpenComputers doesn't interface with the startup script and with the API documentation on the wiki stating to use methods (eg sendLaser) that don't exist it's impossible to start coding something to use those. 

So unless there is a wiki somewhere other than GitHub that I'm failing to find, I'd like to see updated help too please.

**Comment by LemADEC** [comment]
@Laurelai 
Yes, Camera & monitor page is empty for now.
Laser canon has 2 pages dedicated to it, plus the API description, that's far from nothing.
Enantiomorphic reactor has no default script for OpenComputers, there's already a ticket open for it, and that's one of the reason the mod isn't 'released'.
Similarly, in-game tool tips and recipes are missing on many blocks. Our priority is to have something functional, which sadly implies that the documentation is on hold.

@Harkole
There's no prebuilt script for Enantiomorphic reactor with OpenComputers. Interface is there but you'll need to translate the script from ComputerCraft or make your own.
sendLaser() is the from the legacy API, the new one is stabilize().
The LUA API page explains how the API changed => https://github.com/LemADEC/WarpDrive/wiki/LUA%20API#legacy-api
API is still changing, I'll resync all detailed pages later on.

**Comment by Laurelai** [comment]
I read the laser pages i linked one of them to you and told you specifically what the issue was.
"1) Set up your laser as shown in the image"

The image has no labels so how can one know what blocks are where? A verbal description of what blocks need to go where would make life easier for everyone.

**Comment by Harkole** [comment]
Thanks I'd looked but missed the sendLaser() legacy match up, I'll have another go.

Could you confirm that the block next to the EnanReactorLaser is a LaserMedium? Also do I need to link the medium to the Reactor Laser as when I query it I get the response "unknown 0 0 0" in OpenComputers and as I mentioned above the CompuerCraft lasers never fire despite being detected. 

After further testing, I think there is a bug with the lasers (if it is the LaserMedium block) they take a charge, then if you remove the power source and fire the lasers via ComputerCraft no energy is used although the reactor output does appear to be affected by something. You can't use the lasers to try maintain a stability thought which means that you have to find a passive output configuration to be able to use it.

By the way I'm running the Dev build 1.3.10

Below is the set up (both complete then with power source removed from laser), right clicking on the LaserMedium shows a 10000 EU charge at all times.

![image](https://cloud.githubusercontent.com/assets/3703699/10267392/38a0dd86-6a8a-11e5-9f5b-11fbcdaf01a8.png)
![image](https://cloud.githubusercontent.com/assets/3703699/10267394/5ed0ac66-6a8a-11e5-9daf-f34d4012633b.png)
![image](https://cloud.githubusercontent.com/assets/3703699/10267397/7de79948-6a8a-11e5-92c8-1a2f6ba10aa1.png)
![image](https://cloud.githubusercontent.com/assets/3703699/10267400/8f90796c-6a8a-11e5-86de-8b25a2569219.png)
Having fired the lasers (pressing and holding L on ComputerCraft for about 15 seconds) the LaserMedium still has a full charge despite being disconnected
![image](https://cloud.githubusercontent.com/assets/3703699/10267404/b0bd88f0-6a8a-11e5-83c5-69512c4ecff3.png)

**Comment by LemADEC** [comment]
All your reactor laser are reporting 0 energy in stock, hence they won't fire.
The reactor laser only accept a laser medium above or below it.

**Comment by Harkole** [comment]
Duly noted, am I able to update the wiki with the new layout?

Confirmed that the lasers are now working as expected and can stablise the core when placed above or below the emitter.

**Comment by LemADEC** [comment]
What do you mean by new layout? you mean with updated pictures due to the new textures?

**Comment by Harkole** [comment]
I see you've updated the page, but I was more meaning that it used to state side by side and yes the screen shots could do with an update too as they still show a side/side layout.

Thanks for the extra information about the reactor in terms of programming though :+1:  :)

I still have a lot of experimenting to do with this structure as so far I'm not making any really worth while energy values once I've powered the lasers to keep things stable

**Comment by LemADEC** [comment]
The bottom screenshots are indeed completely misleading, didn't realize it.

**Comment by LemADEC** [comment]
Laser pages have been fixed. I'll create another ticket for the remaining issues.

**Comment by Laurelai** [comment]
So are you going to address the rest of the issues or not?

**Comment by LemADEC** [comment]
I've already answered about 'other issues'.
